In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, make_scorer, mean_absolute_error
from sklearn.model_selection import GridSearchCV

In [54]:
#data = pd.read_csv('BS_train_data.csv')
#data

In [3]:
data = pd.read_csv('DeltaBS_data.csv')
data

Company        Time  Total Assets  Total Liabilities  Total Equity  \
0       SIRI  2019-12-01        2976.0             1895.0        1081.0   
1       NEWT  2015-12-01          50.6               13.1          37.5   
2        ADM  2019-12-01        3164.0             2926.0         238.0   
3        PXD  2017-12-01         544.0             -324.0         868.0   
4       TROW  2018-12-01         153.9              106.5          47.4   
5        PRU  2013-12-01       22546.0            25777.0       -3231.0   
6        LEG  2017-12-01         566.7              469.9          96.8   
7        ADS  2012-12-01        3019.9             2667.4         352.5   
8        PPG  2018-12-01        -523.0              417.0        -940.0   
9         VZ  2015-12-01       11559.0             7393.0        4166.0   
10       CAT  2012-12-01        7752.0             3572.0        4180.0   
11       SWK  2017-12-01        3462.8             1531.4        1931.4   
12       TXN  2015-12-01       -1142.0             -698.0        -444.0   
13     JSAIY  2014-03-01        8279.3             7132.8        1146.5   
14       XRX  2017-12-01       -2105.0            -2651.0         546.0   
15        GL  2015-12-01        -419.1              222.9        -641.9   
16      YORW  2018-12-01          13.1                6.3           6.8   
17       LEN  2019-11-01         793.3             -557.5        1350.8   
18       AJG  2012-12-01         868.8              453.8         415.0   
19       LNC  2017-12-01       20136.0            17292.0        2844.0   
20       OII  2014-12-01         376.4              762.4        -385.9   
21       PKG  2015-12-01          -0.5             -112.4         111.9   
22       FSM  2015-12-01          29.4               37.9          -8.5   
23       APD  2019-09-01        -235.5             -447.5         212.0   
24      MSCI  2014-12-01        -253.6             -122.1        -131.5   
25      AMGN  2018-12-01      -13538.0             -797.0      -12741.0   
26      MKTX  2013-12-01          74.1                6.4          67.7   
27      SPGI  2014-12-01         712.0             1517.0        -805.0   
28      VRSN  2013-12-01         598.3             1012.5        -414.3   
29       PPG  2013-12-01         -15.0             -891.0         876.0   
...      ...         ...           ...                ...           ...   
4470     TJX  2019-02-01         268.0              367.7         -99.7   
4471     AAL  2019-12-01        -585.0             -636.0          51.0   
4472    CTXS  2018-12-01        -684.2             -243.2        -441.0   
4473     ROK  2015-09-01         180.4              581.7        -401.3   
4474     ABC  2015-09-01        6430.8             7771.3       -1340.5   
4475     THS  2017-12-01        -766.5             -526.5        -240.0   
4476     FLO  2019-12-01         332.3              327.0           5.1   
4477     DEO  2013-06-01        2927.0             1317.4        1609.6   
4478     MAR  2019-12-01        1355.0             2877.0       -1522.0   
4479    DLTR  2016-01-01       12408.5             9786.6        2621.9   
4480    SNPS  2018-10-01         749.6              544.3         205.3   
4481     UTL  2018-12-01          56.4               41.9          14.5   
4482   JSAIY  2013-03-01        -322.8             -246.7         -76.1   
4483    SIRI  2018-12-01        -156.4              136.8        -293.1   
4484     IFF  2015-12-01         207.4              135.1          72.3   
4485       A  2013-10-01         150.0               46.0         104.0   
4486     PHM  2018-12-01         486.4             -177.4         663.8   
4487     SYY  2019-06-01        -103.9              -97.3          -6.6   
4488     FCX  2012-12-01        3370.0              612.0        2758.0   
4489    NTAP  2019-04-01       -1250.0              -64.0       -1186.0   
4490     ALL  2019-12-01        7701.0             3015.0        4686.0   
4491     VMC  2018-12-01      

In [5]:
prices = data['Price_Change'] 
data = data.drop(['Company', 'Time', 'Price_Change'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")

Total Assets
Done
Total Liabilities
Done
Total Equity
Done
Total Shares Out. on Filing Date
Done
Book Value / Share
Done
Tangible Book Value
Done
Tangible Book Value Per Share
Done
Total Debt
Done
Net Debt
Done


In [6]:
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Price_Change', prices)
data

Total Assets  Total Liabilities  Total Equity  \
0         0.567761           0.674890      0.524838   
1         0.558627           0.667503      0.518225   
2         0.568348           0.678937      0.519496   
3         0.560168           0.666180      0.523488   
4         0.558950           0.667870      0.518288   
5         0.628862           0.768633      0.497513   
6         0.560238           0.669296      0.518601   
7         0.567898           0.677922      0.520221   
8         0.556836           0.669089      0.512031   
9         0.594558           0.696471      0.544388   
10        0.582672           0.681473      0.544476   
11        0.569281           0.673463      0.530227   
12        0.554904           0.664712      0.515174   
13        0.584318           0.695450      0.525253   
14        0.551897           0.657046      0.521448   
15        0.557161           0.668327      0.513920   
16        0.558510           0.667476      0.518031   
17        0.560946           0.665263      0.526548   
18        0.561182           0.669233      0.520617   
19        0.621337           0.735327      0.536010   
20        0.559644           0.670444      0.515542   
21        0.558468           0.667011      0.518697   
22        0.558561           0.667600      0.517934   
23        0.557734           0.665695      0.519331   
24        0.557677           0.666972      0.517154   
25        0.516201           0.664323      0.437248   
26        0.558700           0.667477      0.518417   
27        0.560692           0.673406      0.512886   
28        0.560337           0.671426      0.515362   
29        0.558422           0.663954      0.523539   
...            ...                ...           ...   
4470      0.559306           0.668895      0.517356   
4471      0.556643           0.664955      0.518311   
4472      0.556333           0.666497      0.515193   
4473      0.559032           0.669735      0.515445   
4474      0.578547           0.697956      0.509493   
4475      0.556076           0.665385      0.516467   
4476      0.559507           0.668735      0.518020   
4477      0.567608           0.672623      0.528188   
4478      0.562700           0.678745      0.508343   
4479      0.597211           0.705867      0.534603   
4480      0.560809           0.669588      0.519289   
4481      0.558645           0.667616      0.518080   
4482      0.557461           0.666483      0.517505   
4483      0.557981           0.667989      0.516130   
4484      0.559117           0.667982      0.518446   
4485      0.558937           0.667632      0.518647   
4486      0.559988           0.666755      0.522194   
4487      0.558145           0.667070      0.517946   
4488      0.568991           0.669854      0.535465   
4489      0.554566           0.667201      0.510472   
4490      0.582513           0.679286      0.547683   
4491      0.559491           0.667818      0.519470   
4492      0.610085           0.727669      0.525535   
4493      0.558500           0.667471      0.518019   
4494      0.554205           0.659547      0.522096   
4495      0.564323           0.673108      0.520738   
4496      0.559164           0.668671      0.517430   
4497      0.567258           0.672637      0.527455   
4498      0.581189           0.694308      0.520744   
4499      0.560183           0.670366      0.516761   

      Total Shares Out. on Filing Date  Book Value / Share  \
0                             0.209157            0.001012   
1                             0.206439            0.000961   
2                             0.206162            0.001017   
3                             0.206277            0.001108   
4                             0.205911            0.001047   
5                             0.206171            0.000871   
6                             0.206107            0.001024   
7                             0.206252            0.001152   
8                             0.20565

In [7]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:9] # Parameters
y = NpMatrix[:,9] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.56776064 0.67489009 0.52483793 ... 0.15652723 0.66016046 0.60947678]
 [0.55862704 0.66750314 0.51822526 ... 0.1564935  0.649944   0.60069462]
 [0.56834761 0.67893704 0.51949583 ... 0.15649596 0.66054083 0.61740799]
 ...
 [0.56725797 0.67263699 0.52745512 ... 0.1565369  0.65582847 0.60690295]
 [0.5811891  0.69430837 0.52074422 ... 0.15652372 0.67007121 0.60685211]
 [0.56018282 0.67036623 0.51676141 ... 0.15630548 0.65148239 0.60218744]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 9
Total Number of Training instances: 4500


[  1.44   1.87   5.38 ...   5.83  77.77 334.81]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 1.44
Total number of y values 4500


In [59]:
#X_train, X_test, y_train, y_test = train_test_split(X , y, test_size = 0.2, random_state = 42) # 42, 56, 66, 87

In [8]:
# Hyperparameter Grid Search
#criterion = {'mse', 'friedman_mse', 'mae'}
#'criterion' : ['mse', 'mae'],
#  'criterion' : {'mse', 'friedman_mse', 'mae'}
params = {
        'splitter' : ['best', 'random'],
          'max_depth': range(1,50), 
         }

decision_tree = DecisionTreeRegressor()
#mse = make_scorer(mean_squared_error, greater_is_better= False)
mae = make_scorer(mean_absolute_error, greater_is_better= False)

#gs_decision_tree = GridSearchCV(decision_tree, params, scoring = mae,  cv=10)
gs_decision_tree = GridSearchCV(decision_tree, params, scoring = mae,  cv=5)

grid_results = gs_decision_tree.fit(X , y)

# Best parameters, best test score using these parameters, optimal KNN Configuration
print("Best Parameters", gs_decision_tree.best_params_)
print("Best score on Test Data", gs_decision_tree.best_score_)
print("Optimal Configuration", gs_decision_tree.best_estimator_)

Best Parameters {'max_depth': 10, 'splitter': 'random'}
Best score on Test Data -16.171624884688924
Optimal Configuration DecisionTreeRegressor(criterion='mse', max_depth=10, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='random')


In [11]:
# Summarize the results in a readable format
print("Best: {0}, using {1}".format(grid_results.cv_results_['mean_test_score'], grid_results.best_params_))
results_df = pd.DataFrame(grid_results.cv_results_)
results_df

Best: [-16.68447533 -16.35672173 -16.8040424  -16.23600132 -16.93804795
 -16.43916355 -16.96460135 -16.96565695 -16.71649752 -16.82863854
 -16.63247825 -17.45300447 -17.07467513 -17.22776289 -17.09658483
 -17.0914029  -17.32546761 -18.49118639 -18.18608234 -16.17162488
 -18.01278174 -17.9232883  -18.48810216 -16.76384429 -18.94811432
 -17.40821695 -19.43343804 -18.29208692 -19.58690995 -17.70404915
 -19.94443898 -19.10170131 -20.37709961 -18.28316151 -20.6285827
 -18.83036    -21.63625968 -19.7512209  -21.80090921 -19.09152201
 -22.00494515 -20.26752966 -22.20279734 -21.63079177 -22.58186283
 -20.55872872 -22.48909454 -21.8596042  -22.94346545 -20.89217611
 -22.99204826 -22.57336964 -23.2387983  -21.03977005 -23.56692596
 -21.84509303 -23.19998577 -22.78736326 -23.68268722 -22.76727059
 -23.76318368 -24.48213611 -23.80982889 -22.91699594 -24.17904344
 -23.79015262 -24.05020449 -23.01142437 -23.90111591 -23.73004179
 -23.41575309 -24.63279724 -23.75524317 -23.34541493 -23.76291424
 -23.

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.005798  2.216013e-03         0.000209        0.000418   
1        0.000000  0.000000e+00         0.000805        0.001610   
2        0.007188  1.604920e-03         0.000000        0.000000   
3        0.001600  1.959809e-03         0.000000        0.000000   
4        0.008233  4.588898e-04         0.000800        0.001600   
5        0.000799  1.597786e-03         0.000000        0.000000   
6        0.010386  1.955907e-03         0.000000        0.000000   
7        0.001598  1.956957e-03         0.000000        0.000000   
8        0.013582  1.955888e-03         0.000000        0.000000   
9        0.000799  1.597404e-03         0.000799        0.001598   
10       0.015978  2.617832e-06         0.000000        0.000000   
11       0.000799  1.598263e-03         0.000799        0.001598   
12       0.017576  1.957328e-03         0.000000        0.000000   
13       0.000000  0.000000e+00         0.000799        0.001598   
14       0.019973  4.862804e-07         0.000000        0.000000   
15       0.002397  1.956958e-03         0.000000        0.000000   
16       0.023957  2.554117e-03         0.000000        0.000000   
17       0.001598  1.957055e-03         0.000000        0.000000   
18       0.027955  6.193971e-03         0.000799        0.001598   
19       0.002396  1.955986e-03         0.001599        0.001959   
20       0.045538  6.967801e-03         0.000798        0.001596   
21       0.003994  9.311642e-06         0.001599        0.001958   
22       0.033566  1.962098e-03         0.000799        0.001598   
23       0.003993  2.603959e-05         0.000000        0.000000   
24       0.035742  3.995767e-04         0.000000        0.000000   
25       0.003995  2.156707e-05         0.000000        0.000000   
26       0.032160  4.198956e-03         0.000817        0.001635   
27       0.004002  1.427281e-05         0.000000        0.000000   
28       0.033555  1.956355e-03         0.000000        0.000000   
29       0.002397  1.956958e-03         0.000000        0.000000   
..            ...           ...              ...             ...   
68       0.052729  2.988267e-03         0.000000        0.000000   
69       0.008789  1.615839e-03         0.000799        0.001598   
70       0.054569  4.367947e-03         0.000799        0.001597   
71       0.016781  5.872233e-03         0.000000        0.000000   
72       0.068920  9.236122e-03         0.000611        0.001223   
73       0.009587  1.958477e-03         0.000800        0.001599   
74       0.052729  2.989376e-03         0.000000        0.000000   
75       0.009587  1.957055e-03         0.000000        0.000000   
76       0.059910  4.401325e-03         0.000000        0.000000   
77       0.011983  2.371928e-05         0.000000        0.000000   
78       0.060720  5.302263e-03         0.000000        0.000000   
79       0.011185  1.596092e-03         0.000799        0.001598   
80       0.061520  4.073231e-03         0.000000        0.000000   
81       0.011964  2.326604e-05         0.000809        0.001618   
82       0.063115  4.659424e-03         0.000807        0.001614   
83       0.009580  1.963374e-03         0.001605        0.001966   
84       0.053529  3.192473e-03         0.000000        0.000000   
85       0.010393  1.952843e-03         0.000792        0.001584   
86       0.063808  1.116086e-02         0.000800        0.001600   
87       0.009587  1.957620e-03         0.000799        0.001598   
88       0.063715  1.203849e-02         0.001598        0.001957   
89       0.012782  1.597584e-03         0.000799        0.001599   
90       0.069507  1.351335e-02         0.000799        0.001598   
91       0.011984  1.114208e-06         0.000799        0.001598   
92       0.058314  5.428222e-03         0.001606        0.001967   
93       0.011991  1.686710e-05         0.000000        0.000000   
94       0.052841  1.655709e-03         0.000000        0.00

In [12]:
results_df = results_df.sort_values(['rank_test_score'])
results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
19       0.002396  1.955986e-03         0.001599        0.001959   
3        0.001600  1.959809e-03         0.000000        0.000000   
1        0.000000  0.000000e+00         0.000805        0.001610   
5        0.000799  1.597786e-03         0.000000        0.000000   
10       0.015978  2.617832e-06         0.000000        0.000000   
0        0.005798  2.216013e-03         0.000209        0.000418   
8        0.013582  1.955888e-03         0.000000        0.000000   
23       0.003993  2.603959e-05         0.000000        0.000000   
2        0.007188  1.604920e-03         0.000000        0.000000   
9        0.000799  1.597404e-03         0.000799        0.001598   
4        0.008233  4.588898e-04         0.000800        0.001600   
6        0.010386  1.955907e-03         0.000000        0.000000   
7        0.001598  1.956957e-03         0.000000        0.000000   
12       0.017576  1.957328e-03         0.000000        0.000000   
15       0.002397  1.956958e-03         0.000000        0.000000   
14       0.019973  4.862804e-07         0.000000        0.000000   
13       0.000000  0.000000e+00         0.000799        0.001598   
16       0.023957  2.554117e-03         0.000000        0.000000   
25       0.003995  2.156707e-05         0.000000        0.000000   
11       0.000799  1.598263e-03         0.000799        0.001598   
29       0.002397  1.956958e-03         0.000000        0.000000   
21       0.003994  9.311642e-06         0.001599        0.001958   
20       0.045538  6.967801e-03         0.000798        0.001596   
18       0.027955  6.193971e-03         0.000799        0.001598   
33       0.004783  1.576331e-03         0.000808        0.001616   
27       0.004002  1.427281e-05         0.000000        0.000000   
22       0.033566  1.962098e-03         0.000799        0.001598   
17       0.001598  1.957055e-03         0.000000        0.000000   
35       0.004793  1.598931e-03         0.000806        0.001612   
24       0.035742  3.995767e-04         0.000000        0.000000   
..            ...           ...              ...             ...   
91       0.011984  1.114208e-06         0.000799        0.001598   
92       0.058314  5.428222e-03         0.001606        0.001967   
80       0.061520  4.073231e-03         0.000000        0.000000   
94       0.052841  1.655709e-03         0.000000        0.000000   
86       0.063808  1.116086e-02         0.000800        0.001600   
58       0.057524  8.221301e-03         0.000000        0.000000   
84       0.053529  3.192473e-03         0.000000        0.000000   
69       0.008789  1.615839e-03         0.000799        0.001598   
72       0.068920  9.236122e-03         0.000611        0.001223   
74       0.052729  2.989376e-03         0.000000        0.000000   
60       0.063978  7.256085e-03         0.000791        0.001582   
75       0.009587  1.957055e-03         0.000000        0.000000   
78       0.060720  5.302263e-03         0.000000        0.000000   
65       0.011185  1.598216e-03         0.000000        0.000000   
90       0.069507  1.351335e-02         0.000799        0.001598   
62       0.051930  3.573325e-03         0.000799        0.001599   
88       0.063715  1.203849e-02         0.001598        0.001957   
85       0.010393  1.952843e-03         0.000792        0.001584   
68       0.052729  2.988267e-03         0.000000        0.000000   
96       0.055130  3.009297e-03         0.000000        0.000000   
97       0.010391  1.944721e-03         0.000000        0.000000   
66       0.053528  4.059552e-03         0.000000        0.000000   
83       0.009580  1.963374e-03         0.001605        0.001966   
82       0.063115  4.659424e-03         0.000807        0.001614   
64       0.060726  1.055353e-02         0.000000        0.000000   
77       0.011983  2.371928e-05         0.000000        0.000000   
61       0.007991  2.461487e-05         0.000000        0.00