In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsRegressor 
from sklearn.metrics import mean_squared_error, make_scorer, mean_absolute_error
from sklearn.model_selection import GridSearchCV

In [2]:
data = pd.read_csv('DeltaBS_data.csv')
data

Company        Time  Total Assets  Total Liabilities  Total Equity  \
0       SIRI  2019-12-01        2976.0             1895.0        1081.0   
1       NEWT  2015-12-01          50.6               13.1          37.5   
2        ADM  2019-12-01        3164.0             2926.0         238.0   
3        PXD  2017-12-01         544.0             -324.0         868.0   
4       TROW  2018-12-01         153.9              106.5          47.4   
5        PRU  2013-12-01       22546.0            25777.0       -3231.0   
6        LEG  2017-12-01         566.7              469.9          96.8   
7        ADS  2012-12-01        3019.9             2667.4         352.5   
8        PPG  2018-12-01        -523.0              417.0        -940.0   
9         VZ  2015-12-01       11559.0             7393.0        4166.0   
10       CAT  2012-12-01        7752.0             3572.0        4180.0   
11       SWK  2017-12-01        3462.8             1531.4        1931.4   
12       TXN  2015-12-01       -1142.0             -698.0        -444.0   
13     JSAIY  2014-03-01        8279.3             7132.8        1146.5   
14       XRX  2017-12-01       -2105.0            -2651.0         546.0   
15        GL  2015-12-01        -419.1              222.9        -641.9   
16      YORW  2018-12-01          13.1                6.3           6.8   
17       LEN  2019-11-01         793.3             -557.5        1350.8   
18       AJG  2012-12-01         868.8              453.8         415.0   
19       LNC  2017-12-01       20136.0            17292.0        2844.0   
20       OII  2014-12-01         376.4              762.4        -385.9   
21       PKG  2015-12-01          -0.5             -112.4         111.9   
22       FSM  2015-12-01          29.4               37.9          -8.5   
23       APD  2019-09-01        -235.5             -447.5         212.0   
24      MSCI  2014-12-01        -253.6             -122.1        -131.5   
25      AMGN  2018-12-01      -13538.0             -797.0      -12741.0   
26      MKTX  2013-12-01          74.1                6.4          67.7   
27      SPGI  2014-12-01         712.0             1517.0        -805.0   
28      VRSN  2013-12-01         598.3             1012.5        -414.3   
29       PPG  2013-12-01         -15.0             -891.0         876.0   
...      ...         ...           ...                ...           ...   
4470     TJX  2019-02-01         268.0              367.7         -99.7   
4471     AAL  2019-12-01        -585.0             -636.0          51.0   
4472    CTXS  2018-12-01        -684.2             -243.2        -441.0   
4473     ROK  2015-09-01         180.4              581.7        -401.3   
4474     ABC  2015-09-01        6430.8             7771.3       -1340.5   
4475     THS  2017-12-01        -766.5             -526.5        -240.0   
4476     FLO  2019-12-01         332.3              327.0           5.1   
4477     DEO  2013-06-01        2927.0             1317.4        1609.6   
4478     MAR  2019-12-01        1355.0             2877.0       -1522.0   
4479    DLTR  2016-01-01       12408.5             9786.6        2621.9   
4480    SNPS  2018-10-01         749.6              544.3         205.3   
4481     UTL  2018-12-01          56.4               41.9          14.5   
4482   JSAIY  2013-03-01        -322.8             -246.7         -76.1   
4483    SIRI  2018-12-01        -156.4              136.8        -293.1   
4484     IFF  2015-12-01         207.4              135.1          72.3   
4485       A  2013-10-01         150.0               46.0         104.0   
4486     PHM  2018-12-01         486.4             -177.4         663.8   
4487     SYY  2019-06-01        -103.9              -97.3          -6.6   
4488     FCX  2012-12-01        3370.0              612.0        2758.0   
4489    NTAP  2019-04-01       -1250.0              -64.0       -1186.0   
4490     ALL  2019-12-01        7701.0             3015.0        4686.0   
4491     VMC  2018-12-01      

In [3]:
prices = data['Price_Change'] 
data = data.drop(['Company', 'Time', 'Price_Change'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")

Total Assets
Done
Total Liabilities
Done
Total Equity
Done
Total Shares Out. on Filing Date
Done
Book Value / Share
Done
Tangible Book Value
Done
Tangible Book Value Per Share
Done
Total Debt
Done
Net Debt
Done


In [4]:
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Price_Change', prices)
data

Total Assets  Total Liabilities  Total Equity  \
0         0.567761           0.674890      0.524838   
1         0.558627           0.667503      0.518225   
2         0.568348           0.678937      0.519496   
3         0.560168           0.666180      0.523488   
4         0.558950           0.667870      0.518288   
5         0.628862           0.768633      0.497513   
6         0.560238           0.669296      0.518601   
7         0.567898           0.677922      0.520221   
8         0.556836           0.669089      0.512031   
9         0.594558           0.696471      0.544388   
10        0.582672           0.681473      0.544476   
11        0.569281           0.673463      0.530227   
12        0.554904           0.664712      0.515174   
13        0.584318           0.695450      0.525253   
14        0.551897           0.657046      0.521448   
15        0.557161           0.668327      0.513920   
16        0.558510           0.667476      0.518031   
17        0.560946           0.665263      0.526548   
18        0.561182           0.669233      0.520617   
19        0.621337           0.735327      0.536010   
20        0.559644           0.670444      0.515542   
21        0.558468           0.667011      0.518697   
22        0.558561           0.667600      0.517934   
23        0.557734           0.665695      0.519331   
24        0.557677           0.666972      0.517154   
25        0.516201           0.664323      0.437248   
26        0.558700           0.667477      0.518417   
27        0.560692           0.673406      0.512886   
28        0.560337           0.671426      0.515362   
29        0.558422           0.663954      0.523539   
...            ...                ...           ...   
4470      0.559306           0.668895      0.517356   
4471      0.556643           0.664955      0.518311   
4472      0.556333           0.666497      0.515193   
4473      0.559032           0.669735      0.515445   
4474      0.578547           0.697956      0.509493   
4475      0.556076           0.665385      0.516467   
4476      0.559507           0.668735      0.518020   
4477      0.567608           0.672623      0.528188   
4478      0.562700           0.678745      0.508343   
4479      0.597211           0.705867      0.534603   
4480      0.560809           0.669588      0.519289   
4481      0.558645           0.667616      0.518080   
4482      0.557461           0.666483      0.517505   
4483      0.557981           0.667989      0.516130   
4484      0.559117           0.667982      0.518446   
4485      0.558937           0.667632      0.518647   
4486      0.559988           0.666755      0.522194   
4487      0.558145           0.667070      0.517946   
4488      0.568991           0.669854      0.535465   
4489      0.554566           0.667201      0.510472   
4490      0.582513           0.679286      0.547683   
4491      0.559491           0.667818      0.519470   
4492      0.610085           0.727669      0.525535   
4493      0.558500           0.667471      0.518019   
4494      0.554205           0.659547      0.522096   
4495      0.564323           0.673108      0.520738   
4496      0.559164           0.668671      0.517430   
4497      0.567258           0.672637      0.527455   
4498      0.581189           0.694308      0.520744   
4499      0.560183           0.670366      0.516761   

      Total Shares Out. on Filing Date  Book Value / Share  \
0                             0.209157            0.001012   
1                             0.206439            0.000961   
2                             0.206162            0.001017   
3                             0.206277            0.001108   
4                             0.205911            0.001047   
5                             0.206171            0.000871   
6                             0.206107            0.001024   
7                             0.206252            0.001152   
8                             0.20565

In [5]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:9] # Parameters
y = NpMatrix[:,9] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.56776064 0.67489009 0.52483793 ... 0.15652723 0.66016046 0.60947678]
 [0.55862704 0.66750314 0.51822526 ... 0.1564935  0.649944   0.60069462]
 [0.56834761 0.67893704 0.51949583 ... 0.15649596 0.66054083 0.61740799]
 ...
 [0.56725797 0.67263699 0.52745512 ... 0.1565369  0.65582847 0.60690295]
 [0.5811891  0.69430837 0.52074422 ... 0.15652372 0.67007121 0.60685211]
 [0.56018282 0.67036623 0.51676141 ... 0.15630548 0.65148239 0.60218744]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 9
Total Number of Training instances: 4500


[  1.44   1.87   5.38 ...   5.83  77.77 334.81]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 1.44
Total number of y values 4500


In [6]:
# Grid Search for Optimal KNN Hyperparameters
# Using GridSearchCV to find best parameters
kvals = range(1,100)
params = {'n_neighbors': kvals,
        'weights' : ['uniform', 'distance'],
         'metric' : ['euclidean', 'manhattan']}

knn = KNeighborsRegressor()
#mse = make_scorer(mean_squared_error, greater_is_better= False)
mae = make_scorer(mean_absolute_error, greater_is_better= False)

gs_modelKNN = GridSearchCV(knn, params, scoring = mae,  cv=5)
grid_results = gs_modelKNN.fit(X , y)

# Best parameters, best test score using these parameters, optimal KNN Configuration
print("Best Parameters", gs_modelKNN.best_params_)
print("Best score on Test Data", gs_modelKNN.best_score_)
print("Optimal Configuration", gs_modelKNN.best_estimator_)

Best Parameters {'metric': 'manhattan', 'n_neighbors': 99, 'weights': 'distance'}
Best score on Test Data -15.947575300779546
Optimal Configuration KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='manhattan',
                    metric_params=None, n_jobs=None, n_neighbors=99, p=2,
                    weights='distance')


In [9]:
# Summarize the results in a readable format
print("Best: {0}, using {1}".format(grid_results.cv_results_['mean_test_score'], grid_results.best_params_))
results_df = pd.DataFrame(grid_results.cv_results_)
results_df

Best: [-23.26146    -23.26146    -20.77969222 -20.76936987 -19.35353111
 -19.40577775 -18.76155278 -18.78600284 -18.37645467 -18.39274905
 -17.89638815 -17.94524098 -17.72755587 -17.75532685 -17.58501361
 -17.60792708 -17.4416158  -17.45983577 -17.26458689 -17.29168525
 -17.19625636 -17.20585549 -17.12579926 -17.13153612 -17.05237299
 -17.04320397 -16.97594841 -16.97080583 -16.96162178 -16.93985712
 -16.91578431 -16.88965996 -16.84922523 -16.82465323 -16.75165556
 -16.73831915 -16.6899807  -16.67863332 -16.66661033 -16.65804159
 -16.63663767 -16.62127488 -16.59975273 -16.58206666 -16.55093372
 -16.53651058 -16.52177546 -16.50927891 -16.49329636 -16.48466561
 -16.44288949 -16.43922939 -16.43050996 -16.4243805  -16.39957381
 -16.39493376 -16.37958989 -16.37332728 -16.37049141 -16.36313243
 -16.35575971 -16.3465093  -16.33469937 -16.33035268 -16.32705764
 -16.318661   -16.30379235 -16.29443782 -16.30372432 -16.29097235
 -16.29229265 -16.27878389 -16.28708144 -16.26650554 -16.26166216
 -16

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0         0.003750  3.920330e-03         0.024185        0.008927   
1         0.002397  1.957542e-03         0.016733        0.002943   
2         0.001598  1.957523e-03         0.016409        0.002669   
3         0.001598  1.957639e-03         0.015179        0.001597   
4         0.003197  1.598334e-03         0.016777        0.002989   
5         0.000000  0.000000e+00         0.018375        0.003196   
6         0.000800  1.599312e-03         0.019174        0.001597   
7         0.002398  1.958361e-03         0.017575        0.001958   
8         0.000799  1.598167e-03         0.021585        0.005425   
9         0.000799  1.597118e-03         0.019974        0.002527   
10        0.003197  1.598359e-03         0.019174        0.002989   
11        0.000799  1.598835e-03         0.021575        0.001956   
12        0.000799  1.597786e-03         0.022368        0.001955   
13        0.000800  1.599026e-03         0.020769        0.001600   
14        0.000800  1.599312e-03         0.022370        0.003196   
15        0.002397  1.957198e-03         0.020772        0.001602   
16        0.002398  1.957971e-03         0.021570        0.001958   
17        0.000799  1.597786e-03         0.026365        0.004067   
18        0.001565  1.919024e-03         0.032467        0.012767   
19        0.001600  1.959334e-03         0.023167        0.002992   
20        0.000798  1.596546e-03         0.023972        0.002519   
21        0.001595  1.954078e-03         0.023176        0.001606   
22        0.001599  1.958347e-03         0.023966        0.004382   
23        0.001607  1.968025e-03         0.028756        0.003001   
24        0.001608  1.969063e-03         0.029540        0.007394   
25        0.002398  1.958126e-03         0.030358        0.003215   
26        0.003033  2.725938e-03         0.035184        0.013702   
27        0.002409  1.966850e-03         0.031376        0.001769   
28        0.000803  1.605034e-03         0.030362        0.001936   
29        0.000809  1.618385e-03         0.030350        0.003197   
..             ...           ...              ...             ...   
366       0.001600  1.959391e-03         0.046336        0.003198   
367       0.003197  1.598382e-03         0.045539        0.004075   
368       0.003196  1.598144e-03         0.047946        0.002525   
369       0.000798  1.596642e-03         0.048731        0.003022   
370       0.000000  0.000000e+00         0.049533        0.001956   
371       0.003212  1.606017e-03         0.045516        0.001959   
372       0.001608  1.969149e-03         0.049532        0.005980   
373       0.001599  1.958165e-03         0.047936        0.002526   
374       0.001598  1.956880e-03         0.048734        0.003900   
375       0.001598  1.957582e-03         0.047935        0.002521   
376       0.001598  1.957057e-03         0.049537        0.005414   
377       0.000798  1.596928e-03         0.048737        0.002989   
378       0.001598  1.956997e-03         0.048731        0.002975   
379       0.001609  1.970075e-03         0.053889        0.011343   
380       0.003997  1.619843e-06         0.103129        0.006216   
381       0.003993  1.297137e-06         0.100661        0.004684   
382       0.005605  1.957701e-03         0.121425        0.016691   
383       0.003994  2.718390e-06         0.104669        0.004653   
384       0.003189  1.594616e-03         0.107722        0.012085   
385       0.003195  1.597621e-03         0.104663        0.002966   
386       0.003992  6.882001e-06         0.106269        0.004799   
387       0.003994  2.552732e-05         0.106250        0.005412   
388       0.004003  1.400100e-05         0.104711        0.005034   
389       0.003219  1.609625e-03         0.103854        0.005628   
390       0.003993  9.464947e-07         0.104662        0.006371   
391       0.004794  1.598573e-03         0.104669        0.006393   
392

In [10]:
results_df = results_df.sort_values(['rank_test_score'])
results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
395       0.001598      0.001957         0.053309        0.005755   
393       0.003196      0.001598         0.052815        0.003937   
391       0.004794      0.001599         0.104669        0.006393   
389       0.003219      0.001610         0.103854        0.005628   
387       0.003994      0.000026         0.106250        0.005412   
381       0.003993      0.000001         0.100661        0.004684   
383       0.003994      0.000003         0.104669        0.004653   
379       0.001609      0.001970         0.053889        0.011343   
195       0.004792      0.001598         0.160580        0.030662   
193       0.001598      0.001957         0.059919        0.005649   
385       0.003195      0.001598         0.104663        0.002966   
197       0.004793      0.001598         0.149402        0.022114   
189       0.003197      0.001599         0.056730        0.009924   
371       0.003212      0.001606         0.045516        0.001959   
191       0.001598      0.001957         0.063116        0.015033   
377       0.000798      0.001597         0.048737        0.002989   
187       0.001598      0.001957         0.058329        0.005966   
373       0.001599      0.001958         0.047936        0.002526   
185       0.003197      0.001598         0.067109        0.011687   
369       0.000798      0.001597         0.048731        0.003022   
183       0.002400      0.001959         0.064711        0.009250   
367       0.003197      0.001598         0.045539        0.004075   
181       0.003198      0.001599         0.075896        0.014063   
375       0.001598      0.001958         0.047935        0.002521   
365       0.003197      0.001598         0.046337        0.003196   
361       0.001598      0.001957         0.047134        0.003894   
179       0.003188      0.001594         0.058322        0.009316   
363       0.000000      0.000000         0.047928        0.003568   
392       0.003207      0.001604         0.059899        0.005035   
394       0.000801      0.001602         0.050331        0.001960   
..             ...           ...              ...             ...   
210       0.003986      0.000015         0.047153        0.005883   
211       0.003993      0.000001         0.045541        0.004073   
14        0.000800      0.001599         0.022370        0.003196   
15        0.002397      0.001957         0.020772        0.001602   
12        0.000799      0.001598         0.022368        0.001955   
13        0.000800      0.001599         0.020769        0.001600   
208       0.002404      0.001963         0.045538        0.003197   
209       0.002395      0.001956         0.045542        0.004780   
10        0.003197      0.001598         0.019174        0.002989   
11        0.000799      0.001599         0.021575        0.001956   
206       0.003994      0.000003         0.043942        0.004398   
207       0.003197      0.001598         0.043135        0.004651   
8         0.000799      0.001598         0.021585        0.005425   
9         0.000799      0.001597         0.019974        0.002527   
204       0.003889      0.000229         0.040059        0.003450   
205       0.003204      0.001602         0.042336        0.004072   
6         0.000800      0.001599         0.019174        0.001597   
7         0.002398      0.001958         0.017575        0.001958   
4         0.003197      0.001598         0.016777        0.002989   
202       0.003989      0.000017         0.039154        0.004667   
5         0.000000      0.000000         0.018375        0.003196   
203       0.003197      0.001598         0.040078        0.005682   
201       0.002404      0.001963         0.035950        0.004375   
200       0.002397      0.001957         0.035154        0.002991   
3         0.001598      0.001958         0.015179        0.001597   
2         0.001598      0.001958         0.016409        0.002669   
199