In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, StratifiedKFold, cross_val_score
from sklearn.svm import SVC

In [4]:
data = pd.read_csv('ISTrend_data.csv')
data

classes = data['Classification'] 
data = data.drop(['Company', 'Time', 'Classification'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")
    
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Classification', classes)
data


Total Revenues
Done
Operating Income
Done
Net Income
Done
Revenue Per Share
Done
Basic EPS
Done
Normalized Basic EPS
Done
Dividend Per Share
Done
EBITA
Done
EBIT
Done
Normalized Net Income
Done


Total Revenues  Operating Income  Net Income  Revenue Per Share  \
0           0.754239          0.212925    0.488938           0.037673   
1           0.553576          0.196357    0.481506           0.032382   
2           0.553525          0.196917    0.482404           0.035705   
3           0.559044          0.198095    0.461074           0.032107   
4           0.552203          0.195741    0.480458           0.032441   
5           0.552618          0.196912    0.481546           0.032132   
6           0.553636          0.197628    0.481859           0.032294   
7           0.556193          0.203943    0.485073           0.032287   
8           0.555855          0.200552    0.482149           0.032149   
9           0.551238          0.191023    0.476275           0.031885   
10          0.552919          0.199043    0.482195           0.032111   
11          0.552148          0.196423    0.481694           0.031807   
12          0.552079          0.194148    0.480168           0.031916   
13          0.552634          0.196523    0.480560           0.032145   
14          0.570996          0.207822    0.508958           0.032229   
15          0.550765          0.196198    0.480932           0.031867   
16          0.545343          0.193853    0.486352           0.031804   
17          0.550788          0.196256    0.480913           0.031914   
18          0.549969          0.196363    0.481993           0.031936   
19          0.553214          0.197654    0.481292           0.032272   
20          0.553130          0.186216    0.477191           0.031923   
21          0.551863          0.196761    0.480899           0.031949   
22          0.575284          0.211022    0.484908           0.032387   
23          0.449344          0.112803    0.446545           0.031531   
24          0.545745          0.186250    0.475440           0.031896   
25          0.559935          0.196843    0.479389           0.032856   
26          0.573917          0.214272    0.507107           0.031953   
27          0.550575          0.193752    0.481036           0.031857   
28          0.551881          0.198076    0.481261           0.031883   
29          0.597106          0.203966    0.484262           0.033195   
...              ...               ...         ...                ...   
4470        0.558879          0.199503    0.483628           0.032023   
4471        0.550823          0.196229    0.480866           0.031905   
4472        0.888419          0.200556    0.633948           0.032153   
4473        0.550541          0.196191    0.480890           0.031727   
4474        0.550452          0.195544    0.480784           0.032794   
4475        0.548689          0.196612    0.481086           0.031782   
4476        0.551099          0.196448    0.480975           0.031947   
4477        0.551437          0.195728    0.479632           0.031909   
4478        0.554954          0.196187    0.480360           0.032172   
4479        0.552267          0.198215    0.485950           0.032018   
4480        0.551587          0.195148    0.480622           0.031905   
4481        0.551498          0.196715    0.480523           0.031987   
4482        0.558281          0.196211    0.481041           0.032216   
4483        0.551040          0.196507    0.480963           0.031980   
4484        0.549187          0.195613    0.457076           0.031896   
4485        0.550746          0.195782    0.480808           0.032303   
4486        0.554053          0.196606    0.481012           0.032096   
4487        0.549554          0.196081    0.481036           0.031865   
4488        0.546751          0.196162    0.480714           0.031822   
4489        0.557576          0.199705    0.449903           0.031914   
4490        0.550306          0.196169    0.483860           0.031883   
4491        0.552071          0.196749    0.481180           0.032271   
4492        0.552379          0.197621    0.482040           0.0

In [5]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:10] # Parameters
y = NpMatrix[:,10] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.75423917 0.21292468 0.48893807 ... 0.21432902 0.21292468 0.24998533]
 [0.55357628 0.19635667 0.48150562 ... 0.19700335 0.19635667 0.23093844]
 [0.55352502 0.1969166  0.48240426 ... 0.1975557  0.1969166  0.23141158]
 ...
 [0.5658876  0.19423231 0.47595825 ... 0.19441591 0.19423231 0.23161008]
 [0.53574144 0.17061424 0.4720971  ... 0.17126114 0.17061424 0.2105595 ]
 [0.55532448 0.19673389 0.48112056 ... 0.19751528 0.19673389 0.23125428]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 10
Total Number of Training instances: 4500


[1. 1. 1. ... 1. 0. 1.]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 1.0
Total number of y values 4500


In [6]:
SVM = SVC(C=10000, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [7]:
# 7 minutes to run
CV = StratifiedKFold(n_splits=10, random_state=None, shuffle=False)

scores = cross_val_score(SVM, X, y, cv = CV) 

print(scores)

print("Mean Accuracy:", scores.mean())
print("SD of the mean:", scores.std())

[0.66962306 0.68736142 0.68444444 0.67777778 0.67555556 0.68222222
 0.67111111 0.68666667 0.67483296 0.69042316]
Mean MAE: 0.680001838143508
SD of the mean: 0.006856029814143587
