In [20]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.svm import SVC

In [21]:
data = pd.read_csv('BSTrend_data.csv')
data

classes = data['Classification'] 
data = data.drop(['Company', 'Time', 'Classification'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")
    
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Classification', classes)
data

Total Assets
Done
Total Liabilities
Done
Total Equity
Done
Total Shares Out. on Filing Date
Done
Book Value / Share
Done
Tangible Book Value
Done
Tangible Book Value Per Share
Done
Total Debt
Done
Net Debt
Done


Total Assets  Total Liabilities  Total Equity  \
0         0.574127           0.681912      0.526422   
1         0.561622           0.668232      0.523127   
2         0.558386           0.666852      0.518787   
3         0.551311           0.664790      0.507757   
4         0.569522           0.671660      0.533627   
5         0.571274           0.671457      0.537511   
6         0.555837           0.667440      0.512665   
7         0.558628           0.667559      0.518137   
8         0.558574           0.667400      0.518284   
9         0.557938           0.665650      0.519819   
10        0.558004           0.671629      0.510299   
11        0.572397           0.680970      0.524432   
12        0.559036           0.667879      0.518449   
13        0.555375           0.661583      0.521181   
14        0.560420           0.666820      0.522969   
15        0.561288           0.669583      0.520269   
16        0.563087           0.672025      0.519977   
17        0.554042           0.667695      0.508611   
18        0.565124           0.674290      0.520457   
19        0.562050           0.668810      0.523064   
20        0.560680           0.669631      0.518957   
21        0.558585           0.667434      0.518252   
22        0.581189           0.694308      0.520744   
23        0.558551           0.667484      0.518101   
24        0.559357           0.667596      0.519556   
25        0.565413           0.674194      0.521197   
26        0.559696           0.668181      0.519301   
27        0.558401           0.667237      0.518195   
28        0.574895           0.687129      0.519559   
29        0.569635           0.676381      0.526236   
...            ...                ...           ...   
4470      0.560549           0.669062      0.519609   
4471      0.557346           0.670303      0.511106   
4472      0.549209           0.663143      0.506149   
4473      0.561019           0.669013      0.520643   
4474      0.558076           0.666675      0.518445   
4475      0.563255           0.670576      0.522658   
4476      0.559924           0.668166      0.519787   
4477      0.562310           0.670488      0.520881   
4478      0.555322           0.662847      0.519033   
4479      0.560118           0.668406      0.519794   
4480      0.557514           0.665709      0.518862   
4481      0.566883           0.671758      0.528114   
4482      0.558492           0.667420      0.518085   
4483      0.559848           0.667683      0.520412   
4484      0.560337           0.671426      0.515362   
4485      0.564898           0.678603      0.513032   
4486      0.569428           0.697025      0.492487   
4487      0.558847           0.668490      0.517080   
4488      0.558525           0.667341      0.518278   
4489      0.539833           0.660775      0.490941   
4490      0.567701           0.676048      0.522848   
4491      0.569237           0.675437      0.526951   
4492      0.547089           0.652732      0.518653   
4493      0.568752           0.676176      0.524775   
4494      0.560424           0.668882      0.519649   
4495      0.558443           0.667495      0.517866   
4496      0.562484           0.670186      0.521721   
4497      0.558098           0.670463      0.512374   
4498      0.563987           0.674461      0.517870   
4499      0.562593           0.671990      0.519033   

      Total Shares Out. on Filing Date  Book Value / Share  \
0                             0.206908            0.001079   
1                             0.206132            0.001419   
2                             0.206226            0.001014   
3                             0.205851            0.000819   
4                             0.207023            0.001043   
5                             0.206320            0.001114   
6                             0.206222            0.000956   
7                             0.206260            0.001019   
8                             0.20629

In [22]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:9] # Parameters
y = NpMatrix[:,9] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.57412675 0.68191239 0.52642218 ... 0.15660121 0.66576035 0.59525398]
 [0.56162183 0.66823206 0.52312694 ... 0.15688709 0.65094776 0.60260052]
 [0.5583857  0.66685155 0.51878735 ... 0.15653233 0.64989047 0.60171398]
 ...
 [0.55809846 0.67046279 0.51237429 ... 0.15644957 0.65595174 0.608092  ]
 [0.56398688 0.67446145 0.51787038 ... 0.15653408 0.66283855 0.61190508]
 [0.56259345 0.67198972 0.51903259 ... 0.15619478 0.65718794 0.60745648]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 9
Total Number of Training instances: 4500


[1. 1. 1. ... 0. 0. 1.]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 1.0
Total number of y values 4500


In [23]:
# Takes 27 mins to run

# Using GridSearchCV to find best SVM hyperparameters
params = {'C': [0.1,1, 5, 10, 50, 100, 1000, 10000], # Slack parameter, how much error is allowed in prediction
          'gamma': ['scale', 'auto'], #[1,0.1,0.01,0.001], # Determines whether only close points determine hyperplane or those further away
          'kernel': ['linear', 'rbf', 'poly'],
         'degree': [1,2,3] } # Type of kernel used
 
cv_str = StratifiedKFold(n_splits=5)
SVM = SVC()

gs_modelSVM = GridSearchCV(SVM, params, cv= cv_str)
grid_results = gs_modelSVM.fit(X , y)

# Best parameters, best test score using these parameters, optimal KNN Configuration
print("Best Parameters", gs_modelSVM.best_params_)
print("Best score on Test Data", gs_modelSVM.best_score_)
print("Optimal Configuration", gs_modelSVM.best_estimator_)

Best Parameters {'C': 0.1, 'degree': 1, 'gamma': 'scale', 'kernel': 'linear'}
Best score on Test Data 0.6751111111111111
Optimal Configuration SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=1, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)


In [24]:
# Summarize the results in a readable format
print("Best: {0}, using {1}".format(grid_results.cv_results_['mean_test_score'], grid_results.best_params_))
results_df = pd.DataFrame(grid_results.cv_results_)
results_df

Best: [0.67511111 0.67511111 0.67511111 0.67511111 0.67511111 0.67511111
 0.67511111 0.67511111 0.67511111 0.67511111 0.67511111 0.67511111
 0.67511111 0.67511111 0.67488889 0.67511111 0.67511111 0.67511111
 0.67511111 0.67511111 0.67511111 0.67511111 0.67511111 0.67511111
 0.67511111 0.67511111 0.67488889 0.67511111 0.67511111 0.67511111
 0.67511111 0.67511111 0.67444444 0.67511111 0.67511111 0.67511111
 0.67511111 0.67488889 0.67511111 0.67511111 0.67511111 0.67511111
 0.67511111 0.67488889 0.67488889 0.67511111 0.67511111 0.67511111
 0.67511111 0.67488889 0.67422222 0.67511111 0.67511111 0.67511111
 0.67511111 0.67444444 0.67511111 0.67511111 0.67511111 0.67511111
 0.67511111 0.67444444 0.67444444 0.67511111 0.67511111 0.67511111
 0.67511111 0.67444444 0.67422222 0.67511111 0.67511111 0.67511111
 0.67511111 0.674      0.67511111 0.67511111 0.67488889 0.67511111
 0.67511111 0.674      0.67422222 0.67511111 0.67488889 0.67511111
 0.67511111 0.674      0.67355556 0.67511111 0.67488889 

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0         0.170073      0.028350         0.021734        0.001701     0.1   
1         0.298990      0.020860         0.048788        0.004145     0.1   
2         0.168143      0.004787         0.023743        0.000403     0.1   
3         0.149001      0.016711         0.019157        0.000395     0.1   
4         0.270790      0.017694         0.045082        0.006382     0.1   
5         0.188487      0.053864         0.025334        0.002554     0.1   
6         0.138431      0.001699         0.020552        0.002256     0.1   
7         0.281047      0.016451         0.045079        0.004027     0.1   
8         0.279049      0.016741         0.027136        0.000746     0.1   
9         0.151802      0.019087         0.019728        0.001593     0.1   
10        0.281225      0.022151         0.046491        0.004250     0.1   
11        0.170942      0.006471         0.026336        0.002340     0.1   
12        0.143996      0.010173         0.020359        0.002336     0.1   
13        0.279371      0.010106         0.047032        0.005644     0.1   
14        0.600179      0.115032         0.029140        0.005059     0.1   
15        0.144546      0.008114         0.021146        0.002376     0.1   
16        0.261255      0.010370         0.047066        0.006024     0.1   
17        0.193285      0.028927         0.027923        0.003779     0.1   
18        0.149012      0.010734         0.019138        0.000377       1   
19        0.354286      0.020830         0.047866        0.005854       1   
20        0.177520      0.014083         0.026143        0.003104       1   
21        0.159764      0.022217         0.020951        0.001884       1   
22        0.282653      0.013747         0.043467        0.003199       1   
23        0.173355      0.016636         0.024127        0.000965       1   
24        0.139810      0.006414         0.018963        0.000017       1   
25        0.372537      0.038505         0.051258        0.008437       1   
26        0.560448      0.113522         0.031331        0.005259       1   
27        0.145625      0.007387         0.020737        0.002399       1   
28        0.292659      0.024166         0.044880        0.004278       1   
29        0.179113      0.009838         0.026331        0.002329       1   
..             ...           ...              ...             ...     ...   
114       3.133332      0.723122         0.021333        0.001634    1000   
115       2.877811      0.613366         0.047081        0.004146    1000   
116       9.130074      1.119910         0.025548        0.000797    1000   
117       3.162710      0.688027         0.022341        0.001853    1000   
118       1.027268      0.103260         0.047062        0.003871    1000   
119       0.805057      0.144337         0.030628        0.004548    1000   
120       3.151861      0.709329         0.024926        0.002740    1000   
121       2.902636      0.570281         0.045481        0.002074    1000   
122      22.351327      1.643850         0.025530        0.000799    1000   
123       3.159711      0.703847         0.020945        0.001080    1000   
124       1.022707      0.107806         0.047665        0.003371    1000   
125       0.655942      0.128773         0.027534        0.002427    1000   
126       4.041066      0.188811         0.021548        0.001616   10000   
127       8.579595      1.425590         0.048470        0.006559   10000   
128       4.741399      0.259588         0.028525        0.004704   10000   
129       4.057650      0.218404         0.021942        0.002675   10000   
130       2.234676      0.192905         0.045787        0.003964   10000   
131       4.628318      1.416812         0.026529        0.001352   10000   
132       4.017963      0.194386         0.023925        0.004181   10000   
133       8.506055      1.475815         0.045469        0.005433   10000   
1

In [25]:
results_df = results_df.sort_values(['rank_test_score'])
results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0         0.170073      0.028350         0.021734        0.001701     0.1   
69        0.172936      0.030921         0.023088        0.002508      10   
66        0.158572      0.023267         0.022537        0.003189      10   
65        0.229180      0.021224         0.031932        0.003622      10   
64        0.349309      0.016575         0.045272        0.002712      10   
63        0.161552      0.018588         0.021557        0.002334      10   
60        0.160398      0.027262         0.020136        0.001601      10   
59        0.196274      0.021084         0.029516        0.004575      10   
58        0.369800      0.040767         0.050483        0.007063      10   
57        0.160378      0.023442         0.020937        0.001421      10   
56        0.186708      0.028796         0.026714        0.006085      10   
54        0.163970      0.022068         0.020745        0.001843      10   
53        0.179735      0.011009         0.026513        0.002227       5   
52        0.330537      0.026022         0.045853        0.002443       5   
51        0.159008      0.018597         0.021938        0.002519       5   
48        0.169747      0.021201         0.021789        0.002377       5   
47        0.191548      0.013224         0.026735        0.002235       5   
46        0.317535      0.022987         0.052467        0.007813       5   
70        0.347534      0.017599         0.050878        0.003166      10   
45        0.160183      0.029465         0.020536        0.001611       5   
72        0.246136      0.104220         0.021541        0.002052      50   
75        0.310288      0.204782         0.023757        0.006269      50   
113       1.265455      0.375422         0.026736        0.004624    1000   
107       0.297004      0.023630         0.026523        0.001341     100   
105       1.324695      0.318602         0.021942        0.004617     100   
102       1.320947      0.309642         0.022934        0.003717     100   
101       0.366462      0.058097         0.029713        0.004330     100   
99        1.325004      0.307759         0.021734        0.003056     100   
96        1.336466      0.324179         0.022373        0.002531     100   
95        0.190542      0.024135         0.027723        0.002117     100   
..             ...           ...              ...             ...     ...   
67        0.601305      0.056817         0.049261        0.006319      10   
55        0.611989      0.067399         0.047878        0.002442      10   
110       3.707932      0.631763         0.029521        0.007543    1000   
62        1.446684      0.176366         0.031510        0.003910      10   
134      16.114317      1.777477         0.027939        0.002975   10000   
137       2.486145      0.428815         0.026345        0.002302   10000   
142       2.210113      0.194416         0.049860        0.005386   10000   
130       2.234676      0.192905         0.045787        0.003964   10000   
68        5.326139      0.770079         0.032910        0.008624      10   
98        4.705148      0.707585         0.026535        0.001191     100   
136       2.221712      0.183424         0.045863        0.006036   10000   
80        3.773203      0.863163         0.026141        0.001476      50   
50        4.122767      0.529860         0.027142        0.002910       5   
79        0.876721      0.071191         0.056066        0.010155      50   
97        1.086560      0.074704         0.046978        0.005185     100   
121       2.902636      0.570281         0.045481        0.002074    1000   
103       1.091001      0.079495         0.049265        0.007237     100   
115       2.877811      0.613366         0.047081        0.004146    1000   
73        0.846327      0.050494         0.047684        0.004996      50   
85        0.851467      0.090035         0.045702        0.002787      50   
9