In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, make_scorer, mean_absolute_error
from sklearn.model_selection import GridSearchCV

In [54]:
#data = pd.read_csv('BS_train_data.csv')
#data

In [2]:
data = pd.read_csv('DeltaCF_data.csv')
data

Company        Time  Net Income  Cash from Operations  \
0         PM  2012-12-01       209.0               -1108.0   
1        HES  2011-12-01      -422.0                 454.0   
2       SIRI  2019-12-01      -262.0                 137.0   
3       SPGI  2013-12-01       939.0                -728.0   
4       MKTX  2015-12-01        21.2                  14.5   
5        GTN  2016-12-01        23.0                 103.4   
6          V  2013-09-01      2836.0               -1987.0   
7        BTI  2011-12-01       322.2                  96.5   
8       VALE  2015-12-01    -11520.1               -6487.9   
9        INT  2015-12-01       -50.0                 306.4   
10       SKM  2016-12-01        98.2                 305.2   
11       FNF  2013-12-01      -213.0                -136.0   
12       VFC  2017-12-01      -459.2                  -5.9   
13       CCL  2012-11-01      -614.0                -767.0   
14       KSU  2015-12-01       -19.1                   3.2   
15       AFL  2015-12-01      -418.0                 226.0   
16        WM  2016-12-01       429.0                 475.0   
17      ORCL  2019-05-01      7496.0                -835.0   
18       WBA  2013-08-01       421.0                -130.0   
19       AWK  2013-12-01        10.9                 -59.6   
20      WLTW  2013-12-01       811.0                  36.0   
21       KSU  2012-12-01        47.0                  35.2   
22       RTX  2011-12-01       606.0                 684.0   
23      DISH  2018-12-01      -523.6                -261.7   
24       SJI  2015-12-01         8.1                  25.4   
25       CCL  2019-11-01      -162.0                 -74.0   
26       SLB  2014-12-01     -1294.0                 531.0   
27       GPS  2012-01-01      -371.0                -381.0   
28       AMD  2018-12-01       370.0                  22.0   
29       DHR  2015-12-01       759.0                  43.4   
...      ...         ...         ...                   ...   
4470    HOLX  2011-09-01       220.0                  -0.7   
4471    MKTX  2019-12-01        32.0                  42.0   
4472      TT  2015-12-01      -267.1                 -84.8   
4473     ITW  2015-12-01     -1047.0                 683.0   
4474     LOW  2017-02-01       547.0                 833.0   
4475     LKQ  2019-12-01        61.2                 353.3   
4476     GLW  2011-12-01      -741.0                -646.0   
4477     EIG  2017-12-01        -5.5                  19.5   
4478     STX  2018-06-01       410.0                 197.0   
4479    NDAQ  2014-12-01        29.0                  58.0   
4480     EIG  2011-12-01       -14.9                 -14.6   
4481     VFF  2016-12-01        -4.1                   1.3   
4482    FFIV  2012-09-01        33.8                  78.5   
4483     AWK  2016-12-01        -8.0                  94.0   
4484    CCOI  2019-12-01         8.8                  14.9   
4485     EQT  2019-12-01      1022.9               -1124.6   
4486    LDOS  2013-01-01       466.0                -370.0   
4487     FCX  2013-12-01      -383.0                2365.0   
4488     FDP  2013-12-01      -177.6                 -63.9   
4489     TSN  2013-09-01       195.0                 127.0   
4490     DHI  2014-09-01        70.8                 567.9   
4491     TAP  2016-12-01      1198.7                 411.0   
4492     CTL  2012-12-01       204.0                1864.0   
4493    PAAS  2018-12-01      -110.7                 -69.6   
4494     BIP  2019-12-01      -140.0                 781.0   
4495     CNK  2013-12-01       -20.4                 -85.5   
4496     UNH  2011-12-01       508.0                 695.0   
4497    IDXX  2017-12-01        41.1                  34.4   
4498     WRB  2018-12-01        91.6                 -90.7   
4499     AVY  2016-01-01        29.2                 118.8   

      Cash from Investing  Cash from Financing  Net Change in Cash  \
0                    40.0                238.0              -414.0   
1                 -1

In [3]:
prices = data['Price_Change'] 
data = data.drop(['Company', 'Time', 'Price_Change'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")

Net Income
Done
Cash from Operations
Done
Cash from Investing
Done
Cash from Financing
Done
Net Change in Cash
Done
Levered Free Cash Flow
Done
Unlevered Free Cash Flow
Done
Free Cash Flow / Share
Done


In [4]:
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Price_Change', prices)
data

Net Income  Cash from Operations  Cash from Investing  \
0       0.482030              0.437469             0.504055   
1       0.478693              0.476244             0.493695   
2       0.479539              0.468375             0.506639   
3       0.485891              0.446902             0.522545   
4       0.481037              0.465334             0.503555   
5       0.481047              0.467540             0.501649   
6       0.495925              0.415649             0.513362   
7       0.482629              0.467369             0.500640   
8       0.419992              0.303920             0.529392   
9       0.480660              0.472580             0.504919   
10      0.481444              0.472550             0.506883   
11      0.479798              0.461598             0.505670   
12      0.478496              0.464827             0.498641   
13      0.477677              0.445934             0.510470   
14      0.480824              0.465053             0.504593   
15      0.478714              0.470584             0.498702   
16      0.483194              0.476765             0.501279   
17      0.520573              0.444246             0.751266   
18      0.483152              0.461747             0.533466   
19      0.480983              0.463494             0.498590   
20      0.485214              0.465867             0.504147   
21      0.481173              0.465847             0.503428   
22      0.484130              0.481953             0.522822   
23      0.478155              0.458477             0.538714   
24      0.480968              0.465604             0.503653   
25      0.480068              0.463137             0.490188   
26      0.474081              0.478155             0.513954   
27      0.478963              0.455516             0.503555   
28      0.482882              0.465520             0.502855   
29      0.484939              0.466051             0.415247   
...          ...                   ...                  ...   
4470    0.482088              0.464956             0.502212   
4471    0.481094              0.466016             0.503195   
4472    0.479512              0.462869             0.496088   
4473    0.475387              0.481928             0.480274   
4474    0.483818              0.485652             0.488227   
4475    0.481249              0.473744             0.512931   
4476    0.477006              0.448938             0.501540   
4477    0.480896              0.465458             0.503553   
4478    0.483093              0.469864             0.495064   
4479    0.481078              0.466413             0.511908   
4480    0.480846              0.464611             0.505680   
4481    0.480903              0.465006             0.503747   
4482    0.481104              0.466922             0.502112   
4483    0.480883              0.467307             0.502740   
4484    0.480971              0.465344             0.503770   
4485    0.486335              0.437057             0.522037   
4486    0.483390              0.455789             0.500402   
4487    0.478899              0.523682             0.446486   
4488    0.479985              0.463387             0.503059   
4489    0.481956              0.468126             0.503878   
4490    0.481299              0.479071             0.500187   
4491    0.487265              0.475176             0.411823   
4492    0.482004              0.511245             0.511108   
4493    0.480339              0.463246             0.503891   
4494    0.480184              0.484361             0.459077   
4495    0.480817              0.462851             0.502745   
4496    0.483612              0.482226             0.512723   
4497    0.481142              0.465828             0.503379   
4498    0.481409              0.462722             0.500819   
4499    0.481079              0.467923             0.503959   

      Cash from Financing  Net Change in Cash  Levered Free Cash Flow  \
0                0.540513 

In [5]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:8] # Parameters
y = NpMatrix[:,8] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.48203031 0.43746897 0.50405519 ... 0.53258539 0.53757125 0.43768056]
 [0.47869279 0.47624367 0.49369513 ... 0.53047059 0.53537496 0.43753007]
 [0.47953907 0.46837454 0.50663944 ... 0.54162278 0.54645877 0.43771673]
 ...
 [0.48114224 0.46582762 0.50337913 ... 0.5401717  0.54495221 0.43773546]
 [0.48140935 0.46272217 0.5008195  ... 0.53972743 0.54452586 0.43770317]
 [0.4810793  0.46792275 0.50395905 ... 0.54119171 0.54594025 0.43781943]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 8
Total Number of Training instances: 4500


[  5.16 -19.74   1.44 ...  39.11   2.39   8.62]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 5.16
Total number of y values 4500


In [59]:
#X_train, X_test, y_train, y_test = train_test_split(X , y, test_size = 0.2, random_state = 42) # 42, 56, 66, 87

In [6]:
# Hyperparameter Grid Search
#criterion = {'mse', 'friedman_mse', 'mae'}
#'criterion' : ['mse', 'mae'],
#  'criterion' : {'mse', 'friedman_mse', 'mae'}
params = {
        'splitter' : ['best', 'random'],
          'max_depth': range(1,50), 
         }

decision_tree = DecisionTreeRegressor()
#mse = make_scorer(mean_squared_error, greater_is_better= False)
mae = make_scorer(mean_absolute_error, greater_is_better= False)

#gs_decision_tree = GridSearchCV(decision_tree, params, scoring = mae,  cv=10)
gs_decision_tree = GridSearchCV(decision_tree, params, scoring = mae,  cv=5)

grid_results = gs_decision_tree.fit(X , y)

# Best parameters, best test score using these parameters, optimal KNN Configuration
print("Best Parameters", gs_decision_tree.best_params_)
print("Best score on Test Data", gs_decision_tree.best_score_)
print("Optimal Configuration", gs_decision_tree.best_estimator_)

Best Parameters {'max_depth': 1, 'splitter': 'random'}
Best score on Test Data -16.419168743172737
Optimal Configuration DecisionTreeRegressor(criterion='mse', max_depth=1, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='random')


In [7]:
# Summarize the results in a readable format
print("Best: {0}, using {1}".format(grid_results.cv_results_['mean_test_score'], grid_results.best_params_))
results_df = pd.DataFrame(grid_results.cv_results_)
results_df

Best: [-16.73894318 -16.41916874 -17.10106146 -16.4329986  -17.86265588
 -16.50712464 -17.8671534  -16.45820444 -17.63809803 -16.49413461
 -18.45920487 -16.47016508 -18.1586351  -17.23619734 -18.43330487
 -17.12806573 -18.60524314 -17.41138129 -19.09774597 -17.20027356
 -19.38463531 -18.24117363 -19.93558104 -17.57750534 -20.39946058
 -17.09295925 -21.58417448 -17.55580982 -22.18748307 -18.27145024
 -21.82128948 -18.64591864 -22.88878263 -19.30900594 -23.4392216
 -18.34637776 -24.27062249 -18.96819069 -23.78972011 -18.9770698
 -24.1462483  -19.13472114 -24.29613482 -22.081139   -24.00440252
 -20.26613177 -24.56071043 -21.512907   -25.16722904 -22.31306695
 -24.41361166 -22.71525678 -25.25676803 -22.63099248 -25.07347179
 -23.0752046  -24.75996632 -23.19932083 -24.74379344 -24.15054658
 -24.94282805 -21.37721129 -24.56390444 -22.58753653 -25.21623109
 -23.41121551 -25.44953687 -25.30348396 -24.76588322 -24.45228033
 -25.7005011  -24.3463129  -25.6229917  -24.26402555 -25.41437619
 -25.0

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.004586  2.720177e-03         0.000601        0.000491   
1        0.000996  3.968362e-06         0.000202        0.000403   
2        0.005775  3.932649e-04         0.000408        0.000499   
3        0.000798  3.990174e-04         0.000000        0.000000   
4        0.007380  4.882088e-04         0.000598        0.000489   
5        0.000798  3.989938e-04         0.000200        0.000399   
6        0.009382  4.822601e-04         0.000400        0.000490   
7        0.000806  4.030339e-04         0.000392        0.000480   
8        0.011960  1.520610e-05         0.000399        0.000489   
9        0.000798  3.990893e-04         0.000407        0.000498   
10       0.015556  1.017170e-03         0.000192        0.000384   
11       0.001602  4.958269e-04         0.000192        0.000384   
12       0.015956  6.430563e-04         0.000399        0.000489   
13       0.001197  3.985416e-04         0.000407        0.000499   
14       0.018344  1.339276e-03         0.000199        0.000397   
15       0.001192  3.896237e-04         0.000798        0.000399   
16       0.019538  4.814803e-04         0.001019        0.000029   
17       0.001994  4.537225e-06         0.000000        0.000000   
18       0.021538  5.089068e-04         0.000798        0.000399   
19       0.001803  4.042276e-04         0.000391        0.000479   
20       0.023544  1.017985e-03         0.000594        0.000485   
21       0.001786  3.929095e-04         0.000407        0.000498   
22       0.025725  7.328386e-04         0.000000        0.000000   
23       0.002194  3.985883e-04         0.000200        0.000399   
24       0.027327  1.202878e-03         0.000605        0.000494   
25       0.002599  4.961913e-04         0.000393        0.000482   
26       0.029122  1.177494e-03         0.000399        0.000488   
27       0.003374  4.867879e-04         0.000408        0.000500   
28       0.032924  2.097516e-03         0.000598        0.000488   
29       0.002385  4.794112e-04         0.000607        0.000496   
..            ...           ...              ...             ...   
68       0.042884  3.294224e-03         0.000599        0.000489   
69       0.007979  6.315149e-04         0.000598        0.000489   
70       0.043283  3.929414e-03         0.000798        0.000399   
71       0.008577  4.889509e-04         0.000399        0.000488   
72       0.046276  7.167215e-03         0.000790        0.000395   
73       0.008584  4.948968e-04         0.000399        0.000489   
74       0.042884  3.349692e-03         0.000399        0.000489   
75       0.008562  4.766941e-04         0.000606        0.000495   
76       0.043483  3.763005e-03         0.000199        0.000399   
77       0.008975  2.336015e-07         0.000200        0.000399   
78       0.044482  5.511345e-03         0.000796        0.000398   
79       0.008784  4.029098e-04         0.000399        0.000489   
80       0.045470  5.512165e-03         0.000598        0.000488   
81       0.009175  3.995661e-04         0.000399        0.000489   
82       0.042893  3.268997e-03         0.000399        0.000488   
83       0.008966  1.714135e-05         0.000600        0.000490   
84       0.044682  5.319478e-03         0.000399        0.000489   
85       0.010769  1.165168e-03         0.000999        0.000002   
86       0.046673  2.702583e-03         0.000402        0.000493   
87       0.009770  7.418957e-04         0.000399        0.000489   
88       0.048202  5.152591e-03         0.000417        0.000474   
89       0.009363  4.605241e-04         0.000199        0.000398   
90       0.043078  3.062205e-03         0.000399        0.000489   
91       0.009574  4.884432e-04         0.000199        0.000397   
92       0.044075  4.124677e-03         0.000407        0.000498   
93       0.009168  4.029776e-04         0.000599        0.000489   
94       0.043292  2.852675e-03         0.000598        0.00

In [8]:
results_df = results_df.sort_values(['rank_test_score'])
results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
1        0.000996      0.000004         0.000202        0.000403   
3        0.000798      0.000399         0.000000        0.000000   
7        0.000806      0.000403         0.000392        0.000480   
11       0.001602      0.000496         0.000192        0.000384   
9        0.000798      0.000399         0.000407        0.000498   
5        0.000798      0.000399         0.000200        0.000399   
0        0.004586      0.002720         0.000601        0.000491   
25       0.002599      0.000496         0.000393        0.000482   
2        0.005775      0.000393         0.000408        0.000499   
15       0.001192      0.000390         0.000798        0.000399   
19       0.001803      0.000404         0.000391        0.000479   
13       0.001197      0.000399         0.000407        0.000499   
17       0.001994      0.000005         0.000000        0.000000   
27       0.003374      0.000487         0.000408        0.000500   
23       0.002194      0.000399         0.000200        0.000399   
8        0.011960      0.000015         0.000399        0.000489   
4        0.007380      0.000488         0.000598        0.000489   
6        0.009382      0.000482         0.000400        0.000490   
12       0.015956      0.000643         0.000399        0.000489   
21       0.001786      0.000393         0.000407        0.000498   
29       0.002385      0.000479         0.000607        0.000496   
35       0.003590      0.000489         0.000599        0.000489   
14       0.018344      0.001339         0.000199        0.000397   
10       0.015556      0.001017         0.000192        0.000384   
16       0.019538      0.000481         0.001019        0.000029   
31       0.003192      0.000401         0.000201        0.000403   
37       0.003783      0.000737         0.000399        0.000489   
39       0.004373      0.000468         0.000406        0.000498   
18       0.021538      0.000509         0.000798        0.000399   
41       0.004388      0.000490         0.000200        0.000400   
..            ...           ...              ...             ...   
93       0.009168      0.000403         0.000599        0.000489   
58       0.042087      0.003047         0.000399        0.000489   
97       0.008982      0.000015         0.000399        0.000489   
56       0.044481      0.003198         0.000798        0.000399   
82       0.042893      0.003269         0.000399        0.000488   
68       0.042884      0.003294         0.000599        0.000489   
88       0.048202      0.005153         0.000417        0.000474   
87       0.009770      0.000742         0.000399        0.000489   
86       0.046673      0.002703         0.000402        0.000493   
60       0.042080      0.003062         0.000798        0.000399   
76       0.043483      0.003763         0.000199        0.000399   
78       0.044482      0.005511         0.000796        0.000398   
54       0.041889      0.003351         0.000797        0.000398   
75       0.008562      0.000477         0.000606        0.000495   
48       0.045478      0.003358         0.000400        0.000490   
81       0.009175      0.000400         0.000399        0.000489   
64       0.044271      0.003721         0.000611        0.000499   
52       0.041488      0.003011         0.000799        0.000399   
80       0.045470      0.005512         0.000598        0.000488   
96       0.045078      0.005454         0.000401        0.000491   
67       0.008579      0.000799         0.000200        0.000399   
83       0.008966      0.000017         0.000600        0.000490   
84       0.044682      0.005319         0.000399        0.000489   
90       0.043078      0.003062         0.000399        0.000489   
74       0.042884      0.003350         0.000399        0.000489   
66       0.042670      0.003200         0.000604        0.000493   
92       0.044075      0.004125         0.000407        0.00