In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsRegressor 
from sklearn.metrics import mean_squared_error, make_scorer, mean_absolute_error
from sklearn.model_selection import GridSearchCV

In [2]:
data = pd.read_csv('DeltaCF_data.csv')
data

Company        Time  Net Income  Cash from Operations  \
0         PM  2012-12-01       209.0               -1108.0   
1        HES  2011-12-01      -422.0                 454.0   
2       SIRI  2019-12-01      -262.0                 137.0   
3       SPGI  2013-12-01       939.0                -728.0   
4       MKTX  2015-12-01        21.2                  14.5   
5        GTN  2016-12-01        23.0                 103.4   
6          V  2013-09-01      2836.0               -1987.0   
7        BTI  2011-12-01       322.2                  96.5   
8       VALE  2015-12-01    -11520.1               -6487.9   
9        INT  2015-12-01       -50.0                 306.4   
10       SKM  2016-12-01        98.2                 305.2   
11       FNF  2013-12-01      -213.0                -136.0   
12       VFC  2017-12-01      -459.2                  -5.9   
13       CCL  2012-11-01      -614.0                -767.0   
14       KSU  2015-12-01       -19.1                   3.2   
15       AFL  2015-12-01      -418.0                 226.0   
16        WM  2016-12-01       429.0                 475.0   
17      ORCL  2019-05-01      7496.0                -835.0   
18       WBA  2013-08-01       421.0                -130.0   
19       AWK  2013-12-01        10.9                 -59.6   
20      WLTW  2013-12-01       811.0                  36.0   
21       KSU  2012-12-01        47.0                  35.2   
22       RTX  2011-12-01       606.0                 684.0   
23      DISH  2018-12-01      -523.6                -261.7   
24       SJI  2015-12-01         8.1                  25.4   
25       CCL  2019-11-01      -162.0                 -74.0   
26       SLB  2014-12-01     -1294.0                 531.0   
27       GPS  2012-01-01      -371.0                -381.0   
28       AMD  2018-12-01       370.0                  22.0   
29       DHR  2015-12-01       759.0                  43.4   
...      ...         ...         ...                   ...   
4470    HOLX  2011-09-01       220.0                  -0.7   
4471    MKTX  2019-12-01        32.0                  42.0   
4472      TT  2015-12-01      -267.1                 -84.8   
4473     ITW  2015-12-01     -1047.0                 683.0   
4474     LOW  2017-02-01       547.0                 833.0   
4475     LKQ  2019-12-01        61.2                 353.3   
4476     GLW  2011-12-01      -741.0                -646.0   
4477     EIG  2017-12-01        -5.5                  19.5   
4478     STX  2018-06-01       410.0                 197.0   
4479    NDAQ  2014-12-01        29.0                  58.0   
4480     EIG  2011-12-01       -14.9                 -14.6   
4481     VFF  2016-12-01        -4.1                   1.3   
4482    FFIV  2012-09-01        33.8                  78.5   
4483     AWK  2016-12-01        -8.0                  94.0   
4484    CCOI  2019-12-01         8.8                  14.9   
4485     EQT  2019-12-01      1022.9               -1124.6   
4486    LDOS  2013-01-01       466.0                -370.0   
4487     FCX  2013-12-01      -383.0                2365.0   
4488     FDP  2013-12-01      -177.6                 -63.9   
4489     TSN  2013-09-01       195.0                 127.0   
4490     DHI  2014-09-01        70.8                 567.9   
4491     TAP  2016-12-01      1198.7                 411.0   
4492     CTL  2012-12-01       204.0                1864.0   
4493    PAAS  2018-12-01      -110.7                 -69.6   
4494     BIP  2019-12-01      -140.0                 781.0   
4495     CNK  2013-12-01       -20.4                 -85.5   
4496     UNH  2011-12-01       508.0                 695.0   
4497    IDXX  2017-12-01        41.1                  34.4   
4498     WRB  2018-12-01        91.6                 -90.7   
4499     AVY  2016-01-01        29.2                 118.8   

      Cash from Investing  Cash from Financing  Net Change in Cash  \
0                    40.0                238.0              -414.0   
1                 -1

In [3]:
prices = data['Price_Change'] 
data = data.drop(['Company', 'Time', 'Price_Change'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")

Net Income
Done
Cash from Operations
Done
Cash from Investing
Done
Cash from Financing
Done
Net Change in Cash
Done
Levered Free Cash Flow
Done
Unlevered Free Cash Flow
Done
Free Cash Flow / Share
Done


In [4]:
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Price_Change', prices)
data

Net Income  Cash from Operations  Cash from Investing  \
0       0.482030              0.437469             0.504055   
1       0.478693              0.476244             0.493695   
2       0.479539              0.468375             0.506639   
3       0.485891              0.446902             0.522545   
4       0.481037              0.465334             0.503555   
5       0.481047              0.467540             0.501649   
6       0.495925              0.415649             0.513362   
7       0.482629              0.467369             0.500640   
8       0.419992              0.303920             0.529392   
9       0.480660              0.472580             0.504919   
10      0.481444              0.472550             0.506883   
11      0.479798              0.461598             0.505670   
12      0.478496              0.464827             0.498641   
13      0.477677              0.445934             0.510470   
14      0.480824              0.465053             0.504593   
15      0.478714              0.470584             0.498702   
16      0.483194              0.476765             0.501279   
17      0.520573              0.444246             0.751266   
18      0.483152              0.461747             0.533466   
19      0.480983              0.463494             0.498590   
20      0.485214              0.465867             0.504147   
21      0.481173              0.465847             0.503428   
22      0.484130              0.481953             0.522822   
23      0.478155              0.458477             0.538714   
24      0.480968              0.465604             0.503653   
25      0.480068              0.463137             0.490188   
26      0.474081              0.478155             0.513954   
27      0.478963              0.455516             0.503555   
28      0.482882              0.465520             0.502855   
29      0.484939              0.466051             0.415247   
...          ...                   ...                  ...   
4470    0.482088              0.464956             0.502212   
4471    0.481094              0.466016             0.503195   
4472    0.479512              0.462869             0.496088   
4473    0.475387              0.481928             0.480274   
4474    0.483818              0.485652             0.488227   
4475    0.481249              0.473744             0.512931   
4476    0.477006              0.448938             0.501540   
4477    0.480896              0.465458             0.503553   
4478    0.483093              0.469864             0.495064   
4479    0.481078              0.466413             0.511908   
4480    0.480846              0.464611             0.505680   
4481    0.480903              0.465006             0.503747   
4482    0.481104              0.466922             0.502112   
4483    0.480883              0.467307             0.502740   
4484    0.480971              0.465344             0.503770   
4485    0.486335              0.437057             0.522037   
4486    0.483390              0.455789             0.500402   
4487    0.478899              0.523682             0.446486   
4488    0.479985              0.463387             0.503059   
4489    0.481956              0.468126             0.503878   
4490    0.481299              0.479071             0.500187   
4491    0.487265              0.475176             0.411823   
4492    0.482004              0.511245             0.511108   
4493    0.480339              0.463246             0.503891   
4494    0.480184              0.484361             0.459077   
4495    0.480817              0.462851             0.502745   
4496    0.483612              0.482226             0.512723   
4497    0.481142              0.465828             0.503379   
4498    0.481409              0.462722             0.500819   
4499    0.481079              0.467923             0.503959   

      Cash from Financing  Net Change in Cash  Levered Free Cash Flow  \
0                0.540513 

In [5]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:8] # Parameters
y = NpMatrix[:,8] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.48203031 0.43746897 0.50405519 ... 0.53258539 0.53757125 0.43768056]
 [0.47869279 0.47624367 0.49369513 ... 0.53047059 0.53537496 0.43753007]
 [0.47953907 0.46837454 0.50663944 ... 0.54162278 0.54645877 0.43771673]
 ...
 [0.48114224 0.46582762 0.50337913 ... 0.5401717  0.54495221 0.43773546]
 [0.48140935 0.46272217 0.5008195  ... 0.53972743 0.54452586 0.43770317]
 [0.4810793  0.46792275 0.50395905 ... 0.54119171 0.54594025 0.43781943]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 8
Total Number of Training instances: 4500


[  5.16 -19.74   1.44 ...  39.11   2.39   8.62]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 5.16
Total number of y values 4500


In [6]:
# Grid Search for Optimal KNN Hyperparameters
# Using GridSearchCV to find best parameters
kvals = range(1,100)
params = {'n_neighbors': kvals,
        'weights' : ['uniform', 'distance'],
         'metric' : ['euclidean', 'manhattan']}

knn = KNeighborsRegressor()
#mse = make_scorer(mean_squared_error, greater_is_better= False)
mae = make_scorer(mean_absolute_error, greater_is_better= False)

gs_modelKNN = GridSearchCV(knn, params, scoring = mae,  cv=5)
grid_results = gs_modelKNN.fit(X , y)

# Best parameters, best test score using these parameters, optimal KNN Configuration
print("Best Parameters", gs_modelKNN.best_params_)
print("Best score on Test Data", gs_modelKNN.best_score_)
print("Optimal Configuration", gs_modelKNN.best_estimator_)

Best Parameters {'metric': 'manhattan', 'n_neighbors': 99, 'weights': 'distance'}
Best score on Test Data -16.217851709330578
Optimal Configuration KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='manhattan',
                    metric_params=None, n_jobs=None, n_neighbors=99, p=2,
                    weights='distance')


In [7]:
# Summarize the results in a readable format
print("Best: {0}, using {1}".format(grid_results.cv_results_['mean_test_score'], grid_results.best_params_))
results_df = pd.DataFrame(grid_results.cv_results_)
results_df

Best: [-22.37959556 -22.37959556 -20.53248889 -20.4357852  -19.7337237
 -19.6164808  -19.15994722 -19.07207715 -18.71399556 -18.66173649
 -18.34528259 -18.30313913 -18.2372546  -18.17732023 -17.95117639
 -17.91619329 -17.81623531 -17.7763719  -17.68647178 -17.65061885
 -17.56717394 -17.53721041 -17.46850444 -17.4370588  -17.35125812
 -17.32644855 -17.23445968 -17.21636133 -17.16567733 -17.15013939
 -17.07692444 -17.06524054 -17.01375216 -17.00248978 -16.96053901
 -16.95475153 -16.88026386 -16.88187156 -16.85437033 -16.8466862
 -16.82484169 -16.82481465 -16.79853778 -16.79790495 -16.77883285
 -16.77245374 -16.75709861 -16.74881731 -16.73587084 -16.72932199
 -16.73031427 -16.72450275 -16.74442477 -16.73118121 -16.74910524
 -16.73420545 -16.74472674 -16.72663326 -16.72942185 -16.70835251
 -16.73742674 -16.70847046 -16.71005625 -16.68300058 -16.67638027
 -16.65871277 -16.64945399 -16.63687658 -16.62099137 -16.60805418
 -16.63297827 -16.61387908 -16.62273772 -16.59937019 -16.61521503
 -16.5

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0         0.002395  2.328640e-03         0.014953        0.004426   
1         0.001593  4.886993e-04         0.012576        0.001362   
2         0.001198  3.990423e-04         0.014759        0.001318   
3         0.001596  4.875485e-04         0.014562        0.001493   
4         0.001595  4.891426e-04         0.015958        0.001093   
5         0.001403  4.979377e-04         0.016348        0.001727   
6         0.001794  3.986656e-04         0.017147        0.001151   
7         0.001596  4.882475e-04         0.021550        0.004118   
8         0.001394  4.891078e-04         0.018153        0.001936   
9         0.001776  3.898910e-04         0.019970        0.002974   
10        0.001664  4.193915e-04         0.018959        0.001904   
11        0.001604  4.939331e-04         0.019141        0.001931   
12        0.001212  4.107952e-04         0.019933        0.001892   
13        0.001596  4.879743e-04         0.019747        0.001596   
14        0.001595  4.884625e-04         0.020733        0.001609   
15        0.001204  4.146101e-04         0.020546        0.001851   
16        0.001597  4.870443e-04         0.022922        0.003775   
17        0.001394  4.865939e-04         0.023937        0.003217   
18        0.001989  1.071171e-03         0.030762        0.017753   
19        0.001397  4.883054e-04         0.021749        0.001319   
20        0.001995  2.591644e-06         0.022140        0.001933   
21        0.001589  4.828528e-04         0.022350        0.001655   
22        0.001594  4.885718e-04         0.022733        0.001603   
23        0.001995  5.223489e-07         0.022647        0.001660   
24        0.001197  3.989018e-04         0.023736        0.001595   
25        0.001594  7.959605e-04         0.028526        0.003477   
26        0.001587  4.677592e-04         0.023929        0.001910   
27        0.001795  3.981609e-04         0.023737        0.001591   
28        0.002002  1.450291e-05         0.023936        0.001893   
29        0.001995  3.612651e-06         0.024328        0.001736   
..             ...           ...              ...             ...   
366       0.001788  7.451676e-04         0.047673        0.001596   
367       0.002010  6.198185e-04         0.049852        0.002002   
368       0.001423  4.813584e-04         0.050876        0.005212   
369       0.002182  4.011824e-04         0.052872        0.002441   
370       0.001810  3.871653e-04         0.050650        0.002220   
371       0.001313  4.078740e-04         0.052755        0.006157   
372       0.001621  7.872606e-04         0.052754        0.003767   
373       0.002407  1.000672e-03         0.066216        0.009266   
374       0.001806  4.031012e-04         0.057835        0.001408   
375       0.002193  3.988984e-04         0.055651        0.005503   
376       0.002017  2.726033e-05         0.051662        0.001916   
377       0.001625  4.769084e-04         0.053030        0.007048   
378       0.001210  3.909666e-04         0.050859        0.001886   
379       0.001609  4.710770e-04         0.054647        0.004781   
380       0.001812  3.896701e-04         0.050075        0.001740   
381       0.001780  4.098079e-04         0.052076        0.005018   
382       0.001615  4.755372e-04         0.054043        0.006600   
383       0.002001  1.492843e-05         0.051256        0.001605   
384       0.002023  4.245388e-05         0.049460        0.001500   
385       0.001603  4.792932e-04         0.051289        0.004573   
386       0.001619  4.930940e-04         0.057431        0.006129   
387       0.001602  4.808710e-04         0.051662        0.002035   
388       0.001618  4.915588e-04         0.049548        0.001424   
389       0.001612  4.721892e-04         0.051056        0.002219   
390       0.001810  3.896952e-04         0.055655        0.002628   
391       0.001810  3.872835e-04         0.053449        0.002063   
392

In [8]:
results_df = results_df.sort_values(['rank_test_score'])
results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
395       0.002007      0.000019         0.053039        0.001580   
389       0.001612      0.000472         0.051056        0.002219   
393       0.001810      0.000389         0.062027        0.005024   
387       0.001602      0.000481         0.051662        0.002035   
385       0.001603      0.000479         0.051289        0.004573   
391       0.001810      0.000387         0.053449        0.002063   
383       0.002001      0.000015         0.051256        0.001605   
394       0.002006      0.000620         0.057441        0.002561   
388       0.001618      0.000492         0.049548        0.001424   
381       0.001780      0.000410         0.052076        0.005018   
392       0.002010      0.000620         0.064214        0.004676   
386       0.001619      0.000493         0.057431        0.006129   
379       0.001609      0.000471         0.054647        0.004781   
384       0.002023      0.000042         0.049460        0.001500   
390       0.001810      0.000390         0.055655        0.002628   
377       0.001625      0.000477         0.053030        0.007048   
373       0.002407      0.001001         0.066216        0.009266   
382       0.001615      0.000476         0.054043        0.006600   
380       0.001812      0.000390         0.050075        0.001740   
367       0.002010      0.000620         0.049852        0.002002   
371       0.001313      0.000408         0.052755        0.006157   
375       0.002193      0.000399         0.055651        0.005503   
369       0.002182      0.000401         0.052872        0.002441   
365       0.001605      0.000481         0.048269        0.002047   
378       0.001210      0.000391         0.050859        0.001886   
376       0.002017      0.000027         0.051662        0.001916   
363       0.002008      0.000018         0.050451        0.002503   
372       0.001621      0.000787         0.052754        0.003767   
361       0.001794      0.000398         0.048472        0.002153   
353       0.001992      0.000630         0.065433        0.008425   
..             ...           ...              ...             ...   
211       0.001596      0.000488         0.022141        0.001716   
210       0.001996      0.000021         0.022146        0.001836   
15        0.001204      0.000415         0.020546        0.001851   
14        0.001595      0.000488         0.020733        0.001609   
209       0.001587      0.000495         0.023132        0.005047   
208       0.001796      0.000397         0.020944        0.001401   
13        0.001596      0.000488         0.019747        0.001596   
12        0.001212      0.000411         0.019933        0.001892   
11        0.001604      0.000494         0.019141        0.001931   
207       0.001995      0.000631         0.023544        0.004162   
10        0.001664      0.000419         0.018959        0.001904   
206       0.001996      0.000002         0.020145        0.001946   
9         0.001776      0.000390         0.019970        0.002974   
8         0.001394      0.000489         0.018153        0.001936   
205       0.001790      0.000395         0.019554        0.001486   
204       0.001788      0.000743         0.020745        0.001917   
7         0.001596      0.000488         0.021550        0.004118   
6         0.001794      0.000399         0.017147        0.001151   
203       0.001796      0.000400         0.018535        0.001464   
202       0.001596      0.000489         0.019159        0.001476   
5         0.001403      0.000498         0.016348        0.001727   
4         0.001595      0.000489         0.015958        0.001093   
201       0.001795      0.000399         0.017945        0.001406   
200       0.001998      0.000613         0.022536        0.005645   
3         0.001596      0.000488         0.014562        0.001493   
2         0.001198      0.000399         0.014759        0.001318   
0  