In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsRegressor 
from sklearn.metrics import mean_squared_error, make_scorer, mean_absolute_error
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import cross_val_score 
from math import sqrt

In [2]:
data = pd.read_csv('DeltaCF_data.csv')
data

Company        Time  Net Income  Cash from Operations  \
0         PM  2012-12-01       209.0               -1108.0   
1        HES  2011-12-01      -422.0                 454.0   
2       SIRI  2019-12-01      -262.0                 137.0   
3       SPGI  2013-12-01       939.0                -728.0   
4       MKTX  2015-12-01        21.2                  14.5   
5        GTN  2016-12-01        23.0                 103.4   
6          V  2013-09-01      2836.0               -1987.0   
7        BTI  2011-12-01       322.2                  96.5   
8       VALE  2015-12-01    -11520.1               -6487.9   
9        INT  2015-12-01       -50.0                 306.4   
10       SKM  2016-12-01        98.2                 305.2   
11       FNF  2013-12-01      -213.0                -136.0   
12       VFC  2017-12-01      -459.2                  -5.9   
13       CCL  2012-11-01      -614.0                -767.0   
14       KSU  2015-12-01       -19.1                   3.2   
15       AFL  2015-12-01      -418.0                 226.0   
16        WM  2016-12-01       429.0                 475.0   
17      ORCL  2019-05-01      7496.0                -835.0   
18       WBA  2013-08-01       421.0                -130.0   
19       AWK  2013-12-01        10.9                 -59.6   
20      WLTW  2013-12-01       811.0                  36.0   
21       KSU  2012-12-01        47.0                  35.2   
22       RTX  2011-12-01       606.0                 684.0   
23      DISH  2018-12-01      -523.6                -261.7   
24       SJI  2015-12-01         8.1                  25.4   
25       CCL  2019-11-01      -162.0                 -74.0   
26       SLB  2014-12-01     -1294.0                 531.0   
27       GPS  2012-01-01      -371.0                -381.0   
28       AMD  2018-12-01       370.0                  22.0   
29       DHR  2015-12-01       759.0                  43.4   
...      ...         ...         ...                   ...   
4470    HOLX  2011-09-01       220.0                  -0.7   
4471    MKTX  2019-12-01        32.0                  42.0   
4472      TT  2015-12-01      -267.1                 -84.8   
4473     ITW  2015-12-01     -1047.0                 683.0   
4474     LOW  2017-02-01       547.0                 833.0   
4475     LKQ  2019-12-01        61.2                 353.3   
4476     GLW  2011-12-01      -741.0                -646.0   
4477     EIG  2017-12-01        -5.5                  19.5   
4478     STX  2018-06-01       410.0                 197.0   
4479    NDAQ  2014-12-01        29.0                  58.0   
4480     EIG  2011-12-01       -14.9                 -14.6   
4481     VFF  2016-12-01        -4.1                   1.3   
4482    FFIV  2012-09-01        33.8                  78.5   
4483     AWK  2016-12-01        -8.0                  94.0   
4484    CCOI  2019-12-01         8.8                  14.9   
4485     EQT  2019-12-01      1022.9               -1124.6   
4486    LDOS  2013-01-01       466.0                -370.0   
4487     FCX  2013-12-01      -383.0                2365.0   
4488     FDP  2013-12-01      -177.6                 -63.9   
4489     TSN  2013-09-01       195.0                 127.0   
4490     DHI  2014-09-01        70.8                 567.9   
4491     TAP  2016-12-01      1198.7                 411.0   
4492     CTL  2012-12-01       204.0                1864.0   
4493    PAAS  2018-12-01      -110.7                 -69.6   
4494     BIP  2019-12-01      -140.0                 781.0   
4495     CNK  2013-12-01       -20.4                 -85.5   
4496     UNH  2011-12-01       508.0                 695.0   
4497    IDXX  2017-12-01        41.1                  34.4   
4498     WRB  2018-12-01        91.6                 -90.7   
4499     AVY  2016-01-01        29.2                 118.8   

      Cash from Investing  Cash from Financing  Net Change in Cash  \
0                    40.0                238.0              -414.0   
1                 -1

In [3]:
prices = data['Price_Change'] 
data = data.drop(['Company', 'Time', 'Price_Change'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")

Net Income
Done
Cash from Operations
Done
Cash from Investing
Done
Cash from Financing
Done
Net Change in Cash
Done
Levered Free Cash Flow
Done
Unlevered Free Cash Flow
Done
Free Cash Flow / Share
Done


In [4]:
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Price_Change', prices)
data

Net Income  Cash from Operations  Cash from Investing  \
0       0.482030              0.437469             0.504055   
1       0.478693              0.476244             0.493695   
2       0.479539              0.468375             0.506639   
3       0.485891              0.446902             0.522545   
4       0.481037              0.465334             0.503555   
5       0.481047              0.467540             0.501649   
6       0.495925              0.415649             0.513362   
7       0.482629              0.467369             0.500640   
8       0.419992              0.303920             0.529392   
9       0.480660              0.472580             0.504919   
10      0.481444              0.472550             0.506883   
11      0.479798              0.461598             0.505670   
12      0.478496              0.464827             0.498641   
13      0.477677              0.445934             0.510470   
14      0.480824              0.465053             0.504593   
15      0.478714              0.470584             0.498702   
16      0.483194              0.476765             0.501279   
17      0.520573              0.444246             0.751266   
18      0.483152              0.461747             0.533466   
19      0.480983              0.463494             0.498590   
20      0.485214              0.465867             0.504147   
21      0.481173              0.465847             0.503428   
22      0.484130              0.481953             0.522822   
23      0.478155              0.458477             0.538714   
24      0.480968              0.465604             0.503653   
25      0.480068              0.463137             0.490188   
26      0.474081              0.478155             0.513954   
27      0.478963              0.455516             0.503555   
28      0.482882              0.465520             0.502855   
29      0.484939              0.466051             0.415247   
...          ...                   ...                  ...   
4470    0.482088              0.464956             0.502212   
4471    0.481094              0.466016             0.503195   
4472    0.479512              0.462869             0.496088   
4473    0.475387              0.481928             0.480274   
4474    0.483818              0.485652             0.488227   
4475    0.481249              0.473744             0.512931   
4476    0.477006              0.448938             0.501540   
4477    0.480896              0.465458             0.503553   
4478    0.483093              0.469864             0.495064   
4479    0.481078              0.466413             0.511908   
4480    0.480846              0.464611             0.505680   
4481    0.480903              0.465006             0.503747   
4482    0.481104              0.466922             0.502112   
4483    0.480883              0.467307             0.502740   
4484    0.480971              0.465344             0.503770   
4485    0.486335              0.437057             0.522037   
4486    0.483390              0.455789             0.500402   
4487    0.478899              0.523682             0.446486   
4488    0.479985              0.463387             0.503059   
4489    0.481956              0.468126             0.503878   
4490    0.481299              0.479071             0.500187   
4491    0.487265              0.475176             0.411823   
4492    0.482004              0.511245             0.511108   
4493    0.480339              0.463246             0.503891   
4494    0.480184              0.484361             0.459077   
4495    0.480817              0.462851             0.502745   
4496    0.483612              0.482226             0.512723   
4497    0.481142              0.465828             0.503379   
4498    0.481409              0.462722             0.500819   
4499    0.481079              0.467923             0.503959   

      Cash from Financing  Net Change in Cash  Levered Free Cash Flow  \
0                0.540513 

In [6]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:8] # Parameters
y = NpMatrix[:,8] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.48203031 0.43746897 0.50405519 ... 0.53258539 0.53757125 0.43768056]
 [0.47869279 0.47624367 0.49369513 ... 0.53047059 0.53537496 0.43753007]
 [0.47953907 0.46837454 0.50663944 ... 0.54162278 0.54645877 0.43771673]
 ...
 [0.48114224 0.46582762 0.50337913 ... 0.5401717  0.54495221 0.43773546]
 [0.48140935 0.46272217 0.5008195  ... 0.53972743 0.54452586 0.43770317]
 [0.4810793  0.46792275 0.50395905 ... 0.54119171 0.54594025 0.43781943]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 8
Total Number of Training instances: 4500


[  5.16 -19.74   1.44 ...  39.11   2.39   8.62]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 5.16
Total number of y values 4500


In [7]:
knn =  KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='manhattan',
                    metric_params=None, n_jobs=None, n_neighbors=99, p=2,
                    weights='distance')

In [8]:
CV = KFold(n_splits=10, random_state=None, shuffle=False)

In [9]:
# Applying k-Fold Cross Validation 
# https://stackoverflow.com/questions/24132237/scikit-learn-cross-validation-scoring-for-regression#:~:text=How%20can%20one%20use%20cross_val_score%20for%20regression%3F%20The,accuracy%2C%20which%20is%20not%20very%20meaningful%20for%20regression.
#mse = make_scorer(mean_squared_error, greater_is_better= False)
mae = make_scorer(mean_absolute_error, greater_is_better= False) 
scores = cross_val_score(knn, X, y, scoring= mae, cv = CV) 

print(scores)

print("Mean MAE:", scores.mean())
print("SD of the mean:", scores.std())

[-19.58710281 -14.11848438 -20.20707432 -16.22278737 -16.76853135
 -16.68016435 -17.50630064 -13.53930346 -14.07562619 -13.67137585]
Mean MAE: -16.237675070356254
SD of the mean: 2.282423269491948
