In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, StratifiedKFold

In [3]:
data = pd.read_csv('MFTrend_data.csv')
data

Company        Time  Total Assets  Total Liabilities  Total Equity  \
0       CINF  2019-12-01        3473.0             1442.0        2031.0   
1       SIRI  2015-12-01        -322.4             1154.0       -1476.3   
2        SNA  2016-12-01         392.1              187.6         204.5   
3       ATNI  2018-12-01         -98.3              -91.4          -6.9   
4        DRI  2019-05-01         423.2              225.4         197.8   
5        ABC  2017-09-01        1679.0             1743.9         -64.9   
6        HPQ  2013-10-01       -3092.0            -7915.0        4823.0   
7        SJM  2012-04-01         790.6              919.6        -129.0   
8        WHR  2018-12-01       -1691.0              232.0       -1923.0   
9        SNA  2017-12-01         525.9              188.8         337.1   
10       WAT  2012-12-01         445.0              204.1         240.8   
11        FE  2018-12-01       -2194.0            -5083.0        2889.0   
12       HFC  2019-12-01        1170.2             1119.9          50.3   
13       BTI  2019-12-01         230.4            -1022.3        1252.7   
14        MA  2015-12-01         921.0             1683.0        -762.0   
15       CVS  2018-12-01      101325.0            80477.0       20848.0   
16       NOC  2013-12-01        -162.0            -1268.0        1106.0   
17       ALL  2014-12-01      -15041.0           -15865.0         824.0   
18       TAP  2017-12-01         905.4             -660.2        1565.6   
19      AVGO  2014-11-01        7076.0             6719.0         357.0   
20      QCOM  2019-09-01         239.0            -3863.0        4102.0   
21       UTL  2011-12-01          87.1               84.4           2.7   
22      REGN  2017-12-01        1790.8               96.0        1694.9   
23       BLK  2011-12-01        1437.0             2409.0        -972.0   
24      XLNX  2017-04-01         -78.8                3.5         -82.3   
25      ULTA  2019-02-01         282.5              236.5          46.0   
26       DAR  2017-12-01         260.2                8.7         251.5   
27       PWR  2013-12-01         652.4              183.1         469.4   
28       KSU  2014-12-01         541.0              153.5         387.5   
29       TXN  2013-12-01       -1083.0             -929.0        -154.0   
...      ...         ...           ...                ...           ...   
4470    ORLY  2015-12-01         144.6              201.7         -57.1   
4471    CDNS  2017-12-01         321.8               74.4         247.4   
4472      IT  2017-12-01        4915.9             3993.2         922.6   
4473    ANSS  2014-12-01          30.5              -50.7          81.3   
4474     CMI  2013-12-01        2180.0             1284.0         896.0   
4475     NUE  2014-12-01         412.6              247.8         164.8   
4476     GIS  2013-05-01        1561.2             1195.7         365.5   
4477    SCCO  2015-12-01        1199.3             1736.7        -537.4   
4478      EL  2014-06-01         723.6              156.1         567.5   
4479     LEN  2015-11-01        1496.3              797.6         698.8   
4480     XOM  2012-12-01        2743.0            -8173.0       10916.0   
4481     UNP  2011-12-01        2008.0             1193.0         815.0   
4482     CMS  2014-12-01        1769.0             1553.0         216.0   
4483     DUK  2016-12-01       11605.0            10335.0        1270.0   
4484     CPE  2013-12-01          45.8              -27.3          73.1   
4485    IDXX  2016-12-01          55.7               79.9         -24.2   
4486    STKL  2017-12-01        -147.4              -20.9        -126.5   
4487     AFL  2017-12-01        7398.0             3282.0        4116.0   
4488     BLK  2019-12-01        9049.0             7660.0        1389.0   
4489   DGICA  2019-12-01          91.1               38.9          52.1   
4490     BWA  2015-12-01        1597.7             1657.1         -59.4   
4491     DVA  2013-12-01      

In [4]:
classes = data['Classification'] 
data = data.drop(['Company', 'Time', 'Classification'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")
    
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Classification', classes)
data

Total Assets
Done
Total Liabilities
Done
Total Equity
Done
Total Shares Out. on Filing Date
Done
Book Value / Share
Done
Tangible Book Value
Done
Tangible Book Value Per Share
Done
Total Debt
Done
Net Debt
Done
Total Revenues
Done
Operating Income
Done
Revenue Per Share
Done
Basic EPS
Done
Normalized Basic EPS
Done
Dividend Per Share
Done
EBITA
Done
EBIT
Done
Normalized Net Income
Done
Net Income
Done
Cash from Operations
Done
Cash from Investing
Done
Cash from Financing
Done
Net Change in Cash
Done
Levered Free Cash Flow
Done
Unlevered Free Cash Flow
Done
Free Cash Flow / Share
Done


Total Assets  Total Liabilities  Total Equity  \
0         0.569312           0.673112      0.530858   
1         0.557462           0.671981      0.508632   
2         0.559693           0.668188      0.519284   
3         0.558162           0.667093      0.517944   
4         0.559790           0.668336      0.519241   
5         0.563711           0.674297      0.517576   
6         0.548815           0.636383      0.548551   
7         0.560937           0.671061      0.517170   
8         0.553189           0.668362      0.505802   
9         0.560111           0.668193      0.520124   
10        0.559858           0.668253      0.519514   
11        0.551619           0.647500      0.536295   
12        0.562123           0.671848      0.518306   
13        0.559188           0.663439      0.525926   
14        0.561345           0.674058      0.513159   
15        0.874823           0.983345      0.650102   
16        0.557963           0.662474      0.524996   
17        0.511508           0.605177      0.523209   
18        0.561296           0.664860      0.527909   
19        0.580562           0.693826      0.520250   
20        0.559215           0.652288      0.543982   
21        0.558741           0.667783      0.518005   
22        0.564060           0.667829      0.528728   
23        0.562956           0.676908      0.511828   
24        0.558223           0.667465      0.517466   
25        0.559351           0.668380      0.518279   
26        0.559281           0.667486      0.519581   
27        0.560506           0.668170      0.520962   
28        0.560158           0.668054      0.520443   
29        0.555088           0.663805      0.517012   
...            ...                ...           ...   
4470      0.558921           0.668243      0.517626   
4471      0.559474           0.667744      0.519555   
4472      0.573817           0.683126      0.523834   
4473      0.558564           0.667253      0.518503   
4474      0.565275           0.672492      0.523666   
4475      0.559757           0.668424      0.519032   
4476      0.563343           0.672145      0.520304   
4477      0.562213           0.674269      0.514582   
4478      0.560728           0.668064      0.521584   
4479      0.563141           0.670583      0.522416   
4480      0.567033           0.635371      0.587162   
4481      0.564738           0.672135      0.523152   
4482      0.563992           0.673548      0.519356   
4483      0.594702           0.708019      0.526036   
4484      0.558612           0.667345      0.518451   
4485      0.558643           0.667765      0.517834   
4486      0.558009           0.667370      0.517186   
4487      0.581567           0.680334      0.544071   
4488      0.586722           0.697519      0.526790   
4489      0.558753           0.667604      0.518318   
4490      0.563457           0.673956      0.517611   
4491      0.561854           0.668547      0.523090   
4492      0.558625           0.667358      0.518457   
4493      0.549209           0.663143      0.506149   
4494      0.558545           0.667528      0.518017   
4495      0.626370           0.746483      0.528217   
4496      0.558001           0.667268      0.517333   
4497      0.559783           0.668987      0.518177   
4498      0.565072           0.681975      0.507943   
4499      0.553125           0.659165      0.520520   

      Total Shares Out. on Filing Date  Book Value / Share  \
0                             0.206247            0.001261   
1                             0.185579            0.001001   
2                             0.206252            0.001081   
3                             0.206256            0.001016   
4                             0.206239            0.001041   
5                             0.206171            0.001002   
6                             0.204582            0.001065   
7                             0.206085            0.001016   
8                             0.20595

In [6]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:26] # Parameters
y = NpMatrix[:,26] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.56931236 0.67311195 0.5308581  ... 0.55756272 0.56219563 0.43772384]
 [0.55746247 0.67198147 0.50863228 ... 0.54663096 0.5515018  0.43771544]
 [0.55969327 0.6681881  0.51928354 ... 0.54098986 0.54574963 0.43779811]
 ...
 [0.5597835  0.66898728 0.51817709 ... 0.54043122 0.54524518 0.43777422]
 [0.56507245 0.68197519 0.50794345 ... 0.54105975 0.5456177  0.43780909]
 [0.55312547 0.6591651  0.52051989 ... 0.55138498 0.55573384 0.4377148 ]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 26
Total Number of Training instances: 4500


[1. 1. 1. ... 1. 0. 0.]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 1.0
Total number of y values 4500


In [7]:
# Grid Search for Optimal KNN Hyperparameters
# Using GridSearchCV to find best parameters
kvals = range(1,100)
params = {'n_neighbors': kvals,
        'weights' : ['uniform', 'distance'],
         'metric' : ['euclidean', 'manhattan']}

knn = KNeighborsClassifier()
cv_str = StratifiedKFold(n_splits=5)

gs_modelKNN = GridSearchCV(knn, params,  cv= cv_str)
grid_results = gs_modelKNN.fit(X , y)

# Best parameters, best test score using these parameters, optimal KNN Configuration
print("Best Parameters", gs_modelKNN.best_params_)
print("Best score on Test Data", gs_modelKNN.best_score_)
print("Optimal Configuration", gs_modelKNN.best_estimator_)

Best Parameters {'metric': 'manhattan', 'n_neighbors': 26, 'weights': 'uniform'}
Best score on Test Data 0.7108888888888889
Optimal Configuration KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='manhattan',
                     metric_params=None, n_jobs=None, n_neighbors=26, p=2,
                     weights='uniform')


In [8]:
# Summarize the results in a readable format
print("Best: {0}, using {1}".format(grid_results.cv_results_['mean_test_score'], grid_results.best_params_))
results_df = pd.DataFrame(grid_results.cv_results_)
results_df

Best: [0.63111111 0.63111111 0.56711111 0.63111111 0.66488889 0.66422222
 0.622      0.66222222 0.67488889 0.674      0.65355556 0.674
 0.67777778 0.67888889 0.66422222 0.68222222 0.68577778 0.68488889
 0.678      0.68866667 0.68933333 0.69066667 0.68777778 0.69111111
 0.69155556 0.69311111 0.68933333 0.696      0.69688889 0.69822222
 0.69755556 0.69755556 0.70133333 0.70177778 0.7        0.70177778
 0.70311111 0.70244444 0.70155556 0.70355556 0.70044444 0.70044444
 0.69822222 0.70266667 0.70066667 0.70088889 0.69911111 0.70311111
 0.70022222 0.7        0.70111111 0.70222222 0.69955556 0.69911111
 0.70355556 0.70111111 0.69866667 0.69777778 0.70022222 0.69977778
 0.698      0.69755556 0.70066667 0.70088889 0.70044444 0.70044444
 0.69911111 0.70311111 0.70022222 0.69955556 0.69777778 0.70022222
 0.70066667 0.7        0.69911111 0.702      0.69977778 0.70111111
 0.70066667 0.70133333 0.69911111 0.7        0.70044444 0.70044444
 0.69933333 0.70044444 0.70022222 0.70088889 0.70133333 0.702

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0         0.005594      0.001205         0.115881        0.005513   
1         0.004188      0.000399         0.091556        0.002918   
2         0.004799      0.000734         0.120884        0.009836   
3         0.004388      0.000489         0.099120        0.003363   
4         0.004595      0.000495         0.121267        0.002656   
5         0.004189      0.000399         0.104040        0.001595   
6         0.003978      0.000022         0.123090        0.002664   
7         0.003989      0.000002         0.106948        0.003324   
8         0.004595      0.000495         0.128185        0.005760   
9         0.004389      0.000797         0.108917        0.002729   
10        0.004377      0.000482         0.131683        0.005658   
11        0.004386      0.000487         0.109223        0.002081   
12        0.004589      0.001216         0.130244        0.003482   
13        0.004778      0.001600         0.114311        0.002714   
14        0.004588      0.000489         0.134839        0.002631   
15        0.004389      0.000489         0.114323        0.004539   
16        0.004572      0.000493         0.134103        0.003930   
17        0.004189      0.000400         0.113599        0.002475   
18        0.005186      0.001918         0.137233        0.004946   
19        0.004390      0.000479         0.118074        0.004975   
20        0.004194      0.000397         0.134077        0.002117   
21        0.004413      0.000472         0.118274        0.004045   
22        0.004180      0.000403         0.139028        0.008469   
23        0.004388      0.000488         0.118084        0.002410   
24        0.004174      0.000406         0.137280        0.003458   
25        0.003989      0.000002         0.118680        0.002599   
26        0.004580      0.000783         0.138030        0.002071   
27        0.004388      0.000489         0.120390        0.002947   
28        0.004203      0.000410         0.139220        0.004649   
29        0.004388      0.000489         0.121277        0.002793   
..             ...           ...              ...             ...   
366       0.004391      0.000493         0.157572        0.004039   
367       0.004611      0.000492         0.137808        0.000743   
368       0.004395      0.000483         0.158993        0.006596   
369       0.005018      0.000015         0.142208        0.007254   
370       0.004396      0.000482         0.159761        0.006724   
371       0.004986      0.000630         0.140826        0.002473   
372       0.004208      0.000390         0.158168        0.001634   
373       0.004406      0.000487         0.140654        0.001796   
374       0.004222      0.000383         0.158642        0.004678   
375       0.004395      0.000483         0.142620        0.004647   
376       0.004196      0.000396         0.160364        0.007643   
377       0.004582      0.000484         0.161788        0.011176   
378       0.005185      0.000978         0.176367        0.008074   
379       0.005386      0.000488         0.180609        0.016111   
380       0.004004      0.000030         0.164187        0.004805   
381       0.004419      0.000503         0.148747        0.004776   
382       0.004611      0.000491         0.157410        0.002223   
383       0.004601      0.000471         0.144644        0.002475   
384       0.004410      0.000471         0.157372        0.002774   
385       0.004621      0.000486         0.146795        0.006690   
386       0.004388      0.000489         0.159575        0.004328   
387       0.004388      0.000489         0.142626        0.000631   
388       0.004603      0.000501         0.161952        0.005065   
389       0.004598      0.000497         0.142820        0.003146   
390       0.004795      0.000748         0.159027        0.001758   
391       0.004819      0.000396         0.140610        0.000631   
392

In [9]:
results_df = results_df.sort_values(['rank_test_score'])
results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
248       0.004361      0.000498         0.144681        0.004095   
275       0.004395      0.000506         0.132051        0.003335   
272       0.004785      0.000402         0.144814        0.002299   
246       0.004582      0.000483         0.140031        0.004395   
244       0.004787      0.000399         0.140424        0.003240   
259       0.004382      0.000494         0.130894        0.007021   
258       0.005186      0.000978         0.178327        0.017930   
247       0.004400      0.000486         0.125018        0.009322   
252       0.004199      0.000412         0.144423        0.008141   
254       0.004390      0.000489         0.144006        0.007980   
271       0.004381      0.000494         0.125842        0.003362   
274       0.003989      0.000002         0.143049        0.002203   
276       0.004183      0.000402         0.142825        0.002772   
270       0.004591      0.000470         0.145963        0.005992   
277       0.004587      0.000489         0.136631        0.009507   
255       0.004788      0.000747         0.123879        0.000758   
249       0.003987      0.000031         0.121082        0.002075   
256       0.004388      0.000488         0.141440        0.003383   
260       0.005766      0.001935         0.151010        0.008718   
147       0.006183      0.000399         0.202459        0.013186   
238       0.004387      0.000490         0.141347        0.004236   
265       0.003997      0.000018         0.125815        0.002428   
262       0.004401      0.000478         0.145055        0.004910   
261       0.004374      0.000484         0.124515        0.003315   
138       0.005196      0.000394         0.215022        0.018587   
245       0.004089      0.000202         0.122583        0.001484   
364       0.005403      0.000787         0.163356        0.008212   
263       0.004592      0.000806         0.124716        0.003662   
267       0.004403      0.000491         0.127654        0.003040   
240       0.004588      0.000489         0.146002        0.005731   
..             ...           ...              ...             ...   
15        0.004389      0.000489         0.114323        0.004539   
13        0.004778      0.001600         0.114311        0.002714   
18        0.005186      0.001918         0.137233        0.004946   
12        0.004589      0.001216         0.130244        0.003482   
8         0.004595      0.000495         0.128185        0.005760   
9         0.004389      0.000797         0.108917        0.002729   
11        0.004386      0.000487         0.109223        0.002081   
209       0.004171      0.000390         0.111924        0.001591   
207       0.004190      0.000400         0.110503        0.001464   
206       0.004580      0.000498         0.130418        0.003257   
203       0.004692      0.000983         0.112805        0.006270   
212       0.004388      0.000489         0.131448        0.001934   
202       0.004189      0.000399         0.130757        0.009252   
205       0.004189      0.000401         0.110896        0.003114   
4         0.004595      0.000495         0.121267        0.002656   
14        0.004588      0.000489         0.134839        0.002631   
5         0.004189      0.000399         0.104040        0.001595   
7         0.003989      0.000002         0.106948        0.003324   
10        0.004377      0.000482         0.131683        0.005658   
208       0.003996      0.000016         0.131078        0.002904   
199       0.003988      0.000002         0.101754        0.002264   
198       0.005186      0.000747         0.138037        0.013273   
201       0.004396      0.000496         0.105905        0.002045   
204       0.003990      0.000004         0.130847        0.004290   
3         0.004388      0.000489         0.099120        0.003363   
1         0.004188      0.000399         0.091556        0.002918   
0  