In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.svm import SVC

In [2]:
data = pd.read_csv('MFTrend_data.csv')
data

classes = data['Classification'] 
data = data.drop(['Company', 'Time', 'Classification'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")
    
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Classification', classes)
data

Total Assets
Done
Total Liabilities
Done
Total Equity
Done
Total Shares Out. on Filing Date
Done
Book Value / Share
Done
Tangible Book Value
Done
Tangible Book Value Per Share
Done
Total Debt
Done
Net Debt
Done
Total Revenues
Done
Operating Income
Done
Revenue Per Share
Done
Basic EPS
Done
Normalized Basic EPS
Done
Dividend Per Share
Done
EBITA
Done
EBIT
Done
Normalized Net Income
Done
Net Income
Done
Cash from Operations
Done
Cash from Investing
Done
Cash from Financing
Done
Net Change in Cash
Done
Levered Free Cash Flow
Done
Unlevered Free Cash Flow
Done
Free Cash Flow / Share
Done


Total Assets  Total Liabilities  Total Equity  \
0         0.569312           0.673112      0.530858   
1         0.557462           0.671981      0.508632   
2         0.559693           0.668188      0.519284   
3         0.558162           0.667093      0.517944   
4         0.559790           0.668336      0.519241   
5         0.563711           0.674297      0.517576   
6         0.548815           0.636383      0.548551   
7         0.560937           0.671061      0.517170   
8         0.553189           0.668362      0.505802   
9         0.560111           0.668193      0.520124   
10        0.559858           0.668253      0.519514   
11        0.551619           0.647500      0.536295   
12        0.562123           0.671848      0.518306   
13        0.559188           0.663439      0.525926   
14        0.561345           0.674058      0.513159   
15        0.874823           0.983345      0.650102   
16        0.557963           0.662474      0.524996   
17        0.511508           0.605177      0.523209   
18        0.561296           0.664860      0.527909   
19        0.580562           0.693826      0.520250   
20        0.559215           0.652288      0.543982   
21        0.558741           0.667783      0.518005   
22        0.564060           0.667829      0.528728   
23        0.562956           0.676908      0.511828   
24        0.558223           0.667465      0.517466   
25        0.559351           0.668380      0.518279   
26        0.559281           0.667486      0.519581   
27        0.560506           0.668170      0.520962   
28        0.560158           0.668054      0.520443   
29        0.555088           0.663805      0.517012   
...            ...                ...           ...   
4470      0.558921           0.668243      0.517626   
4471      0.559474           0.667744      0.519555   
4472      0.573817           0.683126      0.523834   
4473      0.558564           0.667253      0.518503   
4474      0.565275           0.672492      0.523666   
4475      0.559757           0.668424      0.519032   
4476      0.563343           0.672145      0.520304   
4477      0.562213           0.674269      0.514582   
4478      0.560728           0.668064      0.521584   
4479      0.563141           0.670583      0.522416   
4480      0.567033           0.635371      0.587162   
4481      0.564738           0.672135      0.523152   
4482      0.563992           0.673548      0.519356   
4483      0.594702           0.708019      0.526036   
4484      0.558612           0.667345      0.518451   
4485      0.558643           0.667765      0.517834   
4486      0.558009           0.667370      0.517186   
4487      0.581567           0.680334      0.544071   
4488      0.586722           0.697519      0.526790   
4489      0.558753           0.667604      0.518318   
4490      0.563457           0.673956      0.517611   
4491      0.561854           0.668547      0.523090   
4492      0.558625           0.667358      0.518457   
4493      0.549209           0.663143      0.506149   
4494      0.558545           0.667528      0.518017   
4495      0.626370           0.746483      0.528217   
4496      0.558001           0.667268      0.517333   
4497      0.559783           0.668987      0.518177   
4498      0.565072           0.681975      0.507943   
4499      0.553125           0.659165      0.520520   

      Total Shares Out. on Filing Date  Book Value / Share  \
0                             0.206247            0.001261   
1                             0.185579            0.001001   
2                             0.206252            0.001081   
3                             0.206256            0.001016   
4                             0.206239            0.001041   
5                             0.206171            0.001002   
6                             0.204582            0.001065   
7                             0.206085            0.001016   
8                             0.20595

In [4]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:26] # Parameters
y = NpMatrix[:,26] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.56931236 0.67311195 0.5308581  ... 0.55756272 0.56219563 0.43772384]
 [0.55746247 0.67198147 0.50863228 ... 0.54663096 0.5515018  0.43771544]
 [0.55969327 0.6681881  0.51928354 ... 0.54098986 0.54574963 0.43779811]
 ...
 [0.5597835  0.66898728 0.51817709 ... 0.54043122 0.54524518 0.43777422]
 [0.56507245 0.68197519 0.50794345 ... 0.54105975 0.5456177  0.43780909]
 [0.55312547 0.6591651  0.52051989 ... 0.55138498 0.55573384 0.4377148 ]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 26
Total Number of Training instances: 4500


[1. 1. 1. ... 1. 0. 0.]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 1.0
Total number of y values 4500


In [5]:
# Takes 30 mins to run

# Using GridSearchCV to find best SVM hyperparameters
params = {'C': [0.1,1, 10, 50, 100, 1000, 10000], # Slack parameter, how much error is allowed in prediction
          'gamma': ['scale', 'auto'], #[1,0.1,0.01,0.001], # Determines whether only close points determine hyperplane or those further away
          'kernel': ['linear', 'rbf', 'poly'],
         'degree': [1,2,3] } # Type of kernel used
 
cv_str = StratifiedKFold(n_splits=5)
SVM = SVC()

gs_modelSVM = GridSearchCV(SVM, params, cv= cv_str)
grid_results = gs_modelSVM.fit(X , y)

# Best parameters, best test score using these parameters, optimal KNN Configuration
print("Best Parameters", gs_modelSVM.best_params_)
print("Best score on Test Data", gs_modelSVM.best_score_)
print("Optimal Configuration", gs_modelSVM.best_estimator_)

Best Parameters {'C': 10000, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'}
Best score on Test Data 0.6846666666666666
Optimal Configuration SVC(C=10000, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)


In [6]:
# Summarize the results in a readable format
print("Best: {0}, using {1}".format(grid_results.cv_results_['mean_test_score'], grid_results.best_params_))
results_df = pd.DataFrame(grid_results.cv_results_)
results_df

Best: [0.67511111 0.67511111 0.67511111 0.67511111 0.67511111 0.67511111
 0.67511111 0.67511111 0.67511111 0.67511111 0.67511111 0.67511111
 0.67511111 0.67511111 0.67488889 0.67511111 0.67511111 0.67511111
 0.67511111 0.67511111 0.67511111 0.67511111 0.67511111 0.67511111
 0.67511111 0.67511111 0.67488889 0.67511111 0.67511111 0.67511111
 0.67511111 0.67511111 0.67555556 0.67511111 0.67511111 0.67511111
 0.67511111 0.67577778 0.67511111 0.67511111 0.67511111 0.67511111
 0.67511111 0.67577778 0.67533333 0.67511111 0.67511111 0.67511111
 0.67511111 0.67577778 0.67622222 0.67511111 0.67511111 0.67511111
 0.67511111 0.67777778 0.67511111 0.67511111 0.67488889 0.67511111
 0.67511111 0.67777778 0.67555556 0.67511111 0.67488889 0.67511111
 0.67511111 0.67777778 0.67666667 0.67511111 0.67488889 0.67511111
 0.67466667 0.67755556 0.67466667 0.67466667 0.67466667 0.67511111
 0.67466667 0.67755556 0.67733333 0.67466667 0.67466667 0.67511111
 0.67466667 0.67755556 0.67666667 0.67466667 0.67466667 

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0         0.371016      0.011141         0.060652        0.006153     0.1   
1         0.760713      0.082691         0.108296        0.012040     0.1   
2         0.669376      0.123309         0.089983        0.010606     0.1   
3         0.396155      0.031169         0.065648        0.004767     0.1   
4         0.551014      0.018098         0.101800        0.013869     0.1   
5         0.393985      0.023163         0.063629        0.002918     0.1   
6         0.355799      0.017214         0.056249        0.002252     0.1   
7         0.617534      0.013626         0.097737        0.008579     0.1   
8         0.598057      0.020152         0.071418        0.006926     0.1   
9         0.327763      0.011922         0.055050        0.000974     0.1   
10        0.505404      0.013776         0.092960        0.001170     0.1   
11        0.354255      0.010654         0.062632        0.002130     0.1   
12        0.323537      0.009452         0.054255        0.001954     0.1   
13        0.595153      0.011404         0.093557        0.003529     0.1   
14        0.587193      0.018235         0.065025        0.002034     0.1   
15        0.357578      0.034859         0.058256        0.004943     0.1   
16        0.539970      0.011983         0.095366        0.002801     0.1   
17        0.412392      0.019671         0.069818        0.004416     0.1   
18        0.453431      0.084258         0.063428        0.002722       1   
19        0.720784      0.018338         0.110741        0.017352       1   
20        0.443904      0.023421         0.066836        0.003688       1   
21        0.380093      0.025841         0.061649        0.006318       1   
22        0.555214      0.015354         0.095140        0.003246       1   
23        0.357884      0.012665         0.065617        0.005955       1   
24        0.367840      0.034316         0.056445        0.002332       1   
25        0.701659      0.051365         0.100449        0.008985       1   
26        0.592234      0.030605         0.064827        0.003679       1   
27        0.368522      0.026749         0.060432        0.007781       1   
28        0.546896      0.020164         0.092162        0.003712       1   
29        0.374181      0.010973         0.065830        0.002591       1   
..             ...           ...              ...             ...     ...   
96        1.886837      0.303125         0.047292        0.001372    1000   
97        1.774664      0.140681         0.081183        0.003905    1000   
98        7.060179      0.722982         0.054301        0.001923    1000   
99        1.888771      0.286708         0.047887        0.001651    1000   
100       0.840418      0.061447         0.077794        0.000632    1000   
101       0.513637      0.023061         0.053237        0.000487    1000   
102       1.886228      0.298933         0.048470        0.001353    1000   
103       1.803415      0.147019         0.079788        0.001879    1000   
104      24.455614      3.934859         0.054878        0.002075    1000   
105       1.975946      0.370833         0.051466        0.003854    1000   
106       0.841218      0.059842         0.078007        0.000391    1000   
107       0.464448      0.011854         0.053813        0.000654    1000   
108       5.015349      0.267252         0.047274        0.001352   10000   
109       7.191879      0.771605         0.080599        0.003117   10000   
110       5.153705      0.898187         0.054867        0.002007   10000   
111       5.030494      0.266661         0.046897        0.001268   10000   
112       1.506733      0.229788         0.078978        0.001720   10000   
113       1.622274      0.372579         0.053662        0.001165   10000   
114       5.000327      0.230466         0.048263        0.002848   10000   
115       7.151391      0.718483         0.078982        0.003108   10000   
1

In [7]:
results_df = results_df.sort_values(['rank_test_score'])
results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
122      79.296258     17.528901         0.049467        0.001628   10000   
104      24.455614      3.934859         0.054878        0.002075    1000   
116      26.741547      7.852100         0.055646        0.001928   10000   
55        0.708143      0.026569         0.078393        0.001735      50   
61        0.709107      0.028798         0.077996        0.000983      50   
67        0.724313      0.044139         0.079396        0.001873      50   
73        0.789993      0.035656         0.079417        0.002032     100   
79        0.784333      0.045389         0.078198        0.001496     100   
85        0.792388      0.039102         0.079612        0.002126     100   
80        2.255084      0.130120         0.054466        0.003266     100   
98        7.060179      0.722982         0.054301        0.001923    1000   
91        1.793980      0.143597         0.078803        0.002185    1000   
97        1.774664      0.140681         0.081183        0.003905    1000   
108       5.015349      0.267252         0.047274        0.001352   10000   
103       1.803415      0.147019         0.079788        0.001879    1000   
111       5.030494      0.266661         0.046897        0.001268   10000   
114       5.000327      0.230466         0.048263        0.002848   10000   
117       5.233286      0.300557         0.048462        0.001947   10000   
120       4.954317      0.238277         0.049071        0.003913   10000   
123       4.918863      0.207142         0.048101        0.002620   10000   
110       5.153705      0.898187         0.054867        0.002007   10000   
86        5.780087      0.533191         0.055927        0.002070     100   
68        4.060847      0.255466         0.054055        0.001163      50   
112       1.506733      0.229788         0.078978        0.001720   10000   
50        1.784128      0.262290         0.054456        0.001494      10   
118       1.494267      0.232404         0.078187        0.001947   10000   
124       1.493397      0.227105         0.077601        0.000759   10000   
49        0.616087      0.019468         0.081190        0.002793      10   
125       0.624357      0.055119         0.054467        0.001354   10000   
43        0.603428      0.019499         0.078801        0.001989      10   
..             ...           ...              ...             ...     ...   
60        0.981616      0.180235         0.047289        0.001032      50   
28        0.546896      0.020164         0.092162        0.003712       1   
58        0.587874      0.019356         0.077405        0.000475      50   
70        0.596390      0.030357         0.078387        0.001346      50   
119       0.999064      0.077461         0.053469        0.000802   10000   
64        0.587049      0.017202         0.077835        0.001034      50   
107       0.464448      0.011854         0.053813        0.000654    1000   
106       0.841218      0.059842         0.078007        0.000391    1000   
14        0.587193      0.018235         0.065025        0.002034     0.1   
26        0.592234      0.030605         0.064827        0.003679       1   
100       0.840418      0.061447         0.077794        0.000632    1000   
94        0.847657      0.057895         0.078582        0.001459    1000   
93        1.907948      0.278460         0.047281        0.001350    1000   
72        1.069030      0.211915         0.048685        0.002305     100   
88        0.604823      0.008023         0.077404        0.000499     100   
74        1.140332      0.280650         0.053468        0.001846     100   
75        1.026049      0.205974         0.048470        0.002639     100   
76        0.606668      0.017689         0.077814        0.001648     100   
84        1.038727      0.194142         0.049915        0.005617     100   
105       1.975946      0.370833         0.051466        0.003854    1000   
1