In [7]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, StratifiedKFold, cross_val_score 

In [8]:
data = pd.read_csv('BSTrend_data.csv')
data

Company        Time  Total Assets  Total Liabilities  Total Equity  \
0         CI  2011-12-01        5015.0             3684.0        1331.0   
1         RE  2014-12-01        1009.8              198.8         811.0   
2       PAYX  2016-05-01         -26.7             -152.9         126.2   
3        DOV  2018-12-01       -2292.6             -678.1       -1614.5   
4        BIP  2016-12-01        3540.0             1072.0        2468.0   
5        EOG  2018-12-01        4101.4             1020.5        3080.9   
6        MAS  2011-12-01        -843.0               -3.0        -840.0   
7       ATNI  2011-12-01          50.8               27.3          23.5   
8       PEIX  2016-12-01          33.5              -13.1          46.8   
9       ATVI  2011-12-01        -170.0             -459.0         289.0   
10       ROK  2019-09-01        -149.0             1064.3       -1213.3   
11       XEL  2019-12-01        4461.0             3444.0        1017.0   
12       SCL  2013-12-01         181.7              108.9          72.8   
13      SPGI  2013-12-01        -991.0            -1495.0         504.0   
14       FNF  2013-12-01         625.0             -161.0         786.0   
15        EA  2016-03-01         903.0              543.0         360.0   
16       CMS  2018-12-01        1479.0             1165.0         314.0   
17      MNST  2016-12-01       -1417.8               61.9       -1479.7   
18       IPG  2019-12-01        2131.6             1742.0         389.6   
19       CCL  2011-11-01        1147.0              346.0         801.0   
20       ADS  2011-12-01         708.0              555.2         152.9   
21      ATNI  2012-12-01          37.2               -4.6          41.7   
22      AMZN  2012-12-01        7277.0             6842.0         435.0   
23       NGS  2014-12-01          26.1                8.2          17.9   
24       MKC  2013-11-01         284.3               36.8         247.5   
25       EPD  2017-12-01        2224.1             1717.7         506.4   
26       OGE  2014-12-01         393.1              185.8         207.3   
27       WDR  2017-12-01         -21.9              -54.6          32.7   
28      GILD  2016-12-01        5261.0             5013.0         248.0   
29     TCEHY  2011-12-01        3576.4             2274.8        1301.6   
...      ...         ...           ...                ...           ...   
4470    CHRW  2012-12-01         666.2              410.3         255.9   
4471      TT  2014-12-01        -359.6              726.3       -1085.9   
4472     AUY  2015-12-01       -2965.9            -1097.7       -1868.2   
4473     VMC  2019-12-01         816.7              397.7         419.0   
4474     AOS  2018-12-01        -125.9             -198.0          72.1   
4475     TGT  2013-02-01        1533.0              796.0         737.0   
4476     ALK  2015-12-01         466.0              182.0         284.0   
4477     TJX  2013-02-01        1230.3              773.6         456.6   
4478     ASH  2019-09-01       -1008.0            -1173.0         165.0   
4479      WM  2012-12-01         528.0              243.0         285.0   
4480    NLOK  2015-04-01        -306.0             -444.0         138.0   
4481     BMY  2013-12-01        2695.0             1097.0        1598.0   
4482     TAC  2017-12-01           7.4               -8.1          15.4   
4483     PWR  2012-12-01         441.7               58.9         382.6   
4484    VRSN  2013-12-01         598.3             1012.5        -414.3   
4485      BG  2012-12-01        2059.0             2841.0        -782.0   
4486     MRK  2015-12-01        3510.0             7534.0       -4024.0   
4487     SMG  2014-09-01         121.1              264.4        -143.3   
4488    CMCL  2019-12-01          17.9              -28.1          45.9   
4489     SLB  2017-12-01       -5969.0            -1701.0       -4268.0   
4490     XEL  2018-12-01        2957.0             2190.0         767.0   
4491     ETR  2019-12-01      

In [9]:
classes = data['Classification'] 
data = data.drop(['Company', 'Time', 'Classification'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")
    
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Classification', classes)
data

Total Assets
Done
Total Liabilities
Done
Total Equity
Done
Total Shares Out. on Filing Date
Done
Book Value / Share
Done
Tangible Book Value
Done
Tangible Book Value Per Share
Done
Total Debt
Done
Net Debt
Done


Total Assets  Total Liabilities  Total Equity  \
0         0.574127           0.681912      0.526422   
1         0.561622           0.668232      0.523127   
2         0.558386           0.666852      0.518787   
3         0.551311           0.664790      0.507757   
4         0.569522           0.671660      0.533627   
5         0.571274           0.671457      0.537511   
6         0.555837           0.667440      0.512665   
7         0.558628           0.667559      0.518137   
8         0.558574           0.667400      0.518284   
9         0.557938           0.665650      0.519819   
10        0.558004           0.671629      0.510299   
11        0.572397           0.680970      0.524432   
12        0.559036           0.667879      0.518449   
13        0.555375           0.661583      0.521181   
14        0.560420           0.666820      0.522969   
15        0.561288           0.669583      0.520269   
16        0.563087           0.672025      0.519977   
17        0.554042           0.667695      0.508611   
18        0.565124           0.674290      0.520457   
19        0.562050           0.668810      0.523064   
20        0.560680           0.669631      0.518957   
21        0.558585           0.667434      0.518252   
22        0.581189           0.694308      0.520744   
23        0.558551           0.667484      0.518101   
24        0.559357           0.667596      0.519556   
25        0.565413           0.674194      0.521197   
26        0.559696           0.668181      0.519301   
27        0.558401           0.667237      0.518195   
28        0.574895           0.687129      0.519559   
29        0.569635           0.676381      0.526236   
...            ...                ...           ...   
4470      0.560549           0.669062      0.519609   
4471      0.557346           0.670303      0.511106   
4472      0.549209           0.663143      0.506149   
4473      0.561019           0.669013      0.520643   
4474      0.558076           0.666675      0.518445   
4475      0.563255           0.670576      0.522658   
4476      0.559924           0.668166      0.519787   
4477      0.562310           0.670488      0.520881   
4478      0.555322           0.662847      0.519033   
4479      0.560118           0.668406      0.519794   
4480      0.557514           0.665709      0.518862   
4481      0.566883           0.671758      0.528114   
4482      0.558492           0.667420      0.518085   
4483      0.559848           0.667683      0.520412   
4484      0.560337           0.671426      0.515362   
4485      0.564898           0.678603      0.513032   
4486      0.569428           0.697025      0.492487   
4487      0.558847           0.668490      0.517080   
4488      0.558525           0.667341      0.518278   
4489      0.539833           0.660775      0.490941   
4490      0.567701           0.676048      0.522848   
4491      0.569237           0.675437      0.526951   
4492      0.547089           0.652732      0.518653   
4493      0.568752           0.676176      0.524775   
4494      0.560424           0.668882      0.519649   
4495      0.558443           0.667495      0.517866   
4496      0.562484           0.670186      0.521721   
4497      0.558098           0.670463      0.512374   
4498      0.563987           0.674461      0.517870   
4499      0.562593           0.671990      0.519033   

      Total Shares Out. on Filing Date  Book Value / Share  \
0                             0.206908            0.001079   
1                             0.206132            0.001419   
2                             0.206226            0.001014   
3                             0.205851            0.000819   
4                             0.207023            0.001043   
5                             0.206320            0.001114   
6                             0.206222            0.000956   
7                             0.206260            0.001019   
8                             0.20629

In [10]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:9] # Parameters
y = NpMatrix[:,9] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.57412675 0.68191239 0.52642218 ... 0.15660121 0.66576035 0.59525398]
 [0.56162183 0.66823206 0.52312694 ... 0.15688709 0.65094776 0.60260052]
 [0.5583857  0.66685155 0.51878735 ... 0.15653233 0.64989047 0.60171398]
 ...
 [0.55809846 0.67046279 0.51237429 ... 0.15644957 0.65595174 0.608092  ]
 [0.56398688 0.67446145 0.51787038 ... 0.15653408 0.66283855 0.61190508]
 [0.56259345 0.67198972 0.51903259 ... 0.15619478 0.65718794 0.60745648]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 9
Total Number of Training instances: 4500


[1. 1. 1. ... 0. 0. 1.]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 1.0
Total number of y values 4500


In [11]:
knn = KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='manhattan',
                     metric_params=None, n_jobs=None, n_neighbors=61, p=2,
                     weights='distance')

In [12]:
CV = StratifiedKFold(n_splits=10, random_state=None, shuffle=False)

scores = cross_val_score(knn, X, y, cv = CV) 

print(scores)

print("Mean Accuracy:", scores.mean())
print("SD of the mean:", scores.std())

[0.68736142 0.68957871 0.69555556 0.69333333 0.69111111 0.68444444
 0.7        0.71333333 0.68374165 0.69710468]
Mean Accuracy: 0.693556423598251
SD of the mean: 0.008299518216221607
