In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_squared_error, make_scorer, mean_absolute_error
from sklearn.model_selection import cross_val_score 
from math import sqrt
from sklearn.model_selection import KFold
from sklearn.model_selection import RepeatedKFold, StratifiedKFold
from sklearn.model_selection import GridSearchCV

In [2]:
data = pd.read_csv('BSTrend_data.csv')
data

Company        Time  Total Assets  Total Liabilities  Total Equity  \
0        XRX  2016-12-01       -7490.0            -2985.0       -4505.0   
1        MCK  2012-03-01        2207.0             2596.0        -389.0   
2        CXO  2015-12-01         890.1             -771.7        1661.8   
3       BKNG  2015-12-01       -2418.4            -1393.7       -1024.6   
4         NI  2012-12-01        1136.4              579.4         557.0   
5        TDS  2013-12-01          49.7             -164.8         214.4   
6        CMG  2019-12-01        3058.9             2740.4         318.6   
7        PHM  2017-12-01        -491.6               13.8        -505.4   
8        WRB  2014-12-01         -14.3               -5.2          -9.1   
9       CSCO  2019-07-01       10698.0            24386.0      -13688.0   
10      WYNN  2015-12-01        1396.3             1585.5        -189.3   
11       CCK  2015-12-01       -5455.0            -3748.0       -1707.0   
12       ROK  2010-09-01        -536.6             -249.0        -287.6   
13       PRU  2011-12-01       80390.0            78477.0        1913.0   
14      CTXS  2017-12-01         684.2              243.2         441.0   
15        TT  2014-12-01         580.9              414.7         166.2   
16        PG  2017-06-01       -6730.0            -4525.0       -2205.0   
17      ATVI  2019-12-01        1955.0              542.0        1413.0   
18       BSX  2015-12-01      -12432.0            -4875.0       -7557.0   
19         J  2017-09-01          20.9             -136.3         157.2   
20        WM  2015-12-01       -1462.0             -787.0        -675.0   
21      FAST  2010-12-01        -216.6              -40.2        -176.5   
22      DLTR  2018-02-01       12840.1             7442.8        5397.3   
23      AMAT  2014-10-01        2231.0             1899.0         332.0   
24       SSP  2015-12-01         -55.0              -10.1         -44.9   
25       MBT  2017-12-01       -4933.9            -2841.4       -2092.6   
26      CINF  2015-12-01        3793.0             2398.0        1395.0   
27       DAR  2011-01-01        -170.1              428.0        -598.1   
28       PNR  2012-12-01        7296.4             2856.3        4440.1   
29       BSX  2013-12-01       -2471.0            -1998.0        -473.0   
...      ...         ...           ...                ...           ...   
4470     LUV  2010-12-01      -10780.0            -7164.0       -3616.0   
4471     HSY  2012-12-01        -602.7              -34.9        -567.7   
4472     USM  2017-12-01        -433.0              -43.0        -390.0   
4473    PEIX  2011-12-01        -442.2             -189.9        -252.2   
4474     CNX  2010-12-01        3478.4             5624.2       -2145.7   
4475     BGS  2016-01-01        -499.9             -171.9        -328.0   
4476     FNF  2017-12-01        1263.5             -103.1        1366.6   
4477     IEX  2017-12-01         244.7              -98.0         342.6   
4478     GPS  2020-02-01        5630.0             5867.0        -237.0   
4479      WU  2012-12-01        -655.6             -491.5        -164.1   
4480     CMI  2018-12-01         987.0              892.0          95.0   
4481    ANSS  2013-12-01         -30.5               50.7         -81.3   
4482     PHM  2012-12-01        -151.2             -402.2         251.0   
4483     OXY  2016-12-01        1083.0              158.0         925.0   
4484     HBI  2016-01-01        1965.9             1576.9         389.0   
4485     DEO  2013-06-01        2927.0             1317.4        1609.6   
4486     IPG  2018-12-01        3135.1             2843.9         291.2   
4487   DGICA  2012-12-01         162.3              142.4          19.9   
4488     BSX  2017-12-01        2018.0             1463.0         555.0   
4489      CB  2014-12-01       -4058.0            -4510.0         452.0   
4490    CTSH  2011-12-01       -1013.7             -112.2        -901.5   
4491     YUM  2013-12-01      

In [3]:
classes = data['Classification'] 
data = data.drop(['Company', 'Time', 'Classification'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")
    
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Classification', classes)
data

Total Assets
Done
Total Liabilities
Done
Total Equity
Done
Total Shares Out. on Filing Date
Done
Book Value / Share
Done
Tangible Book Value
Done
Tangible Book Value Per Share
Done
Total Debt
Done
Net Debt
Done


Total Assets  Total Liabilities  Total Equity  \
0         0.384391           0.384644      0.319589   
1         0.397569           0.394002      0.329956   
2         0.395779           0.388355      0.335122   
3         0.391283           0.387312      0.328356   
4         0.396114           0.390621      0.332339   
5         0.394637           0.389373      0.331476   
6         0.398727           0.394244      0.331739   
7         0.393902           0.389672      0.329663   
8         0.394550           0.389640      0.330913   
9         0.409108           0.430539      0.296459   
10        0.396467           0.392308      0.330459   
11        0.387156           0.383365      0.326637   
12        0.393840           0.389232      0.330212   
13        0.503819           0.521237      0.335755   
14        0.395499           0.390057      0.332047   
15        0.395359           0.390344      0.331355   
16        0.385424           0.382062      0.325382   
17        0.397226           0.390558      0.334495   
18        0.377675           0.381475      0.311902   
19        0.394598           0.389421      0.331332   
20        0.392583           0.388329      0.329236   
21        0.394275           0.389582      0.330492   
22        0.412019           0.402129      0.344531   
23        0.397602           0.392833      0.331773   
24        0.394495           0.389632      0.330823   
25        0.387865           0.384885      0.325665   
26        0.399724           0.393670      0.334450   
27        0.394338           0.390367      0.329430   
28        0.404485           0.394438      0.342120   
29        0.391212           0.386299      0.329745   
...            ...                ...           ...   
4470      0.379920           0.377637      0.321828   
4471      0.393751           0.389591      0.329506   
4472      0.393981           0.389577      0.329954   
4473      0.393969           0.389331      0.330301   
4474      0.399297           0.399080      0.325532   
4475      0.393890           0.389361      0.330110   
4476      0.396287           0.389476      0.334378   
4477      0.394902           0.389485      0.331799   
4478      0.402221           0.399487      0.330339   
4479      0.393679           0.388825      0.330523   
4480      0.395911           0.391145      0.331176   
4481      0.394528           0.389734      0.330732   
4482      0.394364           0.388975      0.331569   
4483      0.396041           0.389914      0.333266   
4484      0.397241           0.392293      0.331916   
4485      0.398547           0.391858      0.334991   
4486      0.398830           0.394418      0.331670   
4487      0.394790           0.389888      0.330986   
4488      0.397312           0.392102      0.332334   
4489      0.389055           0.382087      0.332075   
4490      0.393192           0.389461      0.328666   
4491      0.395060           0.389156      0.332586   
4492      0.394566           0.389640      0.330944   
4493      0.430383           0.418193      0.354437   
4494      0.395298           0.390638      0.330800   
4495      0.394832           0.389607      0.331485   
4496      0.394900           0.389719      0.331444   
4497      0.393852           0.390389      0.328496   
4498      0.394793           0.389692      0.331286   
4499      0.393660           0.389971      0.328768   

      Total Shares Out. on Filing Date  Book Value / Share  \
0                             0.383287            0.194941   
1                             0.383038            0.195027   
2                             0.383505            0.195059   
3                             0.383280            0.194917   
4                             0.383686            0.195026   
5                             0.383287            0.195032   
6                             0.383273            0.195083   
7                             0.382830            0.195024   
8                             0.38334

In [4]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:9] # Parameters
y = NpMatrix[:,9] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.3843908  0.38464394 0.31958913 ... 0.23383148 0.25325652 0.22129353]
 [0.39756893 0.39400199 0.32995648 ... 0.23389478 0.25512158 0.22627232]
 [0.39577927 0.38835514 0.33512201 ... 0.23396904 0.25471341 0.22440896]
 ...
 [0.39385209 0.39038855 0.32849558 ... 0.23390964 0.25597765 0.2274895 ]
 [0.39479319 0.38969236 0.33128564 ... 0.23393109 0.25542369 0.22562593]
 [0.39366047 0.38997104 0.32876761 ... 0.23392779 0.25617428 0.22299259]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 9
Total Number of Training instances: 4500


[0. 1. 0. ... 1. 0. 1.]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 0.0
Total number of y values 4500


In [5]:
RF = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=9, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=25,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [6]:
CV = StratifiedKFold(n_splits=10, random_state=None, shuffle=False)

scores = cross_val_score(RF, X, y, cv = CV) 

print(scores)

print("Mean MAE:", scores.mean())
print("SD of the mean:", scores.std())

[0.70731707 0.6962306  0.72062084 0.66740576 0.73111111 0.70444444
 0.69265033 0.73051225 0.70824053 0.69933185]
Mean MAE: 0.7057864801527141
SD of the mean: 0.018059733769369094
