In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, StratifiedKFold, cross_val_score
from sklearn.svm import SVC

In [22]:
data = pd.read_csv('BSTrend_data.csv')
data

classes = data['Classification'] 
data = data.drop(['Company', 'Time', 'Classification'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")
    
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Classification', classes)
data

# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:9] # Parameters
y = NpMatrix[:,9] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

Total Assets
Done
Total Liabilities
Done
Total Equity
Done
Total Shares Out. on Filing Date
Done
Book Value / Share
Done
Tangible Book Value
Done
Tangible Book Value Per Share
Done
Total Debt
Done
Net Debt
Done
X: [[0.57412675 0.68191239 0.52642218 ... 0.15660121 0.66576035 0.59525398]
 [0.56162183 0.66823206 0.52312694 ... 0.15688709 0.65094776 0.60260052]
 [0.5583857  0.66685155 0.51878735 ... 0.15653233 0.64989047 0.60171398]
 ...
 [0.55809846 0.67046279 0.51237429 ... 0.15644957 0.65595174 0.608092  ]
 [0.56398688 0.67446145 0.51787038 ... 0.15653408 0.66283855 0.61190508]
 [0.56259345 0.67198972 0.51903259 ... 0.15619478 0.65718794 0.60745648]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 9
Total Number of Training instances: 4500


[1. 1. 1. ... 0. 0. 1.]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 1.0
Total number of y values 4500


In [25]:
SVM = SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=1, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [26]:
# 7 minutes to run
CV = StratifiedKFold(n_splits=10, random_state=None, shuffle=False)

scores = cross_val_score(SVM, X, y, cv = CV) 

print(scores)

print("Mean MAE:", scores.mean())
print("SD of the mean:", scores.std())

[0.67405765 0.67405765 0.67555556 0.67555556 0.67555556 0.67555556
 0.67555556 0.67555556 0.67483296 0.67483296]
Mean MAE: 0.6751114556944315
SD of the mean: 0.0005966137550331421
