In [7]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, make_scorer, mean_absolute_error
from sklearn.model_selection import cross_val_score 
from math import sqrt
from sklearn.model_selection import KFold
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

In [8]:
data = pd.read_csv('CF_data.csv')
data

Company        Time  Net Income  Cash from Operations  \
0        YUM  2015-12-01      1283.0                1260.0   
1        VAR  2010-10-01       360.4                 460.8   
2        HRL  2015-10-01       686.1                 992.0   
3        EPD  2010-12-01       320.8                2300.0   
4      EONGY  2010-12-01      7848.5               14864.2   
5         CF  2012-12-01      1848.7                2375.6   
6        BDX  2014-09-01      1185.0                1746.0   
7       BIIB  2013-12-01      1862.3                2345.1   
8       MTRN  2010-12-01        46.4                  31.0   
9        NOC  2010-12-01      2053.0                2453.0   
10        ED  2016-12-01      1245.0                3459.0   
11      FIZZ  2016-04-01        61.2                  80.5   
12       FDP  2010-12-01        62.2                 197.4   
13      BIIB  2012-12-01      1380.0                1879.9   
14       OMC  2012-12-01       998.3                1451.3   
15       ETR  2014-12-01       940.7                3889.6   
16      NLOK  2014-03-01       898.0                1281.0   
17        IT  2018-12-01       122.5                 471.2   
18        MA  2012-12-01      2759.0                2948.0   
19       TXN  2011-12-01      2236.0                3256.0   
20       OXY  2011-12-01      6771.0               12281.0   
21      WLTW  2014-12-01       362.0                 477.0   
22       LLY  2014-12-01      2390.5                4458.4   
23       THS  2010-12-01        90.9                 244.7   
24       PFG  2019-12-01      1394.2                5493.2   
25      PCAR  2018-12-01      2195.1                2992.3   
26        IP  2012-12-01       794.0                2967.0   
27      EBAY  2013-12-01      2856.0                4995.0   
28        BA  2011-12-01      4018.0                4023.0   
29      MNST  2019-12-01      1107.8                1113.8   
...      ...         ...         ...                   ...   
4970       L  2017-12-01      1164.0                2590.0   
4971     PNR  2017-12-01       666.5                 620.2   
4972     TMO  2015-12-01      1975.0                2942.0   
4973     FLS  2019-12-01       253.7                 312.7   
4974     LNC  2013-12-01      1244.0                 799.0   
4975     EOG  2017-12-01      2582.6                4265.3   
4976      BG  2013-12-01       306.0                2225.0   
4977     SCL  2017-12-01       100.8                 198.9   
4978     PGR  2011-12-01      1015.5                1497.9   
4979      VZ  2011-12-01      2404.0               29780.0   
4980    LDOS  2011-01-01       619.0                 714.0   
4981    SPGI  2017-12-01      1496.0                2016.0   
4982     FLS  2013-12-01       485.5                 487.8   
4983     HUM  2018-12-01      1683.0                2173.0   
4984     CMI  2018-12-01      2141.0                2378.0   
4985     LKQ  2016-12-01       464.0                 635.0   
4986     TAC  2010-12-01       257.4                 856.6   
4987     DPZ  2016-01-01       192.8                 291.8   
4988     ETR  2012-12-01       846.7                2940.3   
4989     LLY  2017-12-01      -204.1                5615.6   
4990     DIS  2012-09-01      5682.0                7966.0   
4991     HHS  2018-12-01        17.6                  -9.2   
4992    BIDU  2011-12-01      1053.1                1297.4   
4993     PPG  2011-12-01      1095.0                1436.0   
4994     BIP  2011-01-01       297.0                  78.0   
4995     GPK  2013-12-01       146.6                 458.0   
4996    SOHU  2014-12-01      -166.7                 152.3   
4997     YUM  2016-12-01      1643.0                1248.0   
4998     BMY  2013-12-01      2563.0                3545.0   
4999     JCI  2017-09-01      1611.0                 100.0   

      Cash from Investing  Cash from Financing  Net Change in Cash  \
0                  -199.0              -1089.0               -28.0   
1                   

In [9]:
prices = data['Price'] 
data = data.drop(['Company', 'Time', 'Price'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")

Net Income
Done
Cash from Operations
Done
Cash from Investing
Done
Cash from Financing
Done
Net Change in Cash
Done
Levered Free Cash Flow
Done
Unlevered Free Cash Flow
Done
Free Cash Flow / Share
Done


In [10]:
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Price', prices)
data

Net Income  Cash from Operations  Cash from Investing  \
0       0.195162              0.101904             0.584679   
1       0.187545              0.092933             0.585543   
2       0.190234              0.098895             0.579795   
3       0.187218              0.113578             0.563438   
4       0.249369              0.254616             0.593118   
5       0.199833              0.114427             0.582491   
6       0.194353              0.107359             0.579467   
7       0.199945              0.114084             0.574898   
8       0.184952              0.088108             0.585740   
9       0.201519              0.115296             0.580776   
10      0.194848              0.126588             0.551620   
11      0.185074              0.088664             0.585980   
12      0.185083              0.089976             0.585712   
13      0.195963              0.108862             0.579451   
14      0.192811              0.104051             0.583626   
15      0.192336              0.131422             0.565506   
16      0.191983              0.102140             0.582007   
17      0.185581              0.093049             0.588737   
18      0.207348              0.120852             0.566309   
19      0.203030              0.124310             0.543117   
20      0.240472              0.225619             0.517156   
21      0.187558              0.093114             0.584143   
22      0.204306              0.137807             0.558863   
23      0.185320              0.090507             0.579759   
24      0.196080              0.149423             0.532565   
25      0.202693              0.121350             0.572629   
26      0.191125              0.121066             0.552260   
27      0.208149              0.143831             0.544231   
28      0.217743              0.132919             0.602548   
29      0.193715              0.100263             0.583791   
...          ...                   ...                  ...   
4970    0.194179              0.116834             0.567590   
4971    0.190072              0.094722             0.604367   
4972    0.200875              0.120785             0.578458   
4973    0.186664              0.091270             0.585898   
4974    0.194840              0.096729             0.553290   
4975    0.205892              0.135639             0.558318   
4976    0.187096              0.112736             0.583079   
4977    0.185401              0.089993             0.585488   
4978    0.192953              0.104574             0.580881   
4979    0.204417              0.422051             0.466033   
4980    0.189680              0.095775             0.583322   
4981    0.196921              0.110390             0.584610   
4982    0.188578              0.093236             0.584895   
4983    0.198464              0.112153             0.564584   
4984    0.202246              0.114454             0.579286   
4985    0.188400              0.094888             0.574166   
4986    0.186694              0.097376             0.580628   
4987    0.186161              0.091035             0.585303   
4988    0.191560              0.120766             0.560737   
4989    0.182884              0.150797             0.559736   
4990    0.231481              0.177181             0.552949   
4991    0.184714              0.087657             0.586063   
4992    0.193264              0.102324             0.570335   
4993    0.193610              0.103879             0.588520   
4994    0.187021              0.088635             0.586565   
4995    0.185780              0.092901             0.585059   
4996    0.183193              0.089469             0.583013   
4997    0.198134              0.101769             0.586036   
4998    0.205730              0.127554             0.582084   
4999    0.197870              0.088882             0.577387   

      Cash from Financing  Net Change in Cash  Levered Free Cash Flow  \
0                0.668242 

In [11]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:8] # Parameters
y = NpMatrix[:,8] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.19516198 0.10190382 0.58467919 ... 0.45917516 0.45236896 0.00381927]
 [0.18754474 0.09293251 0.58554341 ... 0.4589641  0.45168483 0.00388429]
 [0.19023381 0.09889542 0.57979515 ... 0.46132016 0.4540775  0.00380627]
 ...
 [0.19813425 0.10176912 0.58603606 ... 0.45923792 0.45299671 0.00382891]
 [0.20573002 0.12755377 0.58208374 ... 0.45472016 0.44804477 0.00381687]
 [0.19787004 0.0888824  0.57738688 ... 0.46291752 0.45705425 0.00369453]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 8
Total Number of Training instances: 5000


[52.53 55.98 33.77 ... 63.33 53.15 40.29]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 52.53
Total number of y values 5000


In [12]:
RF = RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=11,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=29,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [13]:
CV = KFold(n_splits=10, random_state=None, shuffle=False)

In [14]:
# Applying k-Fold Cross Validation 
# https://stackoverflow.com/questions/24132237/scikit-learn-cross-validation-scoring-for-regression#:~:text=How%20can%20one%20use%20cross_val_score%20for%20regression%3F%20The,accuracy%2C%20which%20is%20not%20very%20meaningful%20for%20regression.
#mse = make_scorer(mean_squared_error, greater_is_better= False)
mae = make_scorer(mean_absolute_error, greater_is_better= False) 
scores = cross_val_score(RF , X, y, scoring= mae, cv = CV) 

print(scores)

print("Mean MAE:", scores.mean())
print("SD of the mean:", scores.std())

[-29.55417185 -35.40119883 -32.13377479 -33.33966761 -30.75090364
 -36.75992931 -32.75446206 -31.5284779  -33.923741   -32.93882696]
Mean MAE: -32.90851539475682
SD of the mean: 2.017417208949951
