In [12]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, StratifiedKFold, cross_val_score
from sklearn.svm import SVC

In [13]:
data = pd.read_csv('CFTrend_data.csv')
data

classes = data['Classification'] 
data = data.drop(['Company', 'Time', 'Classification'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")
    
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Classification', classes)
data


Net Income
Done
Cash from Operations
Done
Cash from Investing
Done
Cash from Financing
Done
Net Change in Cash
Done
Levered Free Cash Flow
Done
Unlevered Free Cash Flow
Done
Free Cash Flow / Share
Done


Net Income  Cash from Operations  Cash from Investing  \
0       0.480473              0.469643             0.508359   
1       0.481818              0.467858             0.505735   
2       0.481596              0.459018             0.491027   
3       0.481972              0.469780             0.520974   
4       0.480921              0.466917             0.503488   
5       0.480900              0.472130             0.502963   
6       0.483575              0.446902             0.509085   
7       0.483352              0.470616             0.503060   
8       0.481091              0.459393             0.503048   
9       0.481496              0.472081             0.501630   
10      0.480977              0.464770             0.503938   
11      0.480988              0.465443             0.504027   
12      0.474033              0.476715             0.503724   
13      0.481025              0.467483             0.503618   
14      0.482743              0.478575             0.506763   
15      0.481610              0.468429             0.504896   
16      0.480301              0.551484             0.456631   
17      0.478844              0.462536             0.493125   
18      0.481427              0.469020             0.483304   
19      0.479741              0.463241             0.507001   
20      0.481002              0.465582             0.503614   
21      0.481282              0.466595             0.502353   
22      0.480934              0.461407             0.503096   
23      0.485891              0.446902             0.522545   
24      0.481581              0.464750             0.502102   
25      0.433755              0.573627             0.816934   
26      0.480930              0.465011             0.503734   
27      0.484030              0.477410             0.464376   
28      0.481243              0.466895             0.503328   
29      0.481771              0.467109             0.504094   
...          ...                   ...                  ...   
4470    0.480990              0.465133             0.503853   
4471    0.481143              0.461208             0.499374   
4472    0.502066              0.462069             0.512146   
4473    0.484998              0.473463             0.475336   
4474    0.481428              0.466865             0.503661   
4475    0.480908              0.464917             0.503746   
4476    0.484982              0.469367             0.506124   
4477    0.483152              0.471155             0.527229   
4478    0.480952              0.468876             0.471128   
4479    0.481319              0.467553             0.501616   
4480    0.484622              0.473910             0.502209   
4481    0.481316              0.462908             0.505587   
4482    0.481025              0.465882             0.503518   
4483    0.481066              0.465234             0.504384   
4484    0.482375              0.470303             0.528353   
4485    0.476674              0.458023             0.578414   
4486    0.481157              0.465701             0.498897   
4487    0.481123              0.466503             0.503765   
4488    0.481893              0.455466             0.502778   
4489    0.482690              0.464132             0.502719   
4490    0.473954              0.460729             0.482451   
4491    0.445463              0.439159             0.480854   
4492    0.437685              0.345298             0.380527   
4493    0.481803              0.469410             0.498700   
4494    0.491197              0.499801             0.442579   
4495    0.480562              0.460232             0.503615   
4496    0.480618              0.475300             0.504340   
4497    0.472483              0.384639             0.470255   
4498    0.481475              0.467953             0.494898   
4499    0.502981              0.465867             0.509601   

      Cash from Financing  Net Change in Cash  Levered Free Cash Flow  \
0                0.534067 

In [14]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:8] # Parameters
y = NpMatrix[:,8] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.48047315 0.46964303 0.5083592  ... 0.54237545 0.54664551 0.43780199]
 [0.48181768 0.46785821 0.50573495 ... 0.54098301 0.54574138 0.43778649]
 [0.48159606 0.45901847 0.49102705 ... 0.53117487 0.5360744  0.43741059]
 ...
 [0.47248322 0.38463906 0.47025539 ... 0.56701213 0.57357241 0.43757012]
 [0.48147547 0.46795254 0.49489803 ... 0.54175474 0.5464481  0.43774903]
 [0.50298102 0.46586734 0.50960056 ... 0.54332166 0.54786444 0.43779489]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 8
Total Number of Training instances: 4500


[0. 0. 1. ... 1. 1. 1.]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 0.0
Total number of y values 4500


In [15]:
SVM = SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [16]:
# 15 minutes to run
CV = StratifiedKFold(n_splits=10, random_state=None, shuffle=False)

scores = cross_val_score(SVM, X, y, cv = CV) 

print(scores)

print("Mean Accuracy:", scores.mean())
print("SD of the mean:", scores.std())

[0.67184035 0.68957871 0.68       0.68444444 0.68888889 0.67111111
 0.67555556 0.66666667 0.67260579 0.68374165]
Mean Accuracy: 0.6784433174155593
SD of the mean: 0.007603169532775665
