In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, StratifiedKFold

In [2]:
data = pd.read_csv('CFTrend_data.csv')
data

Company        Time  Net Income  Cash from Operations  \
0        VMC  2018-12-01       -85.4                 188.1   
1       ALGN  2018-12-01       168.8                 116.2   
2        OKE  2019-12-01       126.9                -239.9   
3        VFC  2012-12-01       197.9                 193.6   
4       AKAM  2016-12-01        -0.7                  78.3   
5        INT  2012-12-01        -4.7                 288.3   
6         MA  2014-12-01       501.0                -728.0   
7        HFC  2015-12-01       458.8                 227.3   
8       CTAS  2011-05-01        31.4                -224.8   
9       MNST  2017-12-01       108.0                 286.3   
10     DGICA  2016-12-01         9.8                  -8.2   
11       FSM  2012-12-01        12.0                  18.9   
12       CNP  2015-12-01     -1303.0                 473.0   
13       SCL  2015-12-01        18.9                 101.1   
14       CXO  2011-12-01       343.7                 547.9   
15      HSIC  2018-12-01       129.6                 139.2   
16        BA  2012-12-01      -118.0                3485.0   
17       SWK  2013-12-01      -393.5                 -98.2   
18         K  2012-12-01        95.0                 163.0   
19      IPGP  2019-12-01      -223.8                 -69.8   
20      JKHY  2012-06-01        14.5                  24.5   
21       AME  2014-12-01        67.5                  65.3   
22       ATO  2011-09-01         1.8                -143.7   
23      SPGI  2013-12-01       939.0                -728.0   
24       BDX  2017-09-01       124.0                  -9.0   
25      MSFT  2018-06-01     -8918.0                4377.0   
26      CMCL  2017-12-01         0.9                   1.5   
27       UAL  2011-12-01       587.0                 501.0   
28      ABMD  2018-03-01        60.1                  77.4   
29     DISCA  2016-12-01       160.0                  86.0   
...      ...         ...         ...                   ...   
4470     EIG  2016-12-01        12.3                   6.4   
4471     MHK  2017-12-01        41.2                -151.7   
4472     BAX  2016-12-01      3997.0                -117.0   
4473     FDX  2016-05-01       770.0                 342.0   
4474    NFLX  2013-12-01        95.2                  76.2   
4475    REED  2015-12-01        -3.2                  -2.3   
4476      WM  2017-12-01       767.0                 177.0   
4477     CNC  2019-12-01       421.0                 249.0   
4478     MKC  2017-11-01         5.1                 157.2   
4479     AME  2012-12-01        74.6                 103.9   
4480     PPL  2018-12-01       699.0                 360.0   
4481     HBI  2015-01-01        74.0                 -83.2   
4482    STKL  2012-12-01        18.9                  36.6   
4483    JBHT  2019-12-01        26.7                  10.5   
4484      LH  2016-12-01       274.2                 214.7   
4485     DHR  2016-12-01      -803.7                -280.0   
4486    ALXN  2017-12-01        43.9                  29.3   
4487     WAT  2015-12-01        37.5                  61.6   
4488     MMC  2012-12-01       183.0                -383.0   
4489    SINA  2012-12-01       333.8                 -33.9   
4490     IBM  2016-12-01     -1318.0                -171.0   
4491   EONGY  2014-12-01     -6704.6               -1039.9   
4492     BBL  2012-06-01     -8175.0               -4821.0   
4493    MNST  2016-12-01       166.0                 178.7   
4494    CSCO  2013-07-01      1942.0                1403.0   
4495     WDR  2019-12-01       -68.6                -191.0   
4496     KSS  2019-02-01       -58.0                 416.0   
4497   SFTBF  2018-03-01     -1596.0               -3236.2   
4498     DRI  2017-05-01       104.1                 120.0   
4499     NRG  2019-12-01      4170.0                  36.0   

      Cash from Investing  Cash from Financing  Net Change in Cash  \
0                   599.6               -768.5                19.2   
1                   

In [3]:
classes = data['Classification'] 
data = data.drop(['Company', 'Time', 'Classification'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")
    
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Classification', classes)
data

Net Income
Done
Cash from Operations
Done
Cash from Investing
Done
Cash from Financing
Done
Net Change in Cash
Done
Levered Free Cash Flow
Done
Unlevered Free Cash Flow
Done
Free Cash Flow / Share
Done


Net Income  Cash from Operations  Cash from Investing  \
0       0.480473              0.469643             0.508359   
1       0.481818              0.467858             0.505735   
2       0.481596              0.459018             0.491027   
3       0.481972              0.469780             0.520974   
4       0.480921              0.466917             0.503488   
5       0.480900              0.472130             0.502963   
6       0.483575              0.446902             0.509085   
7       0.483352              0.470616             0.503060   
8       0.481091              0.459393             0.503048   
9       0.481496              0.472081             0.501630   
10      0.480977              0.464770             0.503938   
11      0.480988              0.465443             0.504027   
12      0.474033              0.476715             0.503724   
13      0.481025              0.467483             0.503618   
14      0.482743              0.478575             0.506763   
15      0.481610              0.468429             0.504896   
16      0.480301              0.551484             0.456631   
17      0.478844              0.462536             0.493125   
18      0.481427              0.469020             0.483304   
19      0.479741              0.463241             0.507001   
20      0.481002              0.465582             0.503614   
21      0.481282              0.466595             0.502353   
22      0.480934              0.461407             0.503096   
23      0.485891              0.446902             0.522545   
24      0.481581              0.464750             0.502102   
25      0.433755              0.573627             0.816934   
26      0.480930              0.465011             0.503734   
27      0.484030              0.477410             0.464376   
28      0.481243              0.466895             0.503328   
29      0.481771              0.467109             0.504094   
...          ...                   ...                  ...   
4470    0.480990              0.465133             0.503853   
4471    0.481143              0.461208             0.499374   
4472    0.502066              0.462069             0.512146   
4473    0.484998              0.473463             0.475336   
4474    0.481428              0.466865             0.503661   
4475    0.480908              0.464917             0.503746   
4476    0.484982              0.469367             0.506124   
4477    0.483152              0.471155             0.527229   
4478    0.480952              0.468876             0.471128   
4479    0.481319              0.467553             0.501616   
4480    0.484622              0.473910             0.502209   
4481    0.481316              0.462908             0.505587   
4482    0.481025              0.465882             0.503518   
4483    0.481066              0.465234             0.504384   
4484    0.482375              0.470303             0.528353   
4485    0.476674              0.458023             0.578414   
4486    0.481157              0.465701             0.498897   
4487    0.481123              0.466503             0.503765   
4488    0.481893              0.455466             0.502778   
4489    0.482690              0.464132             0.502719   
4490    0.473954              0.460729             0.482451   
4491    0.445463              0.439159             0.480854   
4492    0.437685              0.345298             0.380527   
4493    0.481803              0.469410             0.498700   
4494    0.491197              0.499801             0.442579   
4495    0.480562              0.460232             0.503615   
4496    0.480618              0.475300             0.504340   
4497    0.472483              0.384639             0.470255   
4498    0.481475              0.467953             0.494898   
4499    0.502981              0.465867             0.509601   

      Cash from Financing  Net Change in Cash  Levered Free Cash Flow  \
0                0.534067 

In [5]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:8] # Parameters
y = NpMatrix[:,8] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.48047315 0.46964303 0.5083592  ... 0.54237545 0.54664551 0.43780199]
 [0.48181768 0.46785821 0.50573495 ... 0.54098301 0.54574138 0.43778649]
 [0.48159606 0.45901847 0.49102705 ... 0.53117487 0.5360744  0.43741059]
 ...
 [0.47248322 0.38463906 0.47025539 ... 0.56701213 0.57357241 0.43757012]
 [0.48147547 0.46795254 0.49489803 ... 0.54175474 0.5464481  0.43774903]
 [0.50298102 0.46586734 0.50960056 ... 0.54332166 0.54786444 0.43779489]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 8
Total Number of Training instances: 4500


[0. 0. 1. ... 1. 1. 1.]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 0.0
Total number of y values 4500


In [6]:
# Grid Search for Optimal KNN Hyperparameters
# Using GridSearchCV to find best parameters
kvals = range(1,100)
params = {'n_neighbors': kvals,
        'weights' : ['uniform', 'distance'],
         'metric' : ['euclidean', 'manhattan']}

knn = KNeighborsClassifier()
cv_str = StratifiedKFold(n_splits=5)

gs_modelKNN = GridSearchCV(knn, params,  cv= cv_str)
grid_results = gs_modelKNN.fit(X , y)

# Best parameters, best test score using these parameters, optimal KNN Configuration
print("Best Parameters", gs_modelKNN.best_params_)
print("Best score on Test Data", gs_modelKNN.best_score_)
print("Optimal Configuration", gs_modelKNN.best_estimator_)

Best Parameters {'metric': 'manhattan', 'n_neighbors': 54, 'weights': 'distance'}
Best score on Test Data 0.6846666666666666
Optimal Configuration KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='manhattan',
                     metric_params=None, n_jobs=None, n_neighbors=54, p=2,
                     weights='distance')


In [7]:
# Summarize the results in a readable format
print("Best: {0}, using {1}".format(grid_results.cv_results_['mean_test_score'], grid_results.best_params_))
results_df = pd.DataFrame(grid_results.cv_results_)
results_df

Best: [0.58844444 0.58844444 0.52777778 0.58844444 0.62533333 0.62333333
 0.57955556 0.624      0.63355556 0.63177778 0.60955556 0.63644444
 0.646      0.64511111 0.63511111 0.65111111 0.658      0.65466667
 0.64022222 0.65711111 0.65888889 0.66088889 0.65422222 0.66533333
 0.666      0.66466667 0.65911111 0.66511111 0.66977778 0.66844444
 0.664      0.67155556 0.67311111 0.67288889 0.66711111 0.67422222
 0.67755556 0.67555556 0.66844444 0.67688889 0.67822222 0.678
 0.67288889 0.68044444 0.67977778 0.68066667 0.67488889 0.68177778
 0.67866667 0.67955556 0.67444444 0.67888889 0.68111111 0.68155556
 0.67755556 0.68244444 0.68       0.68022222 0.67822222 0.682
 0.67911111 0.68022222 0.67911111 0.68288889 0.682      0.68066667
 0.68044444 0.682      0.68088889 0.68177778 0.68177778 0.68088889
 0.68111111 0.67822222 0.67755556 0.67955556 0.67822222 0.678
 0.67866667 0.68       0.68022222 0.68022222 0.67755556 0.682
 0.68044444 0.68044444 0.67888889 0.68266667 0.68155556 0.68133333
 0.679111

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0         0.003401  2.346988e-03         0.036302        0.013448   
1         0.001795  3.988984e-04         0.012567        0.001492   
2         0.001795  3.988029e-04         0.032313        0.002053   
3         0.001994  3.371748e-07         0.013963        0.001892   
4         0.001795  3.993274e-04         0.034511        0.001620   
5         0.002007  2.094124e-05         0.016152        0.002044   
6         0.001992  3.533778e-05         0.035113        0.001720   
7         0.001991  6.280527e-04         0.018140        0.002765   
8         0.001994  2.254789e-06         0.036105        0.001596   
9         0.001794  4.009728e-04         0.017991        0.001852   
10        0.001794  4.001144e-04         0.036702        0.001933   
11        0.001795  3.987318e-04         0.019344        0.001474   
12        0.002178  3.797887e-04         0.041898        0.002432   
13        0.001795  1.162524e-03         0.021345        0.002242   
14        0.002388  4.826364e-04         0.042086        0.006817   
15        0.003587  3.183872e-03         0.024147        0.004517   
16        0.001804  4.036436e-04         0.041081        0.002715   
17        0.001983  3.938098e-05         0.022361        0.001624   
18        0.001994  3.893164e-06         0.048541        0.014937   
19        0.001787  3.956046e-04         0.023155        0.003211   
20        0.002004  2.322270e-05         0.041160        0.002684   
21        0.002021  2.595790e-05         0.021912        0.001669   
22        0.001584  4.801518e-04         0.040899        0.002533   
23        0.001979  6.449686e-04         0.023341        0.002239   
24        0.002402  1.015720e-03         0.048660        0.007001   
25        0.002006  2.324795e-05         0.024523        0.001965   
26        0.002006  2.879504e-05         0.042885        0.002443   
27        0.001573  4.890303e-04         0.024421        0.001528   
28        0.002113  4.762040e-04         0.044215        0.002244   
29        0.001795  3.989234e-04         0.024532        0.001956   
..             ...           ...              ...             ...   
366       0.001810  4.062960e-04         0.064436        0.002160   
367       0.002221  3.859055e-04         0.050157        0.002716   
368       0.002007  1.999421e-05         0.065228        0.001495   
369       0.002009  1.675226e-05         0.049885        0.001766   
370       0.001790  4.150612e-04         0.066826        0.003040   
371       0.002393  4.884025e-04         0.053058        0.001716   
372       0.001995  1.907349e-07         0.067220        0.002410   
373       0.002194  3.977063e-04         0.053058        0.003534   
374       0.002194  3.989223e-04         0.066023        0.001716   
375       0.001995  4.156970e-07         0.051063        0.001716   
376       0.001994  3.568323e-07         0.072207        0.006070   
377       0.001795  3.987321e-04         0.052260        0.001954   
378       0.001796  3.991850e-04         0.071213        0.001361   
379       0.002024  1.717633e-05         0.054033        0.002033   
380       0.002233  3.828669e-04         0.069997        0.003651   
381       0.002042  2.405283e-05         0.051078        0.001897   
382       0.002003  2.203349e-05         0.066816        0.001670   
383       0.002017  1.779504e-05         0.053661        0.003516   
384       0.001827  3.860242e-04         0.067799        0.001891   
385       0.001827  3.960782e-04         0.051853        0.001552   
386       0.002508  1.327154e-03         0.068927        0.002160   
387       0.001838  4.015661e-04         0.052647        0.001587   
388       0.001845  3.968067e-04         0.070987        0.002726   
389       0.002017  2.166048e-05         0.054849        0.002774   
390       0.002018  1.887131e-05         0.069207        0.002334   
391       0.001824  3.948362e-04         0.053236        0.001623   
392

In [8]:
results_df = results_df.sort_values(['rank_test_score'])
results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
305       0.002014  2.309507e-05         0.043268        0.001477   
301       0.002605  4.756694e-04         0.050845        0.005945   
300       0.002208  3.896666e-04         0.072318        0.003436   
289       0.002201  3.958407e-04         0.041894        0.002216   
297       0.002213  4.091405e-04         0.047640        0.002557   
243       0.001995  2.431402e-07         0.031117        0.002034   
298       0.002625  7.783552e-04         0.076118        0.017025   
299       0.002295  6.194196e-04         0.042621        0.001477   
304       0.002211  3.763334e-04         0.064418        0.001493   
63        0.001793  3.994036e-04         0.032315        0.003920   
293       0.002297  4.009465e-04         0.050663        0.005966   
87        0.001795  3.990176e-04         0.036502        0.002054   
303       0.002013  2.601950e-05         0.044451        0.002134   
269       0.002194  3.989698e-04         0.038696        0.005549   
181       0.002792  3.985647e-04         0.068018        0.008063   
281       0.001994  1.302385e-06         0.038488        0.002492   
283       0.002800  1.163114e-03         0.048064        0.008096   
105       0.002202  3.961803e-04         0.039686        0.003040   
113       0.001995  6.299973e-04         0.041489        0.002932   
95        0.002202  4.112754e-04         0.041282        0.004223   
321       0.001995  3.015783e-07         0.045877        0.001669   
119       0.002393  4.902790e-04         0.049074        0.004393   
267       0.001994  1.007019e-06         0.035505        0.001954   
369       0.002009  1.675226e-05         0.049885        0.001766   
55        0.002005  2.284423e-05         0.029510        0.001961   
319       0.002194  3.992818e-04         0.051067        0.002032   
101       0.001994  4.264961e-07         0.038098        0.002221   
302       0.002418  4.831732e-04         0.072783        0.006707   
97        0.001995  5.223489e-07         0.037500        0.002410   
265       0.002620  8.007920e-04         0.041671        0.005741   
..             ...           ...              ...             ...   
216       0.001994  8.078978e-06         0.042288        0.001620   
12        0.002178  3.797887e-04         0.041898        0.002432   
13        0.001795  1.162524e-03         0.021345        0.002242   
209       0.001998  5.452232e-06         0.020149        0.001463   
18        0.001994  3.893164e-06         0.048541        0.014937   
212       0.002000  1.560912e-05         0.039478        0.001622   
11        0.001795  3.987318e-04         0.019344        0.001474   
14        0.002388  4.826364e-04         0.042086        0.006817   
206       0.002025  2.633825e-05         0.039874        0.002280   
8         0.001994  2.254789e-06         0.036105        0.001596   
207       0.001798  3.737306e-04         0.020202        0.001731   
9         0.001794  4.009728e-04         0.017991        0.001852   
205       0.002392  4.898903e-04         0.021537        0.003244   
202       0.001994  1.340243e-06         0.036892        0.001427   
203       0.001771  4.158547e-04         0.017377        0.001607   
4         0.001795  3.993274e-04         0.034511        0.001620   
7         0.001991  6.280527e-04         0.018140        0.002765   
5         0.002007  2.094124e-05         0.016152        0.002044   
208       0.001795  3.991373e-04         0.038891        0.001781   
10        0.001794  4.001144e-04         0.036702        0.001933   
198       0.003192  9.769220e-04         0.045079        0.007119   
199       0.002003  1.468705e-05         0.016155        0.001716   
201       0.001994  1.266988e-06         0.016618        0.001514   
3         0.001994  3.371748e-07         0.013963        0.001892   
1         0.001795  3.988984e-04         0.012567        0.001492   
0         0.003401  2.346988e-03         0.036302        0.013448   
204