In [15]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.svm import SVC

In [16]:
data = pd.read_csv('CFTrend_data.csv')
data

classes = data['Classification'] 
data = data.drop(['Company', 'Time', 'Classification'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")
    
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Classification', classes)
data

Net Income
Done
Cash from Operations
Done
Cash from Investing
Done
Cash from Financing
Done
Net Change in Cash
Done
Levered Free Cash Flow
Done
Unlevered Free Cash Flow
Done
Free Cash Flow / Share
Done


Net Income  Cash from Operations  Cash from Investing  \
0       0.480473              0.469643             0.508359   
1       0.481818              0.467858             0.505735   
2       0.481596              0.459018             0.491027   
3       0.481972              0.469780             0.520974   
4       0.480921              0.466917             0.503488   
5       0.480900              0.472130             0.502963   
6       0.483575              0.446902             0.509085   
7       0.483352              0.470616             0.503060   
8       0.481091              0.459393             0.503048   
9       0.481496              0.472081             0.501630   
10      0.480977              0.464770             0.503938   
11      0.480988              0.465443             0.504027   
12      0.474033              0.476715             0.503724   
13      0.481025              0.467483             0.503618   
14      0.482743              0.478575             0.506763   
15      0.481610              0.468429             0.504896   
16      0.480301              0.551484             0.456631   
17      0.478844              0.462536             0.493125   
18      0.481427              0.469020             0.483304   
19      0.479741              0.463241             0.507001   
20      0.481002              0.465582             0.503614   
21      0.481282              0.466595             0.502353   
22      0.480934              0.461407             0.503096   
23      0.485891              0.446902             0.522545   
24      0.481581              0.464750             0.502102   
25      0.433755              0.573627             0.816934   
26      0.480930              0.465011             0.503734   
27      0.484030              0.477410             0.464376   
28      0.481243              0.466895             0.503328   
29      0.481771              0.467109             0.504094   
...          ...                   ...                  ...   
4470    0.480990              0.465133             0.503853   
4471    0.481143              0.461208             0.499374   
4472    0.502066              0.462069             0.512146   
4473    0.484998              0.473463             0.475336   
4474    0.481428              0.466865             0.503661   
4475    0.480908              0.464917             0.503746   
4476    0.484982              0.469367             0.506124   
4477    0.483152              0.471155             0.527229   
4478    0.480952              0.468876             0.471128   
4479    0.481319              0.467553             0.501616   
4480    0.484622              0.473910             0.502209   
4481    0.481316              0.462908             0.505587   
4482    0.481025              0.465882             0.503518   
4483    0.481066              0.465234             0.504384   
4484    0.482375              0.470303             0.528353   
4485    0.476674              0.458023             0.578414   
4486    0.481157              0.465701             0.498897   
4487    0.481123              0.466503             0.503765   
4488    0.481893              0.455466             0.502778   
4489    0.482690              0.464132             0.502719   
4490    0.473954              0.460729             0.482451   
4491    0.445463              0.439159             0.480854   
4492    0.437685              0.345298             0.380527   
4493    0.481803              0.469410             0.498700   
4494    0.491197              0.499801             0.442579   
4495    0.480562              0.460232             0.503615   
4496    0.480618              0.475300             0.504340   
4497    0.472483              0.384639             0.470255   
4498    0.481475              0.467953             0.494898   
4499    0.502981              0.465867             0.509601   

      Cash from Financing  Net Change in Cash  Levered Free Cash Flow  \
0                0.534067 

In [17]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:8] # Parameters
y = NpMatrix[:,8] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.48047315 0.46964303 0.5083592  ... 0.54237545 0.54664551 0.43780199]
 [0.48181768 0.46785821 0.50573495 ... 0.54098301 0.54574138 0.43778649]
 [0.48159606 0.45901847 0.49102705 ... 0.53117487 0.5360744  0.43741059]
 ...
 [0.47248322 0.38463906 0.47025539 ... 0.56701213 0.57357241 0.43757012]
 [0.48147547 0.46795254 0.49489803 ... 0.54175474 0.5464481  0.43774903]
 [0.50298102 0.46586734 0.50960056 ... 0.54332166 0.54786444 0.43779489]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 8
Total Number of Training instances: 4500


[0. 0. 1. ... 1. 1. 1.]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 0.0
Total number of y values 4500


In [19]:
# Takes 1hour, 37 mins to run

# Using GridSearchCV to find best SVM hyperparameters
params = {'C': [0.1, 1, 10, 50, 100, 1000, 10000],
          'gamma': ['scale', 'auto'],# Slack parameter, how much error is allowed in prediction
          #[1,0.1,0.01,0.001], # Determines whether only close points determine hyperplane or those further away
          'kernel': ['linear', 'rbf', 'poly'],
         'degree' : [2,3]} #rnel used
 
cv_str = StratifiedKFold(n_splits=5)
SVM = SVC()

gs_modelSVM = GridSearchCV(SVM, params, cv= cv_str)
grid_results = gs_modelSVM.fit(X , y)

# Best parameters, best test score using these parameters, optimal KNN Configuration
print("Best Parameters", gs_modelSVM.best_params_)
print("Best score on Test Data", gs_modelSVM.best_score_)
print("Optimal Configuration", gs_modelSVM.best_estimator_)

Best Parameters {'C': 10, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'}
Best score on Test Data 0.6806666666666666
Optimal Configuration SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)


In [20]:
# Summarize the results in a readable format
print("Best: {0}, using {1}".format(grid_results.cv_results_['mean_test_score'], grid_results.best_params_))
results_df = pd.DataFrame(grid_results.cv_results_)
results_df

Best: [0.67511111 0.67511111 0.67422222 0.67511111 0.67511111 0.67511111
 0.67511111 0.67511111 0.67844444 0.67511111 0.67511111 0.67511111
 0.67511111 0.67644444 0.67444444 0.67511111 0.67511111 0.67511111
 0.67511111 0.67644444 0.67733333 0.67511111 0.67511111 0.67511111
 0.67511111 0.67711111 0.67688889 0.67511111 0.67511111 0.67511111
 0.67511111 0.67711111 0.68066667 0.67511111 0.67511111 0.67511111
 0.67511111 0.67555556 0.67666667 0.67511111 0.67511111 0.67511111
 0.67511111 0.67555556 0.67577778 0.67511111 0.67511111 0.67511111
 0.67511111 0.674      0.67622222 0.67511111 0.67511111 0.67511111
 0.67511111 0.674      0.67777778 0.67511111 0.67511111 0.67511111
 0.67511111 0.67422222 0.67755556 0.67511111 0.67444444 0.67488889
 0.67511111 0.67422222 0.678      0.67511111 0.67444444 0.67488889
 0.67488889 0.67044444 0.67822222 0.67488889 0.67422222 0.67444444
 0.67488889 0.67044444 0.68       0.67488889 0.67422222 0.67466667], using {'C': 10, 'degree': 3, 'gamma': 'scale', 'kernel

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.148620      0.025487         0.016828        0.001613     0.1   
1        0.587868      0.171586         0.082959        0.019948     0.1   
2        3.013163      1.006851         0.027198        0.004662     0.1   
3        0.153116      0.025274         0.020799        0.002994     0.1   
4        0.391614      0.062341         0.054630        0.008007     0.1   
5        0.233600      0.053124         0.040803        0.012744     0.1   
6        0.257832      0.015554         0.026401        0.005987     0.1   
7        0.363993      0.028873         0.040210        0.000421     0.1   
8       21.058689      1.674886         0.034046        0.018158     0.1   
9        0.133725      0.011839         0.016800        0.001600     0.1   
10       0.417230      0.140020         0.076850        0.020985     0.1   
11       0.321798      0.011296         0.048799        0.001599     0.1   
12       0.189478      0.069737         0.021602        0.009339       1   
13       0.429244      0.014523         0.047673        0.003125       1   
14       7.362485      1.349409         0.031618        0.010458       1   
15       0.136636      0.013777         0.017227        0.001615       1   
16       0.255808      0.010893         0.040426        0.000853       1   
17       0.224009      0.080410         0.031998        0.013146       1   
18       0.273591      0.004068         0.036001        0.000003       1   
19       0.617113      0.203734         0.060807        0.020625       1   
20      44.144342      5.002552         0.032903        0.012619       1   
21       0.148800      0.030503         0.016806        0.001622       1   
22       0.252743      0.009448         0.039039        0.001552       1   
23       0.159196      0.004667         0.023200        0.001600       1   
24       0.174051      0.021292         0.019607        0.001965      10   
25       0.640718      0.029688         0.045214        0.009404      10   
26      15.123431      2.187984         0.024458        0.004064      10   
27       0.349774      0.025997         0.033587        0.001955      10   
28       0.607858      0.181996         0.065814        0.017946      10   
29       0.197259      0.017762         0.024512        0.003396      10   
..            ...           ...              ...             ...     ...   
54       1.711246      0.216419         0.018559        0.002044     100   
55       1.687066      0.219205         0.039008        0.000469     100   
56     107.737834     17.604549         0.019755        0.001151     100   
57       1.662995      0.144848         0.017960        0.001086     100   
58       0.529622      0.034269         0.047086        0.005581     100   
59       0.319079      0.035586         0.027336        0.003123     100   
60       2.641133      0.392055         0.017547        0.001020    1000   
61       7.649887      0.870482         0.040884        0.003974    1000   
62      65.941540     17.380653         0.020553        0.001004    1000   
63       2.442214      0.378587         0.016965        0.001565    1000   
64       1.163587      0.163715         0.039901        0.001107    1000   
65       0.667757      0.080937         0.023347        0.000793    1000   
66       2.427064      0.366212         0.017548        0.000792    1000   
67       7.638306      0.926947         0.039505        0.000497    1000   
68     113.680578     13.327693         0.019558        0.001729    1000   
69       2.655878      0.381339         0.018556        0.002408    1000   
70       1.501073      0.137785         0.054656        0.009122    1000   
71       0.554770      0.081786         0.024150        0.001613    1000   
72       3.022169      0.256060         0.017153        0.000977   10000   
73      37.363047      4.978701         0.042087        0.005692   10000   
74     100.907010     40.989001         0.020148    

In [21]:
results_df = results_df.sort_values(['rank_test_score'])
results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
32     116.872670     19.644437         0.031192        0.009263      10   
80     154.982501     47.653304         0.021146        0.001989   10000   
8       21.058689      1.674886         0.034046        0.018158     0.1   
74     100.907010     40.989001         0.020148        0.002469   10000   
68     113.680578     13.327693         0.019558        0.001729    1000   
56     107.737834     17.604549         0.019755        0.001151     100   
62      65.941540     17.380653         0.020553        0.001004    1000   
20      44.144342      5.002552         0.032903        0.012619       1   
25       0.640718      0.029688         0.045214        0.009404      10   
31       0.677538      0.080187         0.046404        0.001950      10   
26      15.123431      2.187984         0.024458        0.004064      10   
38      29.570535      2.905905         0.027200        0.010553      50   
13       0.429244      0.014523         0.047673        0.003125       1   
19       0.617113      0.203734         0.060807        0.020625       1   
50      27.694083      2.022021         0.022555        0.000501     100   
44     132.270184     28.565713         0.025964        0.009328      50   
37       1.174447      0.120534         0.040809        0.001600      50   
43       1.575397      0.482502         0.051428        0.015491      50   
42       0.668251      0.213125         0.028000        0.009799      50   
40       0.488267      0.024893         0.045643        0.003506      50   
39       0.460663      0.104029         0.017600        0.001961      50   
45       0.455077      0.105575         0.017916        0.001497      50   
46       0.471638      0.028618         0.042490        0.002051      50   
0        0.148620      0.025487         0.016828        0.001613     0.1   
48       1.553874      0.167831         0.017784        0.001171     100   
52       0.536096      0.011584         0.044277        0.003850     100   
53       0.375191      0.047709         0.026844        0.002573     100   
54       1.711246      0.216419         0.018559        0.002044     100   
57       1.662995      0.144848         0.017960        0.001086     100   
58       0.529622      0.034269         0.047086        0.005581     100   
..            ...           ...              ...             ...     ...   
30       0.182606      0.017128         0.018594        0.001736      10   
29       0.197259      0.017762         0.024512        0.003396      10   
28       0.607858      0.181996         0.065814        0.017946      10   
18       0.273591      0.004068         0.036001        0.000003       1   
27       0.349774      0.025997         0.033587        0.001955      10   
33       0.187192      0.017780         0.018401        0.001961      10   
23       0.159196      0.004667         0.023200        0.001600       1   
22       0.252743      0.009448         0.039039        0.001552       1   
34       0.382521      0.021148         0.043198        0.002993      10   
24       0.174051      0.021292         0.019607        0.001965      10   
78       3.085712      0.270760         0.016764        0.000404   10000   
72       3.022169      0.256060         0.017153        0.000977   10000   
65       0.667757      0.080937         0.023347        0.000793    1000   
81       3.432692      0.220137         0.019423        0.003418   10000   
71       0.554770      0.081786         0.024150        0.001613    1000   
75       3.024420      0.223996         0.017560        0.000793   10000   
83       1.709465      0.103368         0.035495        0.015497   10000   
64       1.163587      0.163715         0.039901        0.001107    1000   
77       2.528594      0.545511         0.025535        0.003189   10000   
14       7.362485      1.349409         0.031618        0.010458       1   
70       1.501073      0.137785         0.054656    