In [18]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, make_scorer, mean_absolute_error
from sklearn.model_selection import GridSearchCV

In [20]:
data = pd.read_csv('IS_data.csv')
data

Company        Time  Total Revenues  Operating Income  Net Income  \
0       CTAS  2019-05-01          6892.3            1147.9       885.0   
1        PGR  2014-12-01         19377.3            2029.1      1281.0   
2        ELP  2018-12-01          3857.8             583.3       363.5   
3        PHM  2016-12-01          7676.5             980.2       602.7   
4          F  2019-12-01        155900.0            2658.0        47.0   
5         WM  2011-12-01         13378.0            2081.0       961.0   
6       SIRI  2019-12-01          7794.0            1756.0       914.0   
7       SCCO  2017-12-01          6654.5            2618.9       728.5   
8        BAX  2017-12-01         10584.0            1510.0       602.0   
9       CTSH  2014-12-01         10263.0            1885.0      1439.0   
10      CCOI  2013-12-01           348.0              46.2        56.7   
11        LB  2011-01-01          9613.0            1290.0       805.0   
12       CPE  2015-12-01           137.5              35.9      -240.1   
13        ES  2010-12-01          4898.2            1032.8       387.9   
14       EIG  2019-12-01           835.9             194.4       157.1   
15       AEP  2010-12-01         14427.0            2956.0      1211.0   
16      NTAP  2016-04-01          5546.0             413.0       229.0   
17       GSS  2017-12-01           315.5              38.2        38.8   
18       TXT  2020-01-01         13630.0            1160.0       815.0   
19      ADBE  2019-11-01         11171.3            3268.1      2951.5   
20       WEC  2016-12-01          7472.3            1682.1       939.0   
21       FLS  2012-12-01          4751.3             658.8       448.3   
22       NOC  2017-12-01         26004.0            4453.0      2869.0   
23       CVS  2011-12-01        107080.0            6331.0      3462.0   
24      CMCL  2016-12-01            59.1              16.3         8.5   
25      ISRG  2017-12-01          3138.2            1062.9       670.9   
26      DXCM  2013-12-01           160.0             -26.4       -29.8   
27       GPS  2011-01-01         14664.0            1976.0      1204.0   
28       PFE  2010-12-01         65165.0           17568.0      8257.0   
29      QCOM  2012-09-01         19121.0            5759.0      6109.0   
...      ...         ...             ...               ...         ...   
4970     SYY  2010-07-01         37243.5            1975.9      1180.0   
4971     ROP  2012-12-01          2993.5             759.8       483.4   
4972     UHS  2018-12-01         10772.3            1228.6       779.7   
4973       T  2017-12-01        160546.0           23995.0     29450.0   
4974    GASS  2010-12-01           111.4              21.8        11.1   
4975     FNF  2011-12-01          4800.0             463.0       369.0   
4976     DEO  2017-06-01         15696.0            4658.0      3467.5   
4977    MNST  2019-12-01          4200.8            1414.2      1107.8   
4978    CENT  2011-09-01          1628.7              85.2        28.3   
4979     CRM  2012-01-01          2266.5             -35.1       -11.6   
4980     OXY  2019-12-01         20393.0            2579.0      -667.0   
4981    SNPS  2015-10-01          2242.2             281.6       225.9   
4982     AAP  2011-12-01          6170.5             664.6       394.7   
4983    ABMD  2014-03-01           183.6               8.4         7.4   
4984   JSAIY  2011-03-01         34225.9            1385.1      1038.0   
4985     PNW  2010-12-01          3189.2             714.9       350.1   
4986    GLUU  2011-12-01            74.0             -20.2       -21.1   
4987    SINA  2015-12-01           880.7              12.2        25.7   
4988     PPL  2017-12-01          7447.0            3068.0      1128.0   
4989     LPX  2017-12-01          2734.0             530.0       390.0   
4990     LOW  2012-02-01         50208.0            3763.0      1839.0   
4991     WST  2013-12-01          1368.4             163.8       112.3   
4992    M

In [21]:
prices = data['Price'] 
data = data.drop(['Company', 'Time', 'Price'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")

Total Revenues
Done
Operating Income
Done
Net Income
Done
Revenue Per Share
Done
Basic EPS
Done
Normalized Basic EPS
Done
Dividend Per Share
Done
EBITA
Done
EBIT
Done
Normalized Net Income
Done


In [22]:
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Price', prices)
data

Total Revenues  Operating Income  Net Income  Revenue Per Share  \
0           0.013132          0.152721    0.191876           0.000414   
1           0.036961          0.159877    0.195145           0.000208   
2           0.007341          0.148136    0.187570           0.000089   
3           0.014629          0.151359    0.189545           0.000143   
4           0.297524          0.164984    0.184957           0.000249   
5           0.025511          0.160299    0.192503           0.000181   
6           0.014853          0.157659    0.192115           0.000010   
7           0.012679          0.164667    0.190584           0.000054   
8           0.020178          0.155661    0.189539           0.000123   
9           0.019566          0.158707    0.196450           0.000107   
10          0.000642          0.143774    0.185037           0.000047   
11          0.018325          0.153875    0.191215           0.000189   
12          0.000240          0.143690    0.182587           0.000012   
13          0.009327          0.151786    0.187772           0.000176   
14          0.001573          0.144978    0.185866           0.000165   
15          0.027513          0.167404    0.194568           0.000191   
16          0.010563          0.146753    0.186460           0.000119   
17          0.000580          0.143709    0.184890           0.000026   
18          0.025992          0.152819    0.191298           0.000375   
19          0.021299          0.169939    0.208938           0.000146   
20          0.014239          0.157059    0.192322           0.000150   
21          0.009046          0.148749    0.188270           0.000192   
22          0.049609          0.179561    0.208256           0.000950   
23          0.204348          0.194812    0.213152           0.000510   
24          0.000091          0.143531    0.184639           0.000035   
25          0.005968          0.152031    0.190108           0.000178   
26          0.000283          0.143185    0.184323           0.000013   
27          0.027965          0.159446    0.194510           0.000146   
28          0.124350          0.286067    0.252741           0.000051   
29          0.036472          0.190167    0.235007           0.000071   
...              ...               ...         ...                ...   
4970        0.071060          0.159445    0.194312           0.000400   
4971        0.005691          0.149569    0.188560           0.000195   
4972        0.020538          0.153376    0.191007           0.000736   
4973        0.306391          0.338260    0.427717           0.000165   
4974        0.000191          0.143576    0.184661           0.000032   
4975        0.009139          0.147159    0.187616           0.000139   
4976        0.029935          0.181226    0.213198           0.000039   
4977        0.007996          0.154884    0.193715           0.000048   
4978        0.003087          0.144091    0.184803           0.000184   
4979        0.004304          0.143114    0.184473           0.000026   
4980        0.038900          0.164343    0.179062           0.000160   
4981        0.004257          0.145686    0.186434           0.000091   
4982        0.011755          0.148796    0.187828           0.000520   
4983        0.000328          0.143467    0.184630           0.000029   
4984        0.065301          0.154647    0.193139           0.000117   
4985        0.006065          0.149205    0.187460           0.000190   
4986        0.000119          0.143235    0.184395           0.000007   
4987        0.001659          0.143498    0.184781           0.000092   
4988        0.014191          0.168314    0.193882           0.000068   
4989        0.005196          0.147703    0.187789           0.000120   
4990        0.095804          0.173958    0.199752           0.000251   
4991        0.002590          0.144729    0.185496           0.000124   
4992        0.173952          0.364190    0.354145           0.0

In [23]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:10] # Parameters
y = NpMatrix[:,10] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.01313249 0.15272091 0.19187598 ... 0.15130826 0.15272091 0.15156246]
 [0.03696098 0.15987705 0.19514547 ... 0.15729821 0.15987705 0.1588236 ]
 [0.00734093 0.14813585 0.18757033 ... 0.14641947 0.14813585 0.14688201]
 ...
 [0.31257509 0.34565004 0.29170268 ... 0.38301227 0.34565004 0.30593264]
 [0.00518902 0.15225639 0.19026601 ... 0.14998432 0.15225639 0.15134751]
 [0.00816982 0.15014171 0.18915389 ... 0.147815   0.15014171 0.14926791]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 10
Total Number of Training instances: 5000


[221.83  26.99   7.83 ...  42.53  50.32  32.35]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 221.83
Total number of y values 5000


In [14]:
#X_train, X_test, y_train, y_test = train_test_split(X , y, test_size = 0.2, random_state = 42) # 42, 56, 66, 87

In [24]:
# Hyperparameter Grid Search
#criterion = {'mse', 'mae'}
#'criterion' : ['mse', 'mae'],
params = {
        'splitter' : ['best', 'random'],
          'max_depth': [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15], 
         }

decision_tree = DecisionTreeRegressor()
#mse = make_scorer(mean_squared_error, greater_is_better= False)
mae = make_scorer(mean_absolute_error, greater_is_better= False)

#gs_decision_tree = GridSearchCV(decision_tree, params, scoring = mae,  cv=10)
gs_decision_tree = GridSearchCV(decision_tree, params, scoring = mae,  cv=5)
grid_results = gs_decision_tree.fit(X , y)

# Best parameters, best test score using these parameters, optimal KNN Configuration
print("Best Parameters", gs_decision_tree.best_params_)
print("Best score on Test Data", gs_decision_tree.best_score_)
print("Optimal Configuration", gs_decision_tree.best_estimator_)

Best Parameters {'max_depth': 8, 'splitter': 'best'}
Best score on Test Data -30.746962786725046
Optimal Configuration DecisionTreeRegressor(criterion='mse', max_depth=8, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')


In [25]:
# Summarize the results in a readable format
print("Best: {0}, using {1}".format(grid_results.cv_results_['mean_test_score'], grid_results.best_params_))
results_df = pd.DataFrame(grid_results.cv_results_)
results_df

Best: [-50.31694595 -52.36243234 -42.10436182 -51.38335443 -35.78842427
 -51.94442696 -33.45952983 -49.70917488 -31.70152225 -48.09595372
 -30.76163215 -38.59118927 -30.92194839 -42.82965176 -30.74696279
 -37.33691526 -31.28285756 -39.66921323 -30.92968132 -33.81409326
 -31.89811139 -34.89639372 -31.89580729 -34.7264889  -32.22923586
 -32.27628565 -32.62053666 -32.95268572 -32.6830149  -32.30640276], using {'max_depth': 8, 'splitter': 'best'}


mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.019173      0.005297         0.001599        0.001958   
1        0.002398      0.001958         0.001598        0.001957   
2        0.014219      0.007202         0.001598        0.001957   
3        0.000798      0.001597         0.000000        0.000000   
4        0.012783      0.001598         0.000799        0.001598   
5        0.001598      0.001957         0.000000        0.000000   
6        0.013997      0.001770         0.000799        0.001598   
7        0.002397      0.001957         0.000000        0.000000   
8        0.032030      0.019119         0.000800        0.001599   
9        0.002957      0.004210         0.000799        0.001598   
10       0.021997      0.001799         0.000799        0.001598   
11       0.002458      0.003143         0.000799        0.001598   
12       0.021806      0.001814         0.000000        0.000000   
13       0.002397      0.001958         0.000799        0.001598   
14       0.025569      0.001939         0.000806        0.001612   
15       0.003984      0.000020         0.000000        0.000000   
16       0.031329      0.001839         0.000000        0.000000   
17       0.003995      0.000022         0.000000        0.000000   
18       0.044216      0.009231         0.001599        0.001958   
19       0.003982      0.000020         0.000801        0.001603   
20       0.034649      0.001683         0.000000        0.000000   
21       0.003196      0.002989         0.000800        0.001599   
22       0.034593      0.003064         0.000000        0.000000   
23       0.004805      0.001574         0.000790        0.001580   
24       0.035154      0.002961         0.000799        0.001598   
25       0.003195      0.001598         0.000800        0.001599   
26       0.040036      0.001303         0.000000        0.000000   
27       0.004529      0.001068         0.000802        0.001604   
28       0.052343      0.012687         0.001599        0.001958   
29       0.005585      0.001946         0.000805        0.001611   

   param_max_depth param_splitter                                   params  \
0                1           best     {'max_depth': 1, 'splitter': 'best'}   
1                1         random   {'max_depth': 1, 'splitter': 'random'}   
2                2           best     {'max_depth': 2, 'splitter': 'best'}   
3                2         random   {'max_depth': 2, 'splitter': 'random'}   
4                3           best     {'max_depth': 3, 'splitter': 'best'}   
5                3         random   {'max_depth': 3, 'splitter': 'random'}   
6                4           best     {'max_depth': 4, 'splitter': 'best'}   
7                4         random   {'max_depth': 4, 'splitter': 'random'}   
8                5           best     {'max_depth': 5, 'splitter': 'best'}   
9                5         random   {'max_depth': 5, 'splitter': 'random'}   
10               6           best     {'max_depth': 6, 'splitter': 'best'}   
11               6         random   {'max_depth': 6, 'splitter': 'random'}   
12               7           best     {'max_depth': 7, 'splitter': 'best'}   
13               7         random   {'max_depth': 7, 'splitter': 'random'}   
14               8           best     {'max_depth': 8, 'splitter': 'best'}   
15               8         random   {'max_depth': 8, 'splitter': 'random'}   
16               9           best     {'max_depth': 9, 'splitter': 'best'}   
17               9         random   {'max_depth': 9, 'splitter': 'random'}   
18              10           best    {'max_depth': 10, 'splitter': 'best'}   
19              10         random  {'max_depth': 10, 'splitter': 'random'}   
20              11           best    {'max_depth': 11, 'splitter': 'best'}   
21              11         random  {'max_depth': 11, 'splitter': 'random'}   
22              12           best    {'max_depth': 12, 'splitter': 'best'}   
23              12     

In [26]:
results_df = results_df.sort_values(['rank_test_score'])
results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
14       0.025569      0.001939         0.000806        0.001612   
10       0.021997      0.001799         0.000799        0.001598   
12       0.021806      0.001814         0.000000        0.000000   
18       0.044216      0.009231         0.001599        0.001958   
16       0.031329      0.001839         0.000000        0.000000   
8        0.032030      0.019119         0.000800        0.001599   
22       0.034593      0.003064         0.000000        0.000000   
20       0.034649      0.001683         0.000000        0.000000   
24       0.035154      0.002961         0.000799        0.001598   
25       0.003195      0.001598         0.000800        0.001599   
29       0.005585      0.001946         0.000805        0.001611   
26       0.040036      0.001303         0.000000        0.000000   
28       0.052343      0.012687         0.001599        0.001958   
27       0.004529      0.001068         0.000802        0.001604   
6        0.013997      0.001770         0.000799        0.001598   
19       0.003982      0.000020         0.000801        0.001603   
23       0.004805      0.001574         0.000790        0.001580   
21       0.003196      0.002989         0.000800        0.001599   
4        0.012783      0.001598         0.000799        0.001598   
15       0.003984      0.000020         0.000000        0.000000   
11       0.002458      0.003143         0.000799        0.001598   
17       0.003995      0.000022         0.000000        0.000000   
2        0.014219      0.007202         0.001598        0.001957   
13       0.002397      0.001958         0.000799        0.001598   
9        0.002957      0.004210         0.000799        0.001598   
7        0.002397      0.001957         0.000000        0.000000   
0        0.019173      0.005297         0.001599        0.001958   
3        0.000798      0.001597         0.000000        0.000000   
5        0.001598      0.001957         0.000000        0.000000   
1        0.002398      0.001958         0.001598        0.001957   

   param_max_depth param_splitter                                   params  \
14               8           best     {'max_depth': 8, 'splitter': 'best'}   
10               6           best     {'max_depth': 6, 'splitter': 'best'}   
12               7           best     {'max_depth': 7, 'splitter': 'best'}   
18              10           best    {'max_depth': 10, 'splitter': 'best'}   
16               9           best     {'max_depth': 9, 'splitter': 'best'}   
8                5           best     {'max_depth': 5, 'splitter': 'best'}   
22              12           best    {'max_depth': 12, 'splitter': 'best'}   
20              11           best    {'max_depth': 11, 'splitter': 'best'}   
24              13           best    {'max_depth': 13, 'splitter': 'best'}   
25              13         random  {'max_depth': 13, 'splitter': 'random'}   
29              15         random  {'max_depth': 15, 'splitter': 'random'}   
26              14           best    {'max_depth': 14, 'splitter': 'best'}   
28              15           best    {'max_depth': 15, 'splitter': 'best'}   
27              14         random  {'max_depth': 14, 'splitter': 'random'}   
6                4           best     {'max_depth': 4, 'splitter': 'best'}   
19              10         random  {'max_depth': 10, 'splitter': 'random'}   
23              12         random  {'max_depth': 12, 'splitter': 'random'}   
21              11         random  {'max_depth': 11, 'splitter': 'random'}   
4                3           best     {'max_depth': 3, 'splitter': 'best'}   
15               8         random   {'max_depth': 8, 'splitter': 'random'}   
11               6         random   {'max_depth': 6, 'splitter': 'random'}   
17               9         random   {'max_depth': 9, 'splitter': 'random'}   
2                2           best     {'max_depth': 2, 'splitter': 'best'}   
13               7     