In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsRegressor 
from sklearn.metrics import mean_squared_error, make_scorer, mean_absolute_error
from sklearn.model_selection import GridSearchCV

In [2]:
data = pd.read_csv('DeltaMF_data.csv')
data

Company        Time  Total Assets  Total Liabilities  Total Equity  \
0        SAM  2013-12-01          84.6               27.6          57.0   
1        CMS  2019-12-01        2308.0             2045.0         263.0   
2        HON  2019-12-01         906.0              558.0         348.0   
3       FFIV  2011-09-01         206.3              104.6         101.7   
4        CCL  2018-11-01        1623.0             1396.0         227.0   
5        NEE  2017-12-01        7970.0             3770.0        4200.0   
6        DOV  2014-12-01       -1824.9             -148.2       -1676.7   
7        AGI  2019-12-01         124.3               31.3          93.0   
8         RL  2017-04-01        -561.1             -117.2        -443.9   
9         IP  2013-12-01        -625.0            -2436.0        1811.0   
10       LNC  2016-12-01        9719.0             8858.0         861.0   
11      TSCO  2012-12-01         112.0               95.3          16.7   
12       GTN  2014-12-01         537.2              495.0          42.2   
13       AZO  2013-08-01         626.5              765.7        -139.3   
14      CTXS  2017-12-01        -570.0             1046.2       -1616.2   
15       HPQ  2014-10-01       -2470.0            -1941.0        -529.0   
16        ED  2017-12-01        -144.0            -1263.0        1119.0   
17       NEE  2014-12-01        5299.0             3171.0        2128.0   
18      HAIN  2016-06-01         -91.3              -28.1         -63.2   
19       ROK  2012-09-01         351.6              247.9         103.7   
20       AEE  2015-12-01        1351.0             1118.0         233.0   
21       CMI  2013-12-01        2180.0             1284.0         896.0   
22       AUY  2017-12-01         -38.4               94.3        -132.7   
23      QCOM  2013-09-01        2504.0              -38.0        2542.0   
24       KMX  2020-02-01        2364.3             1952.5         411.9   
25      XLNX  2019-03-01          90.8             -410.4         501.1   
26         F  2011-12-01       13661.0            -2052.0       15713.0   
27      GILD  2015-12-01       17052.0            13771.0        3281.0   
28       DTE  2017-12-01        1726.0             1235.0         491.0   
29       ASH  2013-09-01        -436.0             -960.0         524.0   
...      ...         ...           ...                ...           ...   
4470   JSAIY  2019-03-01        5989.4             6123.5        -134.1   
4471     ADP  2015-06-01        1050.7             2912.4       -1861.7   
4472     SHW  2018-12-01        -765.2             -848.0          82.8   
4473     AME  2015-12-01         239.5              224.4          15.0   
4474     CXO  2013-12-01        1001.8              710.0         291.7   
4475      PH  2018-06-01        -169.8             -768.0         598.2   
4476     XRX  2012-12-01        -101.0              260.0        -361.0   
4477     SJM  2014-04-01          28.4              147.6        -119.2   
4478      GE  2016-12-01     -127888.0          -105294.0      -22594.0   
4479     PFG  2018-12-01      -10905.1            -9729.1       -1176.0   
4480    ORCL  2016-05-01        1277.0             2585.0       -1308.0   
4481    FFIV  2019-09-01         784.8              308.8         476.0   
4482     HRB  2017-04-01        -153.1              -69.1         -84.0   
4483    JBHT  2019-12-01         379.3              213.5         165.6   
4484     OXY  2013-12-01        5233.0             1909.0        3324.0   
4485     ICE  2011-12-01        9505.6             9160.0         345.5   
4486     TAP  2018-12-01        -137.1             -685.6         548.5   
4487    IPGP  2012-12-01         287.4               34.2         253.2   
4488     XRX  2011-12-01        -484.0             -350.0        -134.0   
4489    CPRT  2013-07-01         180.5              -20.8         201.3   
4490     MTD  2013-12-01         130.5               22.7         107.9   
4491     XOM  2012-12-01      

In [3]:
prices = data['Price_Change'] 
data = data.drop(['Company', 'Time', 'Price_Change'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")

Total Assets
Done
Total Liabilities
Done
Total Equity
Done
Total Shares Out. on Filing Date
Done
Book Value / Share
Done
Tangible Book Value
Done
Tangible Book Value Per Share
Done
Total Debt
Done
Net Debt
Done
Total Revenues
Done
Operating Income
Done
Revenue Per Share
Done
Basic EPS
Done
Normalized Basic EPS
Done
Dividend Per Share
Done
EBITA
Done
EBIT
Done
Normalized Net Income
Done
Net Income
Done
Cash from Operations
Done
Cash from Investing
Done
Cash from Financing
Done
Net Change in Cash
Done
Levered Free Cash Flow
Done
Unlevered Free Cash Flow
Done
Free Cash Flow / Share
Done


In [4]:
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Price_Change', prices)
data

Total Assets  Total Liabilities  Total Equity  \
0         0.558733           0.667560      0.518349   
1         0.565675           0.675479      0.519654   
2         0.561298           0.669642      0.520193   
3         0.559113           0.667862      0.518632   
4         0.563536           0.672931      0.519426   
5         0.583353           0.682250      0.544603   
6         0.552771           0.666870      0.507362   
7         0.558857           0.667575      0.518577   
8         0.556717           0.666992      0.515175   
9         0.556518           0.657890      0.529464   
10        0.588813           0.702222      0.523444   
11        0.558819           0.667826      0.518093   
12        0.560146           0.669395      0.518255   
13        0.560425           0.670457      0.517105   
14        0.556689           0.671558      0.507746   
15        0.550757           0.659833      0.514635   
16        0.558019           0.662494      0.525079   
17        0.575013           0.679899      0.531473   
18        0.558184           0.667341      0.517587   
19        0.559567           0.668425      0.518645   
20        0.562687           0.671840      0.519464   
21        0.565275           0.672492      0.523666   
22        0.558349           0.667822      0.517147   
23        0.566287           0.667303      0.534096   
24        0.565851           0.675116      0.520598   
25        0.558753           0.665841      0.521163   
26        0.601121           0.659397      0.617561   
27        0.611708           0.721507      0.538779   
28        0.563858           0.672299      0.521099   
29        0.557108           0.663683      0.521308   
...            ...                ...           ...   
4470      0.577169           0.691488      0.517138   
4471      0.561750           0.678884      0.506190   
4472      0.556080           0.664123      0.518512   
4473      0.559217           0.668333      0.518083   
4474      0.561597           0.670239      0.519836   
4475      0.557939           0.664437      0.521778   
4476      0.558154           0.668472      0.515700   
4477      0.558558           0.668031      0.517232   
4478      0.159181           0.254145      0.374809   
4479      0.524421           0.629262      0.510535   
4480      0.562456           0.677599      0.509699   
4481      0.560919           0.668664      0.521004   
4482      0.557991           0.667180      0.517455   
4483      0.559653           0.668290      0.519037   
4484      0.574807           0.674945      0.539052   
4485      0.588147           0.703407      0.520177   
4486      0.558041           0.664761      0.521463   
4487      0.559366           0.667586      0.519592   
4488      0.556958           0.666078      0.517138   
4489      0.559033           0.667370      0.519263   
4490      0.558877           0.667541      0.518671   
4491      0.567033           0.635371      0.587162   
4492      0.558001           0.667268      0.517333   
4493      0.518349           0.658655      0.450758   
4494      0.555684           0.662109      0.520960   
4495      0.547004           0.662722      0.502354   
4496      0.557675           0.666560      0.517817   
4497      0.526260           0.639374      0.497944   
4498      0.560891           0.668654      0.520963   
4499      0.558660           0.669171      0.515599   

      Total Shares Out. on Filing Date  Book Value / Share  \
0                             0.206256            0.001096   
1                             0.206277            0.001025   
2                             0.205553            0.001029   
3                             0.206196            0.001037   
4                             0.205319            0.001035   
5                             0.206392            0.001169   
6                             0.205958            0.000824   
7                             0.206354            0.001011   
8                             0.20617

In [5]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:26] # Parameters
y = NpMatrix[:,26] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.5587332  0.66756006 0.51834883 ... 0.54024647 0.54501042 0.43755785]
 [0.56567503 0.67547888 0.51965425 ... 0.54099377 0.54593977 0.43772771]
 [0.56129775 0.66964202 0.5201929  ... 0.53644599 0.54120814 0.4377697 ]
 ...
 [0.52626043 0.63937353 0.49794427 ... 0.57679926 0.58110907 0.44130202]
 [0.56089124 0.66865403 0.52096285 ... 0.53194171 0.53674037 0.43735956]
 [0.55865951 0.66917098 0.51559856 ... 0.54612999 0.55081934 0.43800221]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 26
Total Number of Training instances: 4500


[107.34  13.19  44.88 ... -28.45  57.36   9.56]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 107.34
Total number of y values 4500


In [6]:
# Grid Search for Optimal KNN Hyperparameters
# Using GridSearchCV to find best parameters
kvals = range(1,100)
params = {'n_neighbors': kvals,
        'weights' : ['uniform', 'distance'],
         'metric' : ['euclidean', 'manhattan']}

knn = KNeighborsRegressor()
#mse = make_scorer(mean_squared_error, greater_is_better= False)
mae = make_scorer(mean_absolute_error, greater_is_better= False)

gs_modelKNN = GridSearchCV(knn, params, scoring = mae,  cv=5)
grid_results = gs_modelKNN.fit(X , y)

# Best parameters, best test score using these parameters, optimal KNN Configuration
print("Best Parameters", gs_modelKNN.best_params_)
print("Best score on Test Data", gs_modelKNN.best_score_)
print("Optimal Configuration", gs_modelKNN.best_estimator_)

Best Parameters {'metric': 'manhattan', 'n_neighbors': 99, 'weights': 'distance'}
Best score on Test Data -15.497326547994136
Optimal Configuration KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='manhattan',
                    metric_params=None, n_jobs=None, n_neighbors=99, p=2,
                    weights='distance')


In [7]:
# Summarize the results in a readable format
print("Best: {0}, using {1}".format(grid_results.cv_results_['mean_test_score'], grid_results.best_params_))
results_df = pd.DataFrame(grid_results.cv_results_)
results_df

Best: [-21.97537556 -21.97537556 -19.77688    -19.69977256 -18.63717926
 -18.60449714 -17.88556722 -17.89387187 -17.57974622 -17.50970097
 -17.49811    -17.40963105 -17.29667206 -17.21250569 -17.0760925
 -17.01671058 -16.94339753 -16.87895578 -16.84008644 -16.78077566
 -16.78176788 -16.72130651 -16.64675352 -16.60021378 -16.62105385
 -16.57141138 -16.57696143 -16.5278423  -16.54014607 -16.48732978
 -16.47620778 -16.42569767 -16.38847059 -16.34589839 -16.34437481
 -16.30316035 -16.33826842 -16.29444638 -16.29565844 -16.25565217
 -16.27449937 -16.23661986 -16.25085081 -16.21674397 -16.23835681
 -16.20464468 -16.20533944 -16.17404814 -16.19082071 -16.16165608
 -16.17993154 -16.15029782 -16.17329654 -16.1427103  -16.1452469
 -16.11746069 -16.10857042 -16.08495952 -16.09712556 -16.07129307
 -16.09703756 -16.07356954 -16.06854597 -16.04769481 -16.05624747
 -16.03571917 -16.04347203 -16.02433355 -16.03673517 -16.01516652
 -16.04076957 -16.01544041 -16.01663676 -15.99233094 -16.01014719
 -15.9

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0         0.005441      0.002878         0.107063        0.020621   
1         0.004008      0.000013         0.091418        0.007670   
2         0.007194      0.002991         0.127205        0.016084   
3         0.004822      0.001562         0.121040        0.004468   
4         0.004811      0.001618         0.129590        0.020623   
5         0.006411      0.003194         0.153759        0.023451   
6         0.004012      0.000032         0.121240        0.014296   
7         0.004795      0.001606         0.134007        0.017837   
8         0.004012      0.000023         0.130589        0.007250   
9         0.005754      0.002153         0.165377        0.041973   
10        0.009596      0.004085         0.230990        0.021196   
11        0.009078      0.001563         0.227710        0.064140   
12        0.005595      0.001965         0.168956        0.013770   
13        0.004814      0.001619         0.130595        0.018042   
14        0.003994      0.000013         0.112800        0.004884   
15        0.004000      0.000023         0.137594        0.011519   
16        0.004790      0.001612         0.127202        0.013237   
17        0.003830      0.000358         0.114589        0.005402   
18        0.004022      0.000019         0.130553        0.015368   
19        0.004203      0.002225         0.116648        0.007877   
20        0.004000      0.002531         0.124015        0.008394   
21        0.003193      0.001597         0.122347        0.005763   
22        0.004002      0.000002         0.124527        0.013320   
23        0.004812      0.001595         0.129573        0.017237   
24        0.004013      0.002532         0.131194        0.014617   
25        0.004002      0.000003         0.133005        0.013647   
26        0.003988      0.000019         0.129605        0.014868   
27        0.004017      0.000018         0.123190        0.004681   
28        0.004004      0.000012         0.128000        0.007157   
29        0.003997      0.000016         0.120503        0.003738   
..             ...           ...              ...             ...   
366       0.007193      0.002980         0.179550        0.017928   
367       0.004808      0.001595         0.143658        0.008318   
368       0.004000      0.000002         0.144298        0.004911   
369       0.004230      0.000446         0.143083        0.006272   
370       0.003995      0.000028         0.143275        0.008729   
371       0.005610      0.001972         0.153473        0.015561   
372       0.004009      0.000015         0.162256        0.028065   
373       0.004001      0.000002         0.146298        0.011204   
374       0.004793      0.001603         0.145618        0.012812   
375       0.003998      0.000004         0.146386        0.011128   
376       0.004792      0.001603         0.140015        0.004365   
377       0.004797      0.001589         0.145589        0.015306   
378       0.005609      0.001952         0.152478        0.014318   
379       0.004799      0.001607         0.159209        0.028758   
380       0.004000      0.000001         0.143451        0.011066   
381       0.004814      0.001612         0.143408        0.008943   
382       0.006839      0.001605         0.155440        0.011748   
383       0.004003      0.000003         0.147993        0.010449   
384       0.003995      0.000016         0.143200        0.007333   
385       0.004784      0.001606         0.148824        0.009609   
386       0.003991      0.000016         0.157991        0.011019   
387       0.005599      0.001959         0.198780        0.045998   
388       0.004005      0.000030         0.153874        0.010498   
389       0.005215      0.001611         0.172569        0.020157   
390       0.004001      0.000027         0.150132        0.008715   
391       0.003995      0.000005         0.151443        0.007420   
392

In [8]:
results_df = results_df.sort_values(['rank_test_score'])
results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
395       0.005595      0.001956         0.148802        0.014170   
393       0.004013      0.000016         0.154687        0.012234   
391       0.003995      0.000005         0.151443        0.007420   
389       0.005215      0.001611         0.172569        0.020157   
392       0.004814      0.001594         0.185439        0.033148   
394       0.004798      0.001602         0.151204        0.015056   
387       0.005599      0.001959         0.198780        0.045998   
375       0.003998      0.000004         0.146386        0.011128   
377       0.004797      0.001589         0.145589        0.015306   
383       0.004003      0.000003         0.147993        0.010449   
388       0.004005      0.000030         0.153874        0.010498   
390       0.004001      0.000027         0.150132        0.008715   
385       0.004784      0.001606         0.148824        0.009609   
381       0.004814      0.001612         0.143408        0.008943   
373       0.004001      0.000002         0.146298        0.011204   
379       0.004799      0.001607         0.159209        0.028758   
386       0.003991      0.000016         0.157991        0.011019   
371       0.005610      0.001972         0.153473        0.015561   
374       0.004793      0.001603         0.145618        0.012812   
369       0.004230      0.000446         0.143083        0.006272   
382       0.006839      0.001605         0.155440        0.011748   
376       0.004792      0.001603         0.140015        0.004365   
384       0.003995      0.000016         0.143200        0.007333   
372       0.004009      0.000015         0.162256        0.028065   
380       0.004000      0.000001         0.143451        0.011066   
378       0.005609      0.001952         0.152478        0.014318   
365       0.004800      0.001601         0.149029        0.014911   
367       0.004808      0.001595         0.143658        0.008318   
363       0.003995      0.000015         0.140033        0.006968   
361       0.004792      0.001604         0.143458        0.006400   
..             ...           ...              ...             ...   
15        0.004000      0.000023         0.137594        0.011519   
211       0.004009      0.000009         0.118832        0.004671   
210       0.004001      0.000001         0.116756        0.007707   
14        0.003994      0.000013         0.112800        0.004884   
13        0.004814      0.001619         0.130595        0.018042   
209       0.004009      0.000027         0.118380        0.004080   
208       0.003201      0.001601         0.115206        0.007331   
12        0.005595      0.001965         0.168956        0.013770   
11        0.009078      0.001563         0.227710        0.064140   
207       0.004016      0.000017         0.129680        0.023485   
206       0.004003      0.000021         0.123226        0.010809   
10        0.009596      0.004085         0.230990        0.021196   
9         0.005754      0.002153         0.165377        0.041973   
8         0.004012      0.000023         0.130589        0.007250   
205       0.004003      0.000003         0.109589        0.001949   
204       0.004003      0.000002         0.117952        0.005015   
6         0.004012      0.000032         0.121240        0.014296   
7         0.004795      0.001606         0.134007        0.017837   
203       0.004002      0.000001         0.109597        0.005411   
202       0.003995      0.000029         0.116005        0.010746   
5         0.006411      0.003194         0.153759        0.023451   
4         0.004811      0.001618         0.129590        0.020623   
201       0.004802      0.001617         0.115991        0.017143   
200       0.004009      0.000014         0.108798        0.007745   
3         0.004822      0.001562         0.121040        0.004468   
2         0.007194      0.002991         0.127205        0.016084   
198