In [9]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsRegressor 
from sklearn.metrics import mean_squared_error, make_scorer, mean_absolute_error
from sklearn.model_selection import GridSearchCV

In [10]:
data = pd.read_csv('CF_data.csv')
data

Company        Time  Net Income  Cash from Operations  \
0        YUM  2015-12-01      1283.0                1260.0   
1        VAR  2010-10-01       360.4                 460.8   
2        HRL  2015-10-01       686.1                 992.0   
3        EPD  2010-12-01       320.8                2300.0   
4      EONGY  2010-12-01      7848.5               14864.2   
5         CF  2012-12-01      1848.7                2375.6   
6        BDX  2014-09-01      1185.0                1746.0   
7       BIIB  2013-12-01      1862.3                2345.1   
8       MTRN  2010-12-01        46.4                  31.0   
9        NOC  2010-12-01      2053.0                2453.0   
10        ED  2016-12-01      1245.0                3459.0   
11      FIZZ  2016-04-01        61.2                  80.5   
12       FDP  2010-12-01        62.2                 197.4   
13      BIIB  2012-12-01      1380.0                1879.9   
14       OMC  2012-12-01       998.3                1451.3   
15       ETR  2014-12-01       940.7                3889.6   
16      NLOK  2014-03-01       898.0                1281.0   
17        IT  2018-12-01       122.5                 471.2   
18        MA  2012-12-01      2759.0                2948.0   
19       TXN  2011-12-01      2236.0                3256.0   
20       OXY  2011-12-01      6771.0               12281.0   
21      WLTW  2014-12-01       362.0                 477.0   
22       LLY  2014-12-01      2390.5                4458.4   
23       THS  2010-12-01        90.9                 244.7   
24       PFG  2019-12-01      1394.2                5493.2   
25      PCAR  2018-12-01      2195.1                2992.3   
26        IP  2012-12-01       794.0                2967.0   
27      EBAY  2013-12-01      2856.0                4995.0   
28        BA  2011-12-01      4018.0                4023.0   
29      MNST  2019-12-01      1107.8                1113.8   
...      ...         ...         ...                   ...   
4970       L  2017-12-01      1164.0                2590.0   
4971     PNR  2017-12-01       666.5                 620.2   
4972     TMO  2015-12-01      1975.0                2942.0   
4973     FLS  2019-12-01       253.7                 312.7   
4974     LNC  2013-12-01      1244.0                 799.0   
4975     EOG  2017-12-01      2582.6                4265.3   
4976      BG  2013-12-01       306.0                2225.0   
4977     SCL  2017-12-01       100.8                 198.9   
4978     PGR  2011-12-01      1015.5                1497.9   
4979      VZ  2011-12-01      2404.0               29780.0   
4980    LDOS  2011-01-01       619.0                 714.0   
4981    SPGI  2017-12-01      1496.0                2016.0   
4982     FLS  2013-12-01       485.5                 487.8   
4983     HUM  2018-12-01      1683.0                2173.0   
4984     CMI  2018-12-01      2141.0                2378.0   
4985     LKQ  2016-12-01       464.0                 635.0   
4986     TAC  2010-12-01       257.4                 856.6   
4987     DPZ  2016-01-01       192.8                 291.8   
4988     ETR  2012-12-01       846.7                2940.3   
4989     LLY  2017-12-01      -204.1                5615.6   
4990     DIS  2012-09-01      5682.0                7966.0   
4991     HHS  2018-12-01        17.6                  -9.2   
4992    BIDU  2011-12-01      1053.1                1297.4   
4993     PPG  2011-12-01      1095.0                1436.0   
4994     BIP  2011-01-01       297.0                  78.0   
4995     GPK  2013-12-01       146.6                 458.0   
4996    SOHU  2014-12-01      -166.7                 152.3   
4997     YUM  2016-12-01      1643.0                1248.0   
4998     BMY  2013-12-01      2563.0                3545.0   
4999     JCI  2017-09-01      1611.0                 100.0   

      Cash from Investing  Cash from Financing  Net Change in Cash  \
0                  -199.0              -1089.0               -28.0   
1                   

In [11]:
prices = data['Price'] 
data = data.drop(['Company', 'Time', 'Price'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")

Net Income
Done
Cash from Operations
Done
Cash from Investing
Done
Cash from Financing
Done
Net Change in Cash
Done
Levered Free Cash Flow
Done
Unlevered Free Cash Flow
Done
Free Cash Flow / Share
Done


In [12]:
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Price', prices)
data

Net Income  Cash from Operations  Cash from Investing  \
0       0.195162              0.101904             0.584679   
1       0.187545              0.092933             0.585543   
2       0.190234              0.098895             0.579795   
3       0.187218              0.113578             0.563438   
4       0.249369              0.254616             0.593118   
5       0.199833              0.114427             0.582491   
6       0.194353              0.107359             0.579467   
7       0.199945              0.114084             0.574898   
8       0.184952              0.088108             0.585740   
9       0.201519              0.115296             0.580776   
10      0.194848              0.126588             0.551620   
11      0.185074              0.088664             0.585980   
12      0.185083              0.089976             0.585712   
13      0.195963              0.108862             0.579451   
14      0.192811              0.104051             0.583626   
15      0.192336              0.131422             0.565506   
16      0.191983              0.102140             0.582007   
17      0.185581              0.093049             0.588737   
18      0.207348              0.120852             0.566309   
19      0.203030              0.124310             0.543117   
20      0.240472              0.225619             0.517156   
21      0.187558              0.093114             0.584143   
22      0.204306              0.137807             0.558863   
23      0.185320              0.090507             0.579759   
24      0.196080              0.149423             0.532565   
25      0.202693              0.121350             0.572629   
26      0.191125              0.121066             0.552260   
27      0.208149              0.143831             0.544231   
28      0.217743              0.132919             0.602548   
29      0.193715              0.100263             0.583791   
...          ...                   ...                  ...   
4970    0.194179              0.116834             0.567590   
4971    0.190072              0.094722             0.604367   
4972    0.200875              0.120785             0.578458   
4973    0.186664              0.091270             0.585898   
4974    0.194840              0.096729             0.553290   
4975    0.205892              0.135639             0.558318   
4976    0.187096              0.112736             0.583079   
4977    0.185401              0.089993             0.585488   
4978    0.192953              0.104574             0.580881   
4979    0.204417              0.422051             0.466033   
4980    0.189680              0.095775             0.583322   
4981    0.196921              0.110390             0.584610   
4982    0.188578              0.093236             0.584895   
4983    0.198464              0.112153             0.564584   
4984    0.202246              0.114454             0.579286   
4985    0.188400              0.094888             0.574166   
4986    0.186694              0.097376             0.580628   
4987    0.186161              0.091035             0.585303   
4988    0.191560              0.120766             0.560737   
4989    0.182884              0.150797             0.559736   
4990    0.231481              0.177181             0.552949   
4991    0.184714              0.087657             0.586063   
4992    0.193264              0.102324             0.570335   
4993    0.193610              0.103879             0.588520   
4994    0.187021              0.088635             0.586565   
4995    0.185780              0.092901             0.585059   
4996    0.183193              0.089469             0.583013   
4997    0.198134              0.101769             0.586036   
4998    0.205730              0.127554             0.582084   
4999    0.197870              0.088882             0.577387   

      Cash from Financing  Net Change in Cash  Levered Free Cash Flow  \
0                0.668242 

In [13]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:8] # Parameters
y = NpMatrix[:,8] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.19516198 0.10190382 0.58467919 ... 0.45917516 0.45236896 0.00381927]
 [0.18754474 0.09293251 0.58554341 ... 0.4589641  0.45168483 0.00388429]
 [0.19023381 0.09889542 0.57979515 ... 0.46132016 0.4540775  0.00380627]
 ...
 [0.19813425 0.10176912 0.58603606 ... 0.45923792 0.45299671 0.00382891]
 [0.20573002 0.12755377 0.58208374 ... 0.45472016 0.44804477 0.00381687]
 [0.19787004 0.0888824  0.57738688 ... 0.46291752 0.45705425 0.00369453]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 8
Total Number of Training instances: 5000


[52.53 55.98 33.77 ... 63.33 53.15 40.29]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 52.53
Total number of y values 5000


In [14]:
# Grid Search for Optimal KNN Hyperparameters
# Using GridSearchCV to find best parameters
kvals = range(1,100)
params = {'n_neighbors': kvals,
        'weights' : ['uniform', 'distance'],
         'metric' : ['euclidean', 'manhattan']}

knn = KNeighborsRegressor()
#mse = make_scorer(mean_squared_error, greater_is_better= False)
mae = make_scorer(mean_absolute_error, greater_is_better= False)

gs_modelKNN = GridSearchCV(knn, params, scoring = mae,  cv=5)
grid_results = gs_modelKNN.fit(X , y)

# Best parameters, best test score using these parameters, optimal KNN Configuration
print("Best Parameters", gs_modelKNN.best_params_)
print("Best score on Test Data", gs_modelKNN.best_score_)
print("Optimal Configuration", gs_modelKNN.best_estimator_)

Best Parameters {'metric': 'manhattan', 'n_neighbors': 37, 'weights': 'distance'}
Best score on Test Data -48.3164939346198
Optimal Configuration KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='manhattan',
                    metric_params=None, n_jobs=None, n_neighbors=37, p=2,
                    weights='distance')


In [15]:
# Summarize the results in a readable format
print("Best: {0}, using {1}".format(grid_results.cv_results_['mean_test_score'], grid_results.best_params_))
results_df = pd.DataFrame(grid_results.cv_results_)
results_df

Best: [-57.675808   -57.675808   -53.643946   -53.38402253 -52.48603
 -51.96473779 -51.587098   -51.09064105 -50.9425372  -50.41832838
 -50.70895767 -50.19054004 -50.67053714 -50.11749647 -50.62497725
 -50.09957602 -50.74015733 -50.20477922 -50.5037176  -50.00283839
 -50.58813509 -50.06717891 -50.37439733 -49.88588027 -50.28477538
 -49.83303847 -50.26542129 -49.80846748 -50.23781187 -49.78772392
 -50.29532362 -49.80457388 -50.22237129 -49.74326897 -50.16704267
 -49.71779897 -50.29536842 -49.8199742  -50.3860975  -49.88786419
 -50.30484381 -49.85104543 -50.38530227 -49.93237135 -50.40263904
 -49.95844698 -50.43462408 -49.98830891 -50.39192016 -49.96205796
 -50.33457985 -49.90921675 -50.3727263  -49.94415582 -50.37353307
 -49.95990094 -50.27015166 -49.87928416 -50.201125   -49.83467225
 -50.202118   -49.84183405 -50.17158169 -49.81154206 -50.14075818
 -49.78845962 -50.13994971 -49.78360941 -50.12849109 -49.76854576
 -50.11482294 -49.76469294 -50.03575124 -49.70579835 -49.97998063
 -49.66

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0         0.003401      0.001745         0.019181        0.002985   
1         0.002396      0.001957         0.014607        0.002181   
2         0.001591      0.001949         0.019982        0.002528   
3         0.000800      0.001601         0.020212        0.002571   
4         0.002399      0.001959         0.018010        0.001798   
5         0.002405      0.001964         0.019955        0.002548   
6         0.003192      0.001596         0.024770        0.004650   
7         0.001598      0.001957         0.020783        0.003001   
8         0.001598      0.001957         0.019973        0.002528   
9         0.001599      0.001958         0.020771        0.001624   
10        0.003198      0.001599         0.020770        0.001570   
11        0.000799      0.001597         0.024760        0.003007   
12        0.002395      0.001956         0.028762        0.004667   
13        0.002395      0.001956         0.023178        0.001603   
14        0.002401      0.001961         0.025387        0.003803   
15        0.002397      0.001957         0.021811        0.002283   
16        0.001599      0.001958         0.024766        0.002964   
17        0.003436      0.001132         0.021751        0.002559   
18        0.003196      0.001598         0.022591        0.002169   
19        0.002397      0.001957         0.023970        0.002528   
20        0.003185      0.001593         0.031963        0.008389   
21        0.003987      0.000014         0.028723        0.003871   
22        0.001598      0.001957         0.026004        0.001778   
23        0.000799      0.001597         0.025577        0.001940   
24        0.000797      0.001594         0.026658        0.001520   
25        0.002377      0.001941         0.024796        0.001612   
26        0.001602      0.001962         0.026363        0.001959   
27        0.003993      0.000025         0.027154        0.002978   
28        0.003995      0.002526         0.037561        0.012003   
29        0.000000      0.000000         0.027160        0.002952   
..             ...           ...              ...             ...   
366       0.004809      0.001609         0.103162        0.007361   
367       0.004002      0.000015         0.102263        0.005407   
368       0.003993      0.000004         0.101465        0.008201   
369       0.004790      0.001592         0.104663        0.004651   
370       0.004802      0.001594         0.101756        0.007145   
371       0.003987      0.000018         0.109362        0.009482   
372       0.005589      0.001956         0.113090        0.008806   
373       0.005592      0.001942         0.115055        0.008890   
374       0.005591      0.001956         0.099072        0.005313   
375       0.005590      0.001942         0.117525        0.013225   
376       0.004801      0.001591         0.102264        0.005407   
377       0.003195      0.001598         0.065984        0.018173   
378       0.003983      0.000016         0.058326        0.014633   
379       0.001601      0.001961         0.048170        0.002913   
380       0.003194      0.001597         0.052017        0.002409   
381       0.001609      0.001970         0.055371        0.008815   
382       0.003995      0.000002         0.056361        0.011476   
383       0.003208      0.001604         0.050324        0.001946   
384       0.002403      0.001962         0.053520        0.009658   
385       0.002395      0.001956         0.060734        0.009257   
386       0.003203      0.001602         0.066737        0.007445   
387       0.003203      0.001602         0.057744        0.009324   
388       0.001610      0.001972         0.053593        0.003162   
389       0.003985      0.000027         0.058195        0.006451   
390       0.003358      0.001866         0.054093        0.004993   
391       0.003211      0.001606         0.050330        0.003217   
392

In [16]:
results_df = results_df.sort_values(['rank_test_score'])
results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
271       0.004801  1.613188e-03         0.073574        0.002744   
269       0.003988  1.674805e-05         0.072710        0.006380   
267       0.003976  2.514565e-03         0.056732        0.023347   
273       0.006808  1.593303e-03         0.108495        0.033673   
265       0.000807  1.614475e-03         0.037549        0.005396   
261       0.000801  1.601696e-03         0.031944        0.002531   
275       0.003992  2.707159e-05         0.074265        0.009148   
259       0.001598  1.956939e-03         0.036979        0.004137   
245       0.004021  2.913690e-05         0.026232        0.002101   
243       0.001809  1.826875e-03         0.027616        0.003229   
277       0.005593  1.958809e-03         0.067908        0.003573   
247       0.002759  2.338971e-03         0.027478        0.002679   
295       0.001807  1.826593e-03         0.037001        0.001541   
291       0.005025  1.547551e-03         0.075915        0.003582   
279       0.003996  8.844012e-07         0.078292        0.009654   
293       0.003987  1.263897e-05         0.075116        0.009246   
301       0.003207  1.603878e-03         0.041948        0.003583   
313       0.002397  1.956843e-03         0.040182        0.002587   
263       0.004209  4.449995e-04         0.046166        0.001847   
311       0.003993  3.025606e-05         0.041542        0.004074   
281       0.004794  1.596308e-03         0.075900        0.005055   
299       0.001598  1.957523e-03         0.037539        0.003189   
315       0.002397  1.957387e-03         0.039136        0.002973   
249       0.001602  1.961912e-03         0.030344        0.004076   
297       0.003191  1.595720e-03         0.043147        0.006396   
309       0.002396  1.956374e-03         0.040746        0.005873   
307       0.001598  1.957406e-03         0.048161        0.005354   
319       0.001602  1.962498e-03         0.039954        0.002537   
317       0.002395  1.955829e-03         0.046977        0.005392   
303       0.002398  1.957581e-03         0.043951        0.008387   
..             ...           ...              ...             ...   
52        0.000800  1.600742e-03         0.033558        0.003201   
54        0.003202  1.601199e-03         0.031827        0.002554   
22        0.001598  1.956997e-03         0.026004        0.001778   
42        0.003191  1.595534e-03         0.029799        0.001807   
38        0.002397  1.957076e-03         0.027965        0.002521   
48        0.003196  1.598121e-03         0.031162        0.002990   
44        0.002397  1.957075e-03         0.031147        0.002961   
9         0.001599  1.957873e-03         0.020771        0.001624   
46        0.000799  1.598263e-03         0.031169        0.001603   
203       0.004791  1.598580e-03         0.039142        0.004668   
18        0.003196  1.597858e-03         0.022591        0.002169   
20        0.003185  1.592580e-03         0.031963        0.008389   
14        0.002401  1.960610e-03         0.025387        0.003803   
12        0.002395  1.955908e-03         0.028762        0.004667   
10        0.003198  1.599219e-03         0.020770        0.001570   
16        0.001599  1.958165e-03         0.024766        0.002964   
202       0.004794  1.599886e-03         0.034362        0.001947   
8         0.001598  1.957464e-03         0.019973        0.002528   
7         0.001598  1.957114e-03         0.020783        0.003001   
6         0.003192  1.596095e-03         0.024770        0.004650   
5         0.002405  1.963658e-03         0.019955        0.002548   
4         0.002399  1.958636e-03         0.018010        0.001798   
201       0.004801  1.613290e-03         0.031151        0.002987   
3         0.000800  1.600552e-03         0.020212        0.002571   
200       0.005585  1.962857e-03         0.030359        0.003187   
2         0.001591  1.948736e-03         0.019982        0.002528   
198