In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, StratifiedKFold

In [2]:
data = pd.read_csv('ISTrend_data.csv')
data

Company        Time  Total Revenues  Operating Income  Net Income  \
0       AMZN  2019-12-01         47635.0            1983.0      1515.0   
1       TSCO  2018-12-01           654.6              15.3       109.8   
2        AZO  2019-08-01           642.6              81.8       279.7   
3        EQT  2018-12-01          1934.8             221.7     -3753.1   
4       SOHU  2013-12-01           333.1             -57.8       -88.2   
5        DRI  2019-05-01           430.3              81.3       117.4   
6         PH  2017-06-01           668.5             166.3       176.6   
7       VRTX  2011-12-01          1267.2             916.3       784.2   
8        PFG  2014-12-01          1188.1             513.6       231.4   
9       DISH  2012-12-01           107.2            -618.2      -879.2   
10       LPX  2017-12-01           500.6             334.4       240.2   
11       LYV  2011-12-01           320.3              23.2       145.4   
12        ED  2018-12-01           304.0            -247.0      -143.0   
13       LNC  2013-12-01           434.0              35.0       -69.0   
14       HAL  2017-12-01          4733.0            1377.0      5300.0   
15      MSEX  2019-12-01            -3.5              -3.5         1.4   
16       AES  2013-12-01         -1273.0            -282.0      1026.0   
17       MED  2016-12-01             1.7               3.3        -2.3   
18       YUM  2018-12-01          -190.0              16.0       202.0   
19       PKG  2018-12-01           569.7             169.4        69.4   
20        SO  2013-12-01           550.0           -1189.0      -706.0   
21       ELP  2016-12-01           253.5              63.3        -4.8   
22       CAT  2012-12-01          5737.0            1757.0       753.0   
23       XOM  2019-12-01        -23749.0           -9908.0     -6500.0   
24      ORCL  2016-05-01         -1179.0           -1185.0     -1037.0   
25       PVH  2014-02-01          2143.4              73.1      -290.3   
26      MSFT  2017-06-01          5417.0            2143.0      4950.0   
27       SRE  2016-12-01           -48.0            -294.0        21.0   
28      MNST  2015-12-01           257.7             219.5        63.5   
29       PRU  2011-12-01         10846.0             919.0       631.0   
...      ...         ...             ...               ...         ...   
4470     GLW  2014-12-01          1896.0             389.0       511.0   
4471    GASS  2018-12-01            10.0               0.1       -11.1   
4472      BP  2011-12-01         79050.0             514.0     28931.0   
4473    MTRN  2016-12-01           -56.1              -4.4        -6.5   
4474    GPRE  2012-12-01           -76.8             -81.2       -26.6   
4475     HLF  2015-12-01          -489.6              45.6        30.4   
4476    ANSS  2014-12-01            74.7              26.1         9.4   
4477     IVZ  2018-12-01           153.8             -59.4      -244.5   
4478     SEE  2011-12-01           977.2              -4.8      -106.8   
4479    SPGI  2016-12-01           348.0             236.0       950.0   
4480    SCCO  2019-12-01           188.9            -128.2       -57.2   
4481     TIF  2018-01-01           168.0              57.9       -76.0   
4482      KR  2014-02-01          1756.0              -2.0        22.0   
4483     AGI  2014-12-01            60.7              33.1         7.2   
4484     BSX  2012-12-01          -373.0             -73.0     -4509.0   
4485     KSS  2015-01-01            -8.0             -53.0       -22.0   
4486     CNC  2011-12-01           766.3              44.9        16.4   
4487     SJM  2014-04-01          -287.1             -17.4        21.0   
4488     GIS  2017-05-01          -943.3              -7.8       -39.9   
4489    ORCL  2018-05-01          1591.0             413.0     -5865.0   
4490       K  2017-12-01          -111.0              -7.0       555.0   
4491     TFX  2018-12-01           302.1              61.9        48.3   
4492     

In [3]:
classes = data['Classification'] 
data = data.drop(['Company', 'Time', 'Classification'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")

Total Revenues
Done
Operating Income
Done
Net Income
Done
Revenue Per Share
Done
Basic EPS
Done
Normalized Basic EPS
Done
Dividend Per Share
Done
EBITA
Done
EBIT
Done
Normalized Net Income
Done


In [4]:
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Classification', classes)
data

Total Revenues  Operating Income  Net Income  Revenue Per Share  \
0           0.754239          0.212925    0.488938           0.037673   
1           0.553576          0.196357    0.481506           0.032382   
2           0.553525          0.196917    0.482404           0.035705   
3           0.559044          0.198095    0.461074           0.032107   
4           0.552203          0.195741    0.480458           0.032441   
5           0.552618          0.196912    0.481546           0.032132   
6           0.553636          0.197628    0.481859           0.032294   
7           0.556193          0.203943    0.485073           0.032287   
8           0.555855          0.200552    0.482149           0.032149   
9           0.551238          0.191023    0.476275           0.031885   
10          0.552919          0.199043    0.482195           0.032111   
11          0.552148          0.196423    0.481694           0.031807   
12          0.552079          0.194148    0.480168           0.031916   
13          0.552634          0.196523    0.480560           0.032145   
14          0.570996          0.207822    0.508958           0.032229   
15          0.550765          0.196198    0.480932           0.031867   
16          0.545343          0.193853    0.486352           0.031804   
17          0.550788          0.196256    0.480913           0.031914   
18          0.549969          0.196363    0.481993           0.031936   
19          0.553214          0.197654    0.481292           0.032272   
20          0.553130          0.186216    0.477191           0.031923   
21          0.551863          0.196761    0.480899           0.031949   
22          0.575284          0.211022    0.484908           0.032387   
23          0.449344          0.112803    0.446545           0.031531   
24          0.545745          0.186250    0.475440           0.031896   
25          0.559935          0.196843    0.479389           0.032856   
26          0.573917          0.214272    0.507107           0.031953   
27          0.550575          0.193752    0.481036           0.031857   
28          0.551881          0.198076    0.481261           0.031883   
29          0.597106          0.203966    0.484262           0.033195   
...              ...               ...         ...                ...   
4470        0.558879          0.199503    0.483628           0.032023   
4471        0.550823          0.196229    0.480866           0.031905   
4472        0.888419          0.200556    0.633948           0.032153   
4473        0.550541          0.196191    0.480890           0.031727   
4474        0.550452          0.195544    0.480784           0.032794   
4475        0.548689          0.196612    0.481086           0.031782   
4476        0.551099          0.196448    0.480975           0.031947   
4477        0.551437          0.195728    0.479632           0.031909   
4478        0.554954          0.196187    0.480360           0.032172   
4479        0.552267          0.198215    0.485950           0.032018   
4480        0.551587          0.195148    0.480622           0.031905   
4481        0.551498          0.196715    0.480523           0.031987   
4482        0.558281          0.196211    0.481041           0.032216   
4483        0.551040          0.196507    0.480963           0.031980   
4484        0.549187          0.195613    0.457076           0.031896   
4485        0.550746          0.195782    0.480808           0.032303   
4486        0.554053          0.196606    0.481012           0.032096   
4487        0.549554          0.196081    0.481036           0.031865   
4488        0.546751          0.196162    0.480714           0.031822   
4489        0.557576          0.199705    0.449903           0.031914   
4490        0.550306          0.196169    0.483860           0.031883   
4491        0.552071          0.196749    0.481180           0.032271   
4492        0.552379          0.197621    0.482040           0.0

In [5]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:10] # Parameters
y = NpMatrix[:,10] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.75423917 0.21292468 0.48893807 ... 0.21432902 0.21292468 0.24998533]
 [0.55357628 0.19635667 0.48150562 ... 0.19700335 0.19635667 0.23093844]
 [0.55352502 0.1969166  0.48240426 ... 0.1975557  0.1969166  0.23141158]
 ...
 [0.5658876  0.19423231 0.47595825 ... 0.19441591 0.19423231 0.23161008]
 [0.53574144 0.17061424 0.4720971  ... 0.17126114 0.17061424 0.2105595 ]
 [0.55532448 0.19673389 0.48112056 ... 0.19751528 0.19673389 0.23125428]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 10
Total Number of Training instances: 4500


[1. 1. 1. ... 1. 0. 1.]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 1.0
Total number of y values 4500


In [6]:
# Hyperparameter Grid Search

params = {
        'criterion' : ['gini', 'entropy'],
        'splitter' : ['best', 'random'],
          'max_depth': range(1,20), 
         }

decision_tree = DecisionTreeClassifier()

cv_str = StratifiedKFold(n_splits=5)

gs_decision_tree = GridSearchCV(decision_tree, params,  cv= cv_str)
grid_results = gs_decision_tree.fit(X , y)

# Best parameters, best test score using these parameters, optimal KNN Configuration
print("Best Parameters", gs_decision_tree.best_params_)
print("Best score on Test Data", gs_decision_tree.best_score_)
print("Optimal Configuration", gs_decision_tree.best_estimator_)

Best Parameters {'criterion': 'gini', 'max_depth': 4, 'splitter': 'best'}
Best score on Test Data 0.692
Optimal Configuration DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')


In [7]:
# Summarize the results in a readable format
print("Best: {0}, using {1}".format(grid_results.cv_results_['mean_test_score'], grid_results.best_params_))
results_df = pd.DataFrame(grid_results.cv_results_)
results_df

Best: [0.67111111 0.67533333 0.684      0.67666667 0.68333333 0.67666667
 0.692      0.67777778 0.688      0.67977778 0.68333333 0.67911111
 0.68244444 0.67933333 0.67244444 0.68022222 0.66177778 0.67844444
 0.66088889 0.678      0.65511111 0.67711111 0.644      0.67866667
 0.638      0.68333333 0.63444444 0.68288889 0.62955556 0.676
 0.62155556 0.67288889 0.61777778 0.67688889 0.61355556 0.67377778
 0.61511111 0.66088889 0.67177778 0.67622222 0.67911111 0.67711111
 0.68777778 0.674      0.68955556 0.67933333 0.69066667 0.67733333
 0.68688889 0.67533333 0.68577778 0.68066667 0.68155556 0.674
 0.66577778 0.67688889 0.66288889 0.68288889 0.65733333 0.67822222
 0.65111111 0.68       0.65644444 0.67977778 0.64466667 0.67511111
 0.64111111 0.682      0.63333333 0.68533333 0.62222222 0.67511111
 0.63044444 0.68       0.62155556 0.67177778], using {'criterion': 'gini', 'max_depth': 4, 'splitter': 'best'}


mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.003957  5.842775e-04         0.000200        0.000400   
1        0.001211  4.091015e-04         0.000390        0.000478   
2        0.005972  2.115330e-05         0.000609        0.000498   
3        0.000997  2.511443e-06         0.000200        0.000399   
4        0.008577  5.126190e-04         0.000199        0.000398   
5        0.001194  3.698898e-04         0.000202        0.000404   
6        0.011368  4.666048e-04         0.000201        0.000402   
7        0.001208  3.927765e-04         0.000188        0.000376   
8        0.013576  4.752526e-04         0.000399        0.000489   
9        0.001188  4.035716e-04         0.000400        0.000490   
10       0.015788  3.861711e-04         0.000398        0.000488   
11       0.001995  7.835234e-07         0.000000        0.000000   
12       0.020533  2.052321e-03         0.000391        0.000479   
13       0.001608  4.978619e-04         0.000200        0.000400   
14       0.020732  3.946241e-04         0.000200        0.000400   
15       0.001608  4.752598e-04         0.000399        0.000489   
16       0.022338  4.887191e-04         0.000400        0.000490   
17       0.001996  8.920806e-07         0.000398        0.000487   
18       0.024133  3.994167e-04         0.000796        0.000398   
19       0.002387  4.793366e-04         0.000399        0.000488   
20       0.026330  5.174701e-04         0.001005        0.000015   
21       0.002393  4.584092e-04         0.000399        0.000489   
22       0.027929  3.797971e-06         0.000199        0.000398   
23       0.002584  4.969423e-04         0.000207        0.000414   
24       0.029526  4.845765e-04         0.000598        0.000488   
25       0.002991  1.093611e-06         0.000200        0.000400   
26       0.034704  3.624850e-03         0.000594        0.000485   
27       0.003590  4.947719e-04         0.000400        0.000489   
28       0.031725  7.635871e-04         0.000998        0.000002   
29       0.003203  3.916529e-04         0.000399        0.000488   
..            ...           ...              ...             ...   
46       0.020732  4.023427e-04         0.000600        0.000490   
47       0.001396  4.888529e-04         0.000000        0.000000   
48       0.025334  8.160601e-04         0.000398        0.000487   
49       0.000990  1.594206e-05         0.001005        0.000016   
50       0.029744  1.327984e-03         0.000592        0.000483   
51       0.001794  3.988583e-04         0.000592        0.000483   
52       0.035816  2.959577e-03         0.000200        0.000399   
53       0.003392  8.000380e-04         0.000600        0.000490   
54       0.036711  1.178974e-03         0.000207        0.000414   
55       0.002394  4.884926e-04         0.000000        0.000000   
56       0.041488  1.600871e-03         0.000600        0.000490   
57       0.002593  4.871869e-04         0.000190        0.000381   
58       0.044120  2.675452e-03         0.000399        0.000489   
59       0.002186  4.025013e-04         0.000406        0.000498   
60       0.046668  7.395130e-04         0.000199        0.000399   
61       0.002602  4.969671e-04         0.000198        0.000395   
62       0.050182  1.922739e-03         0.000794        0.000398   
63       0.003219  3.884668e-04         0.000383        0.000470   
64       0.051259  1.487452e-03         0.000399        0.000489   
65       0.003567  5.028427e-04         0.000406        0.000498   
66       0.054274  1.000189e-03         0.000581        0.000475   
67       0.003598  4.790158e-04         0.000191        0.000382   
68       0.055474  2.791414e-03         0.000189        0.000379   
69       0.003381  4.972655e-04         0.000608        0.000497   
70       0.055260  4.828800e-04         0.000787        0.000394   
71       0.003392  4.869658e-04         0.000397        0.000487   
72       0.069009  1.103466e-02         0.001001        0.00

In [8]:
results_df = results_df.sort_values(['rank_test_score'])
results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
6        0.011368  4.666048e-04         0.000201        0.000402   
46       0.020732  4.023427e-04         0.000600        0.000490   
44       0.016756  3.990181e-04         0.000407        0.000498   
8        0.013576  4.752526e-04         0.000399        0.000489   
42       0.012776  4.079338e-04         0.000587        0.000480   
48       0.025334  8.160601e-04         0.000398        0.000487   
50       0.029744  1.327984e-03         0.000592        0.000483   
69       0.003381  4.972655e-04         0.000608        0.000497   
2        0.005972  2.115330e-05         0.000609        0.000498   
10       0.015788  3.861711e-04         0.000398        0.000488   
4        0.008577  5.126190e-04         0.000199        0.000398   
25       0.002991  1.093611e-06         0.000200        0.000400   
57       0.002593  4.871869e-04         0.000190        0.000381   
27       0.003590  4.947719e-04         0.000400        0.000489   
12       0.020533  2.052321e-03         0.000391        0.000479   
67       0.003598  4.790158e-04         0.000191        0.000382   
52       0.035816  2.959577e-03         0.000200        0.000399   
51       0.001794  3.988583e-04         0.000592        0.000483   
15       0.001608  4.752598e-04         0.000399        0.000489   
73       0.006182  1.934836e-03         0.000998        0.000631   
61       0.002602  4.969671e-04         0.000198        0.000395   
9        0.001188  4.035716e-04         0.000400        0.000490   
63       0.003219  3.884668e-04         0.000383        0.000470   
45       0.001197  3.968973e-04         0.000199        0.000398   
13       0.001608  4.978619e-04         0.000200        0.000400   
40       0.008700  3.973056e-04         0.000399        0.000489   
11       0.001995  7.835234e-07         0.000000        0.000000   
23       0.002584  4.969423e-04         0.000207        0.000414   
17       0.001996  8.920806e-07         0.000398        0.000487   
59       0.002186  4.025013e-04         0.000406        0.000498   
..            ...           ...              ...             ...   
43       0.001009  2.307941e-05         0.000376        0.000461   
35       0.003808  4.088107e-04         0.000591        0.000483   
31       0.003578  4.812382e-04         0.000411        0.000503   
14       0.020732  3.946241e-04         0.000200        0.000400   
38       0.004595  4.960130e-04         0.000599        0.000489   
75       0.006380  1.021733e-03         0.001197        0.000977   
0        0.003957  5.842775e-04         0.000200        0.000400   
54       0.036711  1.178974e-03         0.000207        0.000414   
56       0.041488  1.600871e-03         0.000600        0.000490   
16       0.022338  4.887191e-04         0.000400        0.000490   
37       0.004408  5.126914e-04         0.000399        0.000489   
18       0.024133  3.994167e-04         0.000796        0.000398   
58       0.044120  2.675452e-03         0.000399        0.000489   
62       0.050182  1.922739e-03         0.000794        0.000398   
20       0.026330  5.174701e-04         0.001005        0.000015   
60       0.046668  7.395130e-04         0.000199        0.000399   
64       0.051259  1.487452e-03         0.000399        0.000489   
22       0.027929  3.797971e-06         0.000199        0.000398   
66       0.054274  1.000189e-03         0.000581        0.000475   
24       0.029526  4.845765e-04         0.000598        0.000488   
26       0.034704  3.624850e-03         0.000594        0.000485   
68       0.055474  2.791414e-03         0.000189        0.000379   
72       0.069009  1.103466e-02         0.001001        0.001094   
28       0.031725  7.635871e-04         0.000998        0.000002   
70       0.055260  4.828800e-04         0.000787        0.000394   
74       0.068723  5.537987e-03         0.000399        0.000488   
30       0.037101  6.076448e-03         0.000797        0.00