In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, StratifiedKFold

In [2]:
data = pd.read_csv('ISTrend_data.csv')
data

Company        Time  Total Revenues  Operating Income  Net Income  \
0       AMZN  2019-12-01         47635.0            1983.0      1515.0   
1       TSCO  2018-12-01           654.6              15.3       109.8   
2        AZO  2019-08-01           642.6              81.8       279.7   
3        EQT  2018-12-01          1934.8             221.7     -3753.1   
4       SOHU  2013-12-01           333.1             -57.8       -88.2   
5        DRI  2019-05-01           430.3              81.3       117.4   
6         PH  2017-06-01           668.5             166.3       176.6   
7       VRTX  2011-12-01          1267.2             916.3       784.2   
8        PFG  2014-12-01          1188.1             513.6       231.4   
9       DISH  2012-12-01           107.2            -618.2      -879.2   
10       LPX  2017-12-01           500.6             334.4       240.2   
11       LYV  2011-12-01           320.3              23.2       145.4   
12        ED  2018-12-01           304.0            -247.0      -143.0   
13       LNC  2013-12-01           434.0              35.0       -69.0   
14       HAL  2017-12-01          4733.0            1377.0      5300.0   
15      MSEX  2019-12-01            -3.5              -3.5         1.4   
16       AES  2013-12-01         -1273.0            -282.0      1026.0   
17       MED  2016-12-01             1.7               3.3        -2.3   
18       YUM  2018-12-01          -190.0              16.0       202.0   
19       PKG  2018-12-01           569.7             169.4        69.4   
20        SO  2013-12-01           550.0           -1189.0      -706.0   
21       ELP  2016-12-01           253.5              63.3        -4.8   
22       CAT  2012-12-01          5737.0            1757.0       753.0   
23       XOM  2019-12-01        -23749.0           -9908.0     -6500.0   
24      ORCL  2016-05-01         -1179.0           -1185.0     -1037.0   
25       PVH  2014-02-01          2143.4              73.1      -290.3   
26      MSFT  2017-06-01          5417.0            2143.0      4950.0   
27       SRE  2016-12-01           -48.0            -294.0        21.0   
28      MNST  2015-12-01           257.7             219.5        63.5   
29       PRU  2011-12-01         10846.0             919.0       631.0   
...      ...         ...             ...               ...         ...   
4470     GLW  2014-12-01          1896.0             389.0       511.0   
4471    GASS  2018-12-01            10.0               0.1       -11.1   
4472      BP  2011-12-01         79050.0             514.0     28931.0   
4473    MTRN  2016-12-01           -56.1              -4.4        -6.5   
4474    GPRE  2012-12-01           -76.8             -81.2       -26.6   
4475     HLF  2015-12-01          -489.6              45.6        30.4   
4476    ANSS  2014-12-01            74.7              26.1         9.4   
4477     IVZ  2018-12-01           153.8             -59.4      -244.5   
4478     SEE  2011-12-01           977.2              -4.8      -106.8   
4479    SPGI  2016-12-01           348.0             236.0       950.0   
4480    SCCO  2019-12-01           188.9            -128.2       -57.2   
4481     TIF  2018-01-01           168.0              57.9       -76.0   
4482      KR  2014-02-01          1756.0              -2.0        22.0   
4483     AGI  2014-12-01            60.7              33.1         7.2   
4484     BSX  2012-12-01          -373.0             -73.0     -4509.0   
4485     KSS  2015-01-01            -8.0             -53.0       -22.0   
4486     CNC  2011-12-01           766.3              44.9        16.4   
4487     SJM  2014-04-01          -287.1             -17.4        21.0   
4488     GIS  2017-05-01          -943.3              -7.8       -39.9   
4489    ORCL  2018-05-01          1591.0             413.0     -5865.0   
4490       K  2017-12-01          -111.0              -7.0       555.0   
4491     TFX  2018-12-01           302.1              61.9        48.3   
4492     

In [3]:
classes = data['Classification'] 
data = data.drop(['Company', 'Time', 'Classification'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")
    
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Classification', classes)
data

Total Revenues
Done
Operating Income
Done
Net Income
Done
Revenue Per Share
Done
Basic EPS
Done
Normalized Basic EPS
Done
Dividend Per Share
Done
EBITA
Done
EBIT
Done
Normalized Net Income
Done


Total Revenues  Operating Income  Net Income  Revenue Per Share  \
0           0.754239          0.212925    0.488938           0.037673   
1           0.553576          0.196357    0.481506           0.032382   
2           0.553525          0.196917    0.482404           0.035705   
3           0.559044          0.198095    0.461074           0.032107   
4           0.552203          0.195741    0.480458           0.032441   
5           0.552618          0.196912    0.481546           0.032132   
6           0.553636          0.197628    0.481859           0.032294   
7           0.556193          0.203943    0.485073           0.032287   
8           0.555855          0.200552    0.482149           0.032149   
9           0.551238          0.191023    0.476275           0.031885   
10          0.552919          0.199043    0.482195           0.032111   
11          0.552148          0.196423    0.481694           0.031807   
12          0.552079          0.194148    0.480168           0.031916   
13          0.552634          0.196523    0.480560           0.032145   
14          0.570996          0.207822    0.508958           0.032229   
15          0.550765          0.196198    0.480932           0.031867   
16          0.545343          0.193853    0.486352           0.031804   
17          0.550788          0.196256    0.480913           0.031914   
18          0.549969          0.196363    0.481993           0.031936   
19          0.553214          0.197654    0.481292           0.032272   
20          0.553130          0.186216    0.477191           0.031923   
21          0.551863          0.196761    0.480899           0.031949   
22          0.575284          0.211022    0.484908           0.032387   
23          0.449344          0.112803    0.446545           0.031531   
24          0.545745          0.186250    0.475440           0.031896   
25          0.559935          0.196843    0.479389           0.032856   
26          0.573917          0.214272    0.507107           0.031953   
27          0.550575          0.193752    0.481036           0.031857   
28          0.551881          0.198076    0.481261           0.031883   
29          0.597106          0.203966    0.484262           0.033195   
...              ...               ...         ...                ...   
4470        0.558879          0.199503    0.483628           0.032023   
4471        0.550823          0.196229    0.480866           0.031905   
4472        0.888419          0.200556    0.633948           0.032153   
4473        0.550541          0.196191    0.480890           0.031727   
4474        0.550452          0.195544    0.480784           0.032794   
4475        0.548689          0.196612    0.481086           0.031782   
4476        0.551099          0.196448    0.480975           0.031947   
4477        0.551437          0.195728    0.479632           0.031909   
4478        0.554954          0.196187    0.480360           0.032172   
4479        0.552267          0.198215    0.485950           0.032018   
4480        0.551587          0.195148    0.480622           0.031905   
4481        0.551498          0.196715    0.480523           0.031987   
4482        0.558281          0.196211    0.481041           0.032216   
4483        0.551040          0.196507    0.480963           0.031980   
4484        0.549187          0.195613    0.457076           0.031896   
4485        0.550746          0.195782    0.480808           0.032303   
4486        0.554053          0.196606    0.481012           0.032096   
4487        0.549554          0.196081    0.481036           0.031865   
4488        0.546751          0.196162    0.480714           0.031822   
4489        0.557576          0.199705    0.449903           0.031914   
4490        0.550306          0.196169    0.483860           0.031883   
4491        0.552071          0.196749    0.481180           0.032271   
4492        0.552379          0.197621    0.482040           0.0

In [4]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:10] # Parameters
y = NpMatrix[:,10] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.75423917 0.21292468 0.48893807 ... 0.21432902 0.21292468 0.24998533]
 [0.55357628 0.19635667 0.48150562 ... 0.19700335 0.19635667 0.23093844]
 [0.55352502 0.1969166  0.48240426 ... 0.1975557  0.1969166  0.23141158]
 ...
 [0.5658876  0.19423231 0.47595825 ... 0.19441591 0.19423231 0.23161008]
 [0.53574144 0.17061424 0.4720971  ... 0.17126114 0.17061424 0.2105595 ]
 [0.55532448 0.19673389 0.48112056 ... 0.19751528 0.19673389 0.23125428]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 10
Total Number of Training instances: 4500


[1. 1. 1. ... 1. 0. 1.]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 1.0
Total number of y values 4500


In [5]:
# Grid Search for Optimal KNN Hyperparameters
# Using GridSearchCV to find best parameters
kvals = range(1,100)
params = {'n_neighbors': kvals,
        'weights' : ['uniform', 'distance'],
         'metric' : ['euclidean', 'manhattan']}

knn = KNeighborsClassifier()
cv_str = StratifiedKFold(n_splits=5)

gs_modelKNN = GridSearchCV(knn, params,  cv= cv_str)
grid_results = gs_modelKNN.fit(X , y)

# Best parameters, best test score using these parameters, optimal KNN Configuration
print("Best Parameters", gs_modelKNN.best_params_)
print("Best score on Test Data", gs_modelKNN.best_score_)
print("Optimal Configuration", gs_modelKNN.best_estimator_)

Best Parameters {'metric': 'euclidean', 'n_neighbors': 90, 'weights': 'distance'}
Best score on Test Data 0.7022222222222222
Optimal Configuration KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=90, p=2,
                     weights='distance')


In [6]:
# Summarize the results in a readable format
print("Best: {0}, using {1}".format(grid_results.cv_results_['mean_test_score'], grid_results.best_params_))
results_df = pd.DataFrame(grid_results.cv_results_)
results_df

Best: [0.61533333 0.61533333 0.54711111 0.61533333 0.63488889 0.63266667
 0.59622222 0.64155556 0.65888889 0.66       0.63377778 0.65511111
 0.67111111 0.67066667 0.65466667 0.666      0.67733333 0.67422222
 0.66533333 0.67533333 0.68222222 0.68111111 0.67644444 0.68088889
 0.68555556 0.68333333 0.68066667 0.68555556 0.68733333 0.68666667
 0.688      0.68955556 0.68844444 0.68666667 0.68977778 0.69066667
 0.69244444 0.69155556 0.68911111 0.69177778 0.69022222 0.69155556
 0.69311111 0.69266667 0.69488889 0.69466667 0.69533333 0.69288889
 0.69444444 0.69511111 0.69555556 0.69333333 0.694      0.69377778
 0.69622222 0.69333333 0.69444444 0.69688889 0.69311111 0.69577778
 0.69622222 0.69688889 0.69422222 0.69533333 0.69622222 0.69866667
 0.69533333 0.69777778 0.69577778 0.69977778 0.69688889 0.69666667
 0.69422222 0.69377778 0.69444444 0.69555556 0.69533333 0.69666667
 0.69622222 0.69666667 0.69777778 0.69555556 0.69466667 0.69422222
 0.69622222 0.69511111 0.69444444 0.69577778 0.698      

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0         0.002495  6.339278e-04         0.034907        0.008054   
1         0.002593  4.887139e-04         0.012965        0.001545   
2         0.002194  3.992084e-04         0.033114        0.001470   
3         0.001994  3.234067e-07         0.015558        0.001353   
4         0.002394  4.884803e-04         0.042686        0.007231   
5         0.002405  5.028308e-04         0.018345        0.001630   
6         0.002792  7.465067e-04         0.040094        0.005585   
7         0.002792  3.989697e-04         0.018750        0.001716   
8         0.002394  4.887335e-04         0.037500        0.001739   
9         0.002181  4.242708e-04         0.019579        0.001856   
10        0.002584  7.923731e-04         0.047830        0.007823   
11        0.001990  3.620340e-05         0.022541        0.002421   
12        0.002578  7.851249e-04         0.041107        0.003433   
13        0.002006  2.289881e-05         0.021918        0.002581   
14        0.002009  1.966940e-05         0.042672        0.001729   
15        0.002201  4.151357e-04         0.022340        0.001851   
16        0.001979  1.787688e-05         0.041107        0.002217   
17        0.001997  6.616878e-06         0.022737        0.001830   
18        0.002190  3.849709e-04         0.045240        0.004717   
19        0.002193  3.994734e-04         0.023339        0.002053   
20        0.001993  1.761073e-06         0.042486        0.001850   
21        0.001979  1.951517e-05         0.024550        0.002405   
22        0.002410  4.921658e-04         0.043659        0.001935   
23        0.002602  4.890469e-04         0.025324        0.002216   
24        0.002798  7.495048e-04         0.044083        0.002415   
25        0.001994  2.497826e-06         0.025333        0.002054   
26        0.002204  3.943446e-04         0.043686        0.001831   
27        0.002406  4.956584e-04         0.025907        0.001666   
28        0.002205  3.922195e-04         0.044470        0.001611   
29        0.002576  4.915326e-04         0.029129        0.002039   
..             ...           ...              ...             ...   
366       0.002209  4.130482e-04         0.071609        0.005638   
367       0.002397  4.850165e-04         0.053053        0.002396   
368       0.002380  4.873378e-04         0.073816        0.000629   
369       0.002729  3.850070e-04         0.056367        0.002288   
370       0.002200  3.938105e-04         0.070807        0.001086   
371       0.002194  3.990238e-04         0.053649        0.001719   
372       0.002382  4.978295e-04         0.076377        0.004727   
373       0.002204  3.951098e-04         0.054241        0.000489   
374       0.002401  4.819636e-04         0.072722        0.002480   
375       0.002388  4.842777e-04         0.060769        0.005551   
376       0.002589  4.622125e-04         0.075850        0.000705   
377       0.002201  3.976781e-04         0.056641        0.000973   
378       0.002185  4.035395e-04         0.074412        0.005720   
379       0.001993  2.547400e-06         0.054095        0.001186   
380       0.002207  3.947649e-04         0.071046        0.003512   
381       0.002594  4.874495e-04         0.055052        0.001594   
382       0.002394  4.884998e-04         0.069813        0.000892   
383       0.002401  4.805627e-04         0.056490        0.000820   
384       0.002397  4.854736e-04         0.074041        0.002033   
385       0.002587  4.830967e-04         0.054655        0.001170   
386       0.002196  4.001420e-04         0.072007        0.002987   
387       0.002387  4.783303e-04         0.057844        0.001414   
388       0.002401  4.818429e-04         0.072077        0.001438   
389       0.002195  3.972704e-04         0.054852        0.001092   
390       0.002197  3.966142e-04         0.077591        0.008114   
391       0.002390  4.739191e-04         0.057847        0.002458   
392

In [7]:
results_df = results_df.sort_values(['rank_test_score'])
results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
179       0.003782  9.665787e-04         0.079192        0.008454   
187       0.003191  3.989697e-04         0.073205        0.004829   
189       0.003191  3.992803e-04         0.069617        0.003535   
181       0.002593  4.880526e-04         0.066422        0.002569   
167       0.003391  7.974627e-04         0.081684        0.009560   
169       0.002992  2.431402e-07         0.070212        0.003373   
171       0.002992  6.312789e-04         0.068416        0.002999   
157       0.002792  3.985888e-04         0.065425        0.005300   
163       0.002792  3.986836e-04         0.063032        0.002554   
185       0.002991  2.755772e-06         0.067222        0.004020   
191       0.003589  7.985497e-04         0.083776        0.009933   
197       0.003191  9.768925e-04         0.075204        0.012229   
195       0.002992  5.091228e-07         0.081582        0.009300   
165       0.002593  4.886750e-04         0.065425        0.002931   
183       0.003191  3.985406e-04         0.074002        0.008161   
139       0.003389  4.895958e-04         0.074403        0.013072   
193       0.003398  8.136035e-04         0.081486        0.007052   
194       0.002792  3.987790e-04         0.098337        0.010339   
373       0.002204  3.951098e-04         0.054241        0.000489   
175       0.003191  3.991373e-04         0.068419        0.003765   
145       0.003989  8.922301e-04         0.072008        0.006288   
149       0.003191  9.770969e-04         0.060439        0.002410   
177       0.003390  4.888308e-04         0.076200        0.010605   
379       0.001993  2.547400e-06         0.054095        0.001186   
173       0.002792  3.989935e-04         0.065824        0.003025   
184       0.002992  1.092406e-03         0.090358        0.003601   
69        0.002392  4.898678e-04         0.035705        0.002042   
186       0.002792  3.990174e-04         0.090358        0.009946   
153       0.002792  3.986126e-04         0.063829        0.004136   
155       0.003398  7.948514e-04         0.073397        0.012784   
..             ...           ...              ...             ...   
210       0.002594  4.888320e-04         0.040491        0.002423   
18        0.002190  3.849709e-04         0.045240        0.004717   
220       0.002400  4.830322e-04         0.044680        0.002216   
209       0.002578  1.186619e-03         0.021749        0.002215   
206       0.002400  4.796244e-04         0.037619        0.000745   
216       0.002004  2.281455e-05         0.041890        0.000891   
9         0.002181  4.242708e-04         0.019579        0.001856   
207       0.002209  4.111951e-04         0.019939        0.001078   
8         0.002394  4.887335e-04         0.037500        0.001739   
11        0.001990  3.620340e-05         0.022541        0.002421   
14        0.002009  1.966940e-05         0.042672        0.001729   
212       0.002194  3.965164e-04         0.042084        0.001329   
7         0.002792  3.989697e-04         0.018750        0.001716   
205       0.001983  2.397519e-05         0.019355        0.001008   
208       0.002394  4.876833e-04         0.038696        0.000746   
4         0.002394  4.884803e-04         0.042686        0.007231   
10        0.002584  7.923731e-04         0.047830        0.007823   
202       0.002178  4.067417e-04         0.039111        0.003046   
5         0.002405  5.028308e-04         0.018345        0.001630   
203       0.003177  9.952334e-04         0.020963        0.001667   
3         0.001994  3.234067e-07         0.015558        0.001353   
1         0.002593  4.887139e-04         0.012965        0.001545   
0         0.002495  6.339278e-04         0.034907        0.008054   
198       0.002992  3.234067e-07         0.038298        0.001017   
199       0.002793  3.991871e-04         0.016362        0.001014   
201       0.002195  3.987830e-04         0.017153        0.000976   
204