In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_squared_error, make_scorer, mean_absolute_error
from sklearn.model_selection import cross_val_score 
from math import sqrt
from sklearn.model_selection import KFold
from sklearn.model_selection import RepeatedKFold, StratifiedKFold
from sklearn.model_selection import GridSearchCV

In [2]:
data = pd.read_csv('ISTrend_data.csv')
data

Company        Time  Total Revenues  Operating Income  Net Income  \
0       AMZN  2019-12-01         47635.0            1983.0      1515.0   
1       TSCO  2018-12-01           654.6              15.3       109.8   
2        AZO  2019-08-01           642.6              81.8       279.7   
3        EQT  2018-12-01          1934.8             221.7     -3753.1   
4       SOHU  2013-12-01           333.1             -57.8       -88.2   
5        DRI  2019-05-01           430.3              81.3       117.4   
6         PH  2017-06-01           668.5             166.3       176.6   
7       VRTX  2011-12-01          1267.2             916.3       784.2   
8        PFG  2014-12-01          1188.1             513.6       231.4   
9       DISH  2012-12-01           107.2            -618.2      -879.2   
10       LPX  2017-12-01           500.6             334.4       240.2   
11       LYV  2011-12-01           320.3              23.2       145.4   
12        ED  2018-12-01           304.0            -247.0      -143.0   
13       LNC  2013-12-01           434.0              35.0       -69.0   
14       HAL  2017-12-01          4733.0            1377.0      5300.0   
15      MSEX  2019-12-01            -3.5              -3.5         1.4   
16       AES  2013-12-01         -1273.0            -282.0      1026.0   
17       MED  2016-12-01             1.7               3.3        -2.3   
18       YUM  2018-12-01          -190.0              16.0       202.0   
19       PKG  2018-12-01           569.7             169.4        69.4   
20        SO  2013-12-01           550.0           -1189.0      -706.0   
21       ELP  2016-12-01           253.5              63.3        -4.8   
22       CAT  2012-12-01          5737.0            1757.0       753.0   
23       XOM  2019-12-01        -23749.0           -9908.0     -6500.0   
24      ORCL  2016-05-01         -1179.0           -1185.0     -1037.0   
25       PVH  2014-02-01          2143.4              73.1      -290.3   
26      MSFT  2017-06-01          5417.0            2143.0      4950.0   
27       SRE  2016-12-01           -48.0            -294.0        21.0   
28      MNST  2015-12-01           257.7             219.5        63.5   
29       PRU  2011-12-01         10846.0             919.0       631.0   
...      ...         ...             ...               ...         ...   
4470     GLW  2014-12-01          1896.0             389.0       511.0   
4471    GASS  2018-12-01            10.0               0.1       -11.1   
4472      BP  2011-12-01         79050.0             514.0     28931.0   
4473    MTRN  2016-12-01           -56.1              -4.4        -6.5   
4474    GPRE  2012-12-01           -76.8             -81.2       -26.6   
4475     HLF  2015-12-01          -489.6              45.6        30.4   
4476    ANSS  2014-12-01            74.7              26.1         9.4   
4477     IVZ  2018-12-01           153.8             -59.4      -244.5   
4478     SEE  2011-12-01           977.2              -4.8      -106.8   
4479    SPGI  2016-12-01           348.0             236.0       950.0   
4480    SCCO  2019-12-01           188.9            -128.2       -57.2   
4481     TIF  2018-01-01           168.0              57.9       -76.0   
4482      KR  2014-02-01          1756.0              -2.0        22.0   
4483     AGI  2014-12-01            60.7              33.1         7.2   
4484     BSX  2012-12-01          -373.0             -73.0     -4509.0   
4485     KSS  2015-01-01            -8.0             -53.0       -22.0   
4486     CNC  2011-12-01           766.3              44.9        16.4   
4487     SJM  2014-04-01          -287.1             -17.4        21.0   
4488     GIS  2017-05-01          -943.3              -7.8       -39.9   
4489    ORCL  2018-05-01          1591.0             413.0     -5865.0   
4490       K  2017-12-01          -111.0              -7.0       555.0   
4491     TFX  2018-12-01           302.1              61.9        48.3   
4492     

In [3]:
classes = data['Classification'] 
data = data.drop(['Company', 'Time', 'Classification'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")
    
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Classification', classes)
data

Total Revenues
Done
Operating Income
Done
Net Income
Done
Revenue Per Share
Done
Basic EPS
Done
Normalized Basic EPS
Done
Dividend Per Share
Done
EBITA
Done
EBIT
Done
Normalized Net Income
Done


Total Revenues  Operating Income  Net Income  Revenue Per Share  \
0           0.754239          0.212925    0.488938           0.037673   
1           0.553576          0.196357    0.481506           0.032382   
2           0.553525          0.196917    0.482404           0.035705   
3           0.559044          0.198095    0.461074           0.032107   
4           0.552203          0.195741    0.480458           0.032441   
5           0.552618          0.196912    0.481546           0.032132   
6           0.553636          0.197628    0.481859           0.032294   
7           0.556193          0.203943    0.485073           0.032287   
8           0.555855          0.200552    0.482149           0.032149   
9           0.551238          0.191023    0.476275           0.031885   
10          0.552919          0.199043    0.482195           0.032111   
11          0.552148          0.196423    0.481694           0.031807   
12          0.552079          0.194148    0.480168           0.031916   
13          0.552634          0.196523    0.480560           0.032145   
14          0.570996          0.207822    0.508958           0.032229   
15          0.550765          0.196198    0.480932           0.031867   
16          0.545343          0.193853    0.486352           0.031804   
17          0.550788          0.196256    0.480913           0.031914   
18          0.549969          0.196363    0.481993           0.031936   
19          0.553214          0.197654    0.481292           0.032272   
20          0.553130          0.186216    0.477191           0.031923   
21          0.551863          0.196761    0.480899           0.031949   
22          0.575284          0.211022    0.484908           0.032387   
23          0.449344          0.112803    0.446545           0.031531   
24          0.545745          0.186250    0.475440           0.031896   
25          0.559935          0.196843    0.479389           0.032856   
26          0.573917          0.214272    0.507107           0.031953   
27          0.550575          0.193752    0.481036           0.031857   
28          0.551881          0.198076    0.481261           0.031883   
29          0.597106          0.203966    0.484262           0.033195   
...              ...               ...         ...                ...   
4470        0.558879          0.199503    0.483628           0.032023   
4471        0.550823          0.196229    0.480866           0.031905   
4472        0.888419          0.200556    0.633948           0.032153   
4473        0.550541          0.196191    0.480890           0.031727   
4474        0.550452          0.195544    0.480784           0.032794   
4475        0.548689          0.196612    0.481086           0.031782   
4476        0.551099          0.196448    0.480975           0.031947   
4477        0.551437          0.195728    0.479632           0.031909   
4478        0.554954          0.196187    0.480360           0.032172   
4479        0.552267          0.198215    0.485950           0.032018   
4480        0.551587          0.195148    0.480622           0.031905   
4481        0.551498          0.196715    0.480523           0.031987   
4482        0.558281          0.196211    0.481041           0.032216   
4483        0.551040          0.196507    0.480963           0.031980   
4484        0.549187          0.195613    0.457076           0.031896   
4485        0.550746          0.195782    0.480808           0.032303   
4486        0.554053          0.196606    0.481012           0.032096   
4487        0.549554          0.196081    0.481036           0.031865   
4488        0.546751          0.196162    0.480714           0.031822   
4489        0.557576          0.199705    0.449903           0.031914   
4490        0.550306          0.196169    0.483860           0.031883   
4491        0.552071          0.196749    0.481180           0.032271   
4492        0.552379          0.197621    0.482040           0.0

In [5]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:10] # Parameters
y = NpMatrix[:,10] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.75423917 0.21292468 0.48893807 ... 0.21432902 0.21292468 0.24998533]
 [0.55357628 0.19635667 0.48150562 ... 0.19700335 0.19635667 0.23093844]
 [0.55352502 0.1969166  0.48240426 ... 0.1975557  0.1969166  0.23141158]
 ...
 [0.5658876  0.19423231 0.47595825 ... 0.19441591 0.19423231 0.23161008]
 [0.53574144 0.17061424 0.4720971  ... 0.17126114 0.17061424 0.2105595 ]
 [0.55532448 0.19673389 0.48112056 ... 0.19751528 0.19673389 0.23125428]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 10
Total Number of Training instances: 4500


[1. 1. 1. ... 1. 0. 1.]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector 1.0
Total number of y values 4500


In [6]:
params_RF = {'n_estimators':range(1,30),
            'max_depth' : range(1,15),
            }

cv_str = StratifiedKFold(n_splits=5)

RF = RandomForestClassifier()
gs_modelRF = GridSearchCV(RF, param_grid=params_RF, cv= cv_str)
grid_results = gs_modelRF.fit(X, y)

# Best parameters, best test score using these parameters, optimal KNN Configuration
print("Best Parameters", gs_modelRF.best_params_)
print("Best score on Test Data", gs_modelRF.best_score_)
print("Optimal Configuration", gs_modelRF.best_estimator_)

Best Parameters {'max_depth': 6, 'n_estimators': 28}
Best score on Test Data 0.7046666666666667
Optimal Configuration RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=6, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=28,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)


In [7]:
# Summarize the results in a readable format
print("Best: {0}, using {1}".format(grid_results.cv_results_['mean_test_score'], grid_results.best_params_))
results_df = pd.DataFrame(grid_results.cv_results_)
results_df

Best: [0.67355556 0.67511111 0.67511111 0.67511111 0.67577778 0.67133333
 0.67511111 0.67644444 0.67511111 0.67511111 0.67511111 0.67511111
 0.67511111 0.67511111 0.67511111 0.67511111 0.67511111 0.67511111
 0.67511111 0.67511111 0.67511111 0.67511111 0.67511111 0.67511111
 0.67511111 0.67511111 0.67511111 0.67511111 0.67511111 0.68044444
 0.68644444 0.69177778 0.68466667 0.68933333 0.69222222 0.69577778
 0.69466667 0.69688889 0.69844444 0.69555556 0.68933333 0.69777778
 0.69088889 0.696      0.69466667 0.69711111 0.69488889 0.69044444
 0.696      0.69666667 0.69288889 0.696      0.69266667 0.69822222
 0.696      0.69466667 0.69622222 0.69955556 0.68333333 0.69355556
 0.694      0.69266667 0.69911111 0.69911111 0.69822222 0.69822222
 0.69488889 0.69311111 0.70133333 0.69711111 0.69511111 0.7
 0.69755556 0.69844444 0.69955556 0.70155556 0.69288889 0.70044444
 0.69933333 0.69888889 0.69666667 0.70044444 0.69955556 0.69866667
 0.69488889 0.69977778 0.70222222 0.67977778 0.692      0.69288

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0         0.002210      0.000391         0.000973    1.984204e-05   
1         0.004176      0.000979         0.001009    9.067205e-04   
2         0.005001      0.000641         0.000591    4.825647e-04   
3         0.005786      0.000398         0.000997    5.722046e-07   
4         0.006783      0.000398         0.000997    7.599534e-07   
5         0.008177      0.000401         0.000989    1.555644e-05   
6         0.009582      0.000495         0.000991    1.491472e-05   
7         0.010771      0.000399         0.001396    4.883078e-04   
8         0.012757      0.000396         0.001005    1.420543e-05   
9         0.014362      0.000789         0.001596    7.977009e-04   
10        0.018367      0.003240         0.001396    4.890317e-04   
11        0.016371      0.000507         0.001379    4.863984e-04   
12        0.017154      0.000397         0.001796    3.975450e-04   
13        0.018746      0.000397         0.001591    5.011049e-04   
14        0.019946      0.000631         0.001597    4.893135e-04   
15        0.023528      0.001345         0.001796    3.993058e-04   
16        0.024933      0.000631         0.001994    1.168008e-07   
17        0.026130      0.000399         0.001995    2.431402e-07   
18        0.028723      0.001934         0.002593    4.884027e-04   
19        0.028316      0.000802         0.002609    4.857650e-04   
20        0.027926      0.000619         0.002991    1.742903e-06   
21        0.028522      0.000472         0.002403    4.812507e-04   
22        0.029523      0.000490         0.002393    4.906347e-04   
23        0.030917      0.000004         0.002592    4.872560e-04   
24        0.034109      0.002632         0.002794    3.984300e-04   
25        0.033310      0.000489         0.002985    1.595703e-05   
26        0.035032      0.000249         0.002991    1.997031e-06   
27        0.035704      0.000401         0.002984    1.513791e-05   
28        0.037297      0.000488         0.003002    1.380804e-05   
29        0.002600      0.000479         0.000400    4.894537e-04   
..             ...           ...              ...             ...   
376       0.191058      0.005691         0.005405    5.129341e-04   
377       0.007775      0.000397         0.000602    4.919022e-04   
378       0.014172      0.000392         0.000999    1.419342e-06   
379       0.020343      0.000490         0.001000    1.997031e-06   
380       0.026920      0.000637         0.001405    4.969760e-04   
381       0.034965      0.002212         0.000989    1.788832e-05   
382       0.040341      0.000555         0.001197    3.986395e-04   
383       0.046472      0.000784         0.001796    4.016130e-04   
384       0.053457      0.000488         0.001994    2.403184e-06   
385       0.063536      0.003175         0.002593    4.718262e-04   
386       0.066614      0.001477         0.002201    3.957045e-04   
387       0.072406      0.001019         0.002193    3.988772e-04   
388       0.082794      0.004654         0.002985    1.617919e-05   
389       0.086162      0.001362         0.002404    4.775628e-04   
390       0.094104      0.003786         0.003005    2.114922e-05   
391       0.098739      0.001677         0.002990    9.142350e-06   
392       0.106706      0.004489         0.003591    4.890649e-04   
393       0.113518      0.001813         0.003390    4.922544e-04   
394       0.121131      0.004998         0.003980    6.194152e-04   
395       0.127170      0.003343         0.003791    3.977608e-04   
396       0.132660      0.002285         0.004373    4.846377e-04   
397       0.144074      0.003111         0.004388    4.876066e-04   
398       0.149608      0.002376         0.004389    4.886166e-04   
399       0.158785      0.004822         0.004787    7.476665e-04   
400       0.159978      0.002058         0.004984    6.265369e-04   
401       0.165718      0.000998         0.004828    4.048898e-04   
402

In [8]:
results_df = results_df.sort_values(['rank_test_score'])
results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
172       0.106549  2.225107e-03         0.004189    9.773791e-04   
164       0.077180  1.022221e-03         0.002992    2.431402e-07   
105       0.055843  1.888840e-03         0.002395    4.876265e-04   
171       0.102932  2.302509e-03         0.003775    4.115292e-04   
136       0.069415  4.727197e-04         0.002791    3.995916e-04   
86        0.066817  6.316361e-04         0.003403    4.799862e-04   
141       0.085798  1.224224e-03         0.003590    4.896318e-04   
161       0.064426  1.013140e-03         0.002393    4.863888e-04   
162       0.067819  6.313550e-04         0.002793    3.999748e-04   
197       0.102326  1.196766e-03         0.002992    3.162980e-07   
104       0.050459  4.866118e-04         0.002794    3.977026e-04   
190       0.073203  1.352431e-03         0.002992    9.536743e-08   
75        0.042296  4.984924e-04         0.001986    1.608179e-05   
187       0.060837  6.303741e-04         0.002594    4.884998e-04   
140       0.084784  3.850306e-03         0.003388    4.913429e-04   
106       0.059839  2.272992e-03         0.002793    7.465058e-04   
198       0.108318  3.879368e-03         0.003989    1.038148e-06   
68        0.028317  1.344199e-03         0.001797    3.997449e-04   
112       0.074611  3.128845e-03         0.003772    7.475128e-04   
163       0.073841  3.510837e-03         0.002592    4.877827e-04   
132       0.059251  3.937829e-03         0.003199    1.459968e-03   
167       0.088170  1.739569e-03         0.003179    3.853627e-04   
111       0.069805  1.482987e-05         0.002990    2.435700e-05   
168       0.093380  6.259311e-03         0.003605    4.867270e-04   
138       0.083211  7.343459e-03         0.003178    3.757332e-04   
125       0.033322  4.783092e-04         0.001984    2.201181e-05   
108       0.062252  8.805949e-04         0.002578    5.096212e-04   
288       0.156780  6.979225e-03         0.004788    3.990652e-04   
317       0.163712  4.927030e-03         0.004986    1.200645e-06   
216       0.065442  4.867592e-04         0.002194    3.972414e-04   
..             ...           ...              ...             ...   
322       0.025141  3.953196e-04         0.000997    2.073008e-06   
321       0.019148  3.991431e-04         0.000997    2.605643e-06   
116       0.003994  3.633906e-05         0.000598    4.882663e-04   
384       0.053457  4.883713e-04         0.001994    2.403184e-06   
174       0.005584  7.983209e-04         0.000998    7.387129e-07   
263       0.016940  2.777739e-05         0.001006    1.401853e-05   
292       0.018152  4.187523e-04         0.001003    1.632497e-05   
382       0.040341  5.546594e-04         0.001197    3.986395e-04   
175       0.009175  3.991604e-04         0.000200    3.991127e-04   
354       0.046788  1.179885e-03         0.001808    4.057456e-04   
233       0.010971  5.560829e-07         0.000997    4.422006e-07   
323       0.030915  6.315807e-04         0.000998    1.948625e-06   
204       0.009972  1.767516e-06         0.000599    4.892484e-04   
232       0.005575  4.792182e-04         0.000808    4.048544e-04   
352       0.033717  1.942222e-03         0.001198    3.985666e-04   
203       0.005194  3.960945e-04         0.000399    4.888697e-04   
261       0.006182  3.992602e-04         0.000598    4.882291e-04   
350       0.019347  4.887724e-04         0.000998    1.168008e-07   
351       0.026130  3.989697e-04         0.000998    2.780415e-07   
290       0.008185  7.542322e-04         0.001199    3.983489e-04   
380       0.026920  6.366454e-04         0.001405    4.969760e-04   
319       0.006781  4.171900e-04         0.000800    4.007613e-04   
377       0.007775  3.969951e-04         0.000602    4.919022e-04   
379       0.020343  4.901963e-04         0.001000    1.997031e-06   
262       0.011178  3.957287e-04         0.001004    1.301390e-05   
320       0.012966  6.295491e-04         0.000397    4.865341e-04   
348