In [10]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, make_scorer, mean_absolute_error
from sklearn.model_selection import cross_val_score 
from math import sqrt
from sklearn.model_selection import KFold
from sklearn.model_selection import RepeatedKFold

In [11]:
data = pd.read_csv('DeltaIS_data.csv')
data

Company        Time  Total Revenues  Operating Income  Net Income  \
0       VERU  2018-09-01             2.2              -9.3       -17.3   
1        MAS  2017-12-01         -1347.0             -52.0        40.0   
2        EPD  2014-12-01           224.2              86.1       190.5   
3       ANSS  2015-12-01             6.8               5.1        -2.2   
4       GLUU  2017-12-01            86.2              -5.2       -10.2   
5       SBUX  2011-10-01           993.0             132.8       300.1   
6        CRM  2018-01-01          2103.0             236.0        37.0   
7        TJX  2016-01-01          1866.5              98.2        62.6   
8         PG  2015-06-01         -3652.0            -833.0     -4607.0   
9        WAT  2013-12-01            60.6              -5.6       -11.4   
10       PEG  2016-12-01         -1449.0            -545.0      -792.0   
11       LNT  2014-12-01            73.5               9.7        24.8   
12       EIG  2016-12-01            27.7              40.2        12.3   
13      SPGI  2011-12-01           315.0              76.0        83.0   
14       HHS  2014-12-01           -60.2             -20.1        10.6   
15      FIZZ  2015-05-01             4.7               9.6         5.7   
16       MAS  2018-12-01           640.0             100.0       201.0   
17      BKNG  2016-12-01          1519.0             610.5      -416.4   
18       ATO  2016-09-01          -472.4              45.0        35.0   
19      CINF  2017-12-01           283.0             -82.0       454.0   
20      FFIV  2011-09-01           269.8             120.7        90.2   
21       NVR  2014-12-01           232.2              19.6        15.1   
22       URI  2017-12-01           879.0             225.0       780.0   
23      PRGO  2016-12-01           266.0             -73.4     -4010.9   
24       GLP  2015-12-01         -6955.1             -41.6       -72.8   
25       AFL  2014-12-01         -1009.0             -99.0      -207.0   
26       XOM  2014-12-01        -25484.0           -6219.0       -60.0   
27      SEIC  2015-12-01            68.2              11.5        13.0   
28       NOC  2012-12-01         -1194.0            -146.0      -140.0   
29       CME  2014-12-01           181.3             130.2       150.3   
...      ...         ...             ...               ...         ...   
4470     GWW  2012-12-01           871.8              78.7        31.5   
4471    CHRW  2015-12-01             6.0             109.9        60.0   
4472    MGEE  2014-12-01            28.2              10.1         5.4   
4473     TRV  2014-12-01          1094.0             263.0        19.0   
4474     SJM  2018-04-01           -35.2             -18.6       746.3   
4475    NXST  2019-12-01           272.6             -98.4      -159.2   
4476     IAG  2017-12-01           107.8             543.8       449.0   
4477     WHR  2012-12-01          -523.0             161.0        11.0   
4478     GWW  2017-12-01           288.0             -48.0       -20.0   
4479     FIS  2014-12-01           349.6              88.9       185.9   
4480     MSI  2017-12-01           342.0              88.0      -715.0   
4481     MKC  2019-11-01            44.6              54.1      -230.7   
4482     STE  2017-03-01           379.8              19.9        -0.8   
4483     HON  2014-12-01          1251.0             330.0       315.0   
4484     PWR  2011-12-01           564.4             -49.3       -20.7   
4485       T  2018-12-01         10210.0            7623.0    -10080.0   
4486     MET  2017-12-01          1576.0            -791.0      3160.0   
4487     TIF  2014-01-01           236.9              96.7      -234.8   
4488      EW  2016-12-01           470.0             176.5        74.6   
4489     NKE  2012-05-01          3214.0             228.0        78.0   
4490     STX  2011-07-01          -424.0           -1039.0     -1098.0   
4491      CF  2016-12-01          -623.0            -759.0      -977.0   
4492     

In [12]:
prices = data['Price_Change'] 
data = data.drop(['Company', 'Time', 'Price_Change'], axis = 1)

col_list = []
for col in data.columns:
    col_list.append(col)
    
for col in col_list:
    print(col)
    data[col] = data[col].astype(float) # Converting columns to floats
    print("Done")

Total Revenues
Done
Operating Income
Done
Net Income
Done
Revenue Per Share
Done
Basic EPS
Done
Normalized Basic EPS
Done
Dividend Per Share
Done
EBITA
Done
EBIT
Done
Normalized Net Income
Done


In [13]:
# Normalising the data
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
scaled_values = scaler.fit_transform(data) 
data.loc[:,:] = scaled_values

data.insert(data.shape[1], 'Price_Change', prices)
data

Total Revenues  Operating Income  Net Income  Revenue Per Share  \
0           0.550790          0.196150    0.480833           0.031883   
1           0.545027          0.195790    0.481136           0.031669   
2           0.551738          0.196953    0.481932           0.031842   
3           0.550809          0.196271    0.480913           0.031913   
4           0.551149          0.196184    0.480871           0.031928   
5           0.555022          0.197346    0.482512           0.031931   
6           0.559763          0.198215    0.481121           0.032050   
7           0.558753          0.197055    0.481256           0.032018   
8           0.535182          0.189214    0.456557           0.031808   
9           0.551039          0.196181    0.480865           0.031974   
10          0.544591          0.191639    0.476736           0.031705   
11          0.551094          0.196310    0.481056           0.031911   
12          0.550899          0.196566    0.480990           0.031928   
13          0.552126          0.196868    0.481364           0.031987   
14          0.550523          0.196059    0.480981           0.031274   
15          0.550800          0.196309    0.480955           0.031896   
16          0.553514          0.197070    0.481988           0.032062   
17          0.557268          0.201368    0.478722           0.034212   
18          0.548763          0.196607    0.481110           0.031566   
19          0.551989          0.195537    0.483326           0.032005   
20          0.551933          0.197244    0.481402           0.032096   
21          0.551772          0.196393    0.481005           0.041557   
22          0.554535          0.198122    0.485050           0.032692   
23          0.551916          0.195610    0.459710           0.032029   
24          0.521074          0.195878    0.480540           0.011940   
25          0.546471          0.195394    0.479830           0.031867   
26          0.441933          0.143864    0.480608           0.031689   
27          0.551072          0.196325    0.480994           0.031924   
28          0.545681          0.194999    0.480184           0.032278   
29          0.551555          0.197324    0.481720           0.031922   
...              ...               ...         ...                ...   
4470        0.554504          0.196890    0.481091           0.032683   
4471        0.550806          0.197153    0.481242           0.031983   
4472        0.550901          0.196313    0.480953           0.031942   
4473        0.555453          0.198442    0.481025           0.032521   
4474        0.550630          0.196071    0.484872           0.031956   
4475        0.551945          0.195399    0.480083           0.032249   
4476        0.551241          0.200807    0.483300           0.031891   
4477        0.548547          0.197583    0.480983           0.031197   
4478        0.552010          0.195824    0.480819           0.032724   
4479        0.552274          0.196976    0.481908           0.031991   
4480        0.552241          0.196969    0.477143           0.032120   
4481        0.550971          0.196683    0.479705           0.031890   
4482        0.552403          0.196395    0.480921           0.031825   
4483        0.556124          0.199006    0.482591           0.032001   
4484        0.553191          0.195813    0.480815           0.032047   
4485        0.594389          0.260413    0.427609           0.031834   
4486        0.557512          0.189568    0.497639           0.032087   
4487        0.551792          0.197042    0.479683           0.031993   
4488        0.552788          0.197714    0.481319           0.031940   
4489        0.564508          0.198148    0.481337           0.032025   
4490        0.548969          0.187479    0.475117           0.031962   
4491        0.548119          0.189837    0.475757           0.031729   
4492        0.555517          0.201777    0.482252           0.0

In [14]:
# Converting Data to Numpy Arrays
NpMatrix = data.to_numpy(dtype = None, copy = False)
X = NpMatrix[:,0:10] # Parameters
y = NpMatrix[:,10] # Price
print("X:", X)
print("\n")
print("Type X:", type(X))
print("Length of Individual X_train Vector:", len(X[1]))
print("Total Number of Training instances:", len(X))
print("\n")
print(y)
print("\n")
print("Type y:", type(y))
print("Length of Individual y_train vector", y[0])
print("Total number of y values", len(y))

X: [[0.55078975 0.19614954 0.48083335 ... 0.19679791 0.19614954 0.23076491]
 [0.54502704 0.19579001 0.48113643 ... 0.19644511 0.19579001 0.2300708 ]
 [0.55173795 0.19695281 0.48193246 ... 0.19764158 0.19695281 0.2308885 ]
 ...
 [0.54792847 0.19951753 0.47877213 ... 0.20016419 0.19951753 0.23339155]
 [0.54039705 0.19187471 0.47656652 ... 0.19186468 0.19187471 0.22802217]
 [0.55013796 0.19398813 0.47958932 ... 0.19463483 0.19398813 0.22874749]]


Type X: <class 'numpy.ndarray'>
Length of Individual X_train Vector: 10
Total Number of Training instances: 4500


[-1.23 12.32  2.97 ...  5.11 -1.5  -1.95]


Type y: <class 'numpy.ndarray'>
Length of Individual y_train vector -1.23
Total number of y values 4500


In [44]:
# Repeated KFOLD
# prepare the cross-validation procedure
#from sklearn.model_selection import RepeatedKFold
#cv2 = RepeatedKFold(n_splits=10, n_repeats=10, random_state=1)

In [15]:
decision_tree = DecisionTreeRegressor(criterion='mse', max_depth=6, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='random')

In [16]:
CV = KFold(n_splits=10, random_state=None, shuffle=False)

In [17]:
# Applying k-Fold Cross Validation 
# https://stackoverflow.com/questions/24132237/scikit-learn-cross-validation-scoring-for-regression#:~:text=How%20can%20one%20use%20cross_val_score%20for%20regression%3F%20The,accuracy%2C%20which%20is%20not%20very%20meaningful%20for%20regression.
#mse = make_scorer(mean_squared_error, greater_is_better= False)
mae = make_scorer(mean_absolute_error, greater_is_better= False) 
scores = cross_val_score(decision_tree, X, y, scoring= mae, cv = CV) 

print(scores)

print("Mean MAE:", scores.mean())
print("SD of the mean:", scores.std())

[-18.8679733  -17.8248985  -15.37987712 -18.84682309 -17.78750806
 -14.89557195 -15.53199462 -14.42791815 -18.77697534 -14.42166068]
Mean MAE: -16.676120081292183
SD of the mean: 1.8105595708645585
